### ISSUE TITLE
Automation: Foreign key column missing on child repeat group tables

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/ConSoSci#100]
## Describe the bug
In the training yesterday, we had users run their Kobo forms through the automation solution. For repeat groups, we always create a table that should look up to the parent "form" table. For example... if we have a `survey` that has a repeat group to capture information on `household members`, we expect 2 DB tables will be outputted (`TableSurvey`, `TableSurvey_HhMembers`)... but I expect that  `TableSurvey_HhMembers` will also have a foreign key column to link it to the parent `TableSurvey` -e.g., `tablesurvey_uuid`). See diagram: 
https://docs.google.com/presentation/d/16ZenDRq3zmX6LgrH4_g3O9lISTve42ZDJgjm7RThbTY/edit#slide=id.gd20fa61edc_0_547

In running the solution, we see that the foreign key was correctly referenced in the OpenFn auto-generated jobs, but not includes in the auto-generated SQL output. Therefore, when we go to sync data to the DB, we encounter `error: column "mpahhsurvey_uuid" of relation "wwf_test_mpahhsurvey_hhmembersquestionssubgroup" does not exist`
https://www.openfn.org/projects/p5w6xn/runs/rwazn5pd

See this run of job 2A that does not seem to have configured the column `mpahhsurvey_uuid` to link `wwf_test_mpahhsurvey_hhmembersquestionssubgroup` with the parent table. 
https://www.openfn.org/projects/p5w6xn/runs/ryam9yrx

## To Reproduce
Here is the original run from job `00`: https://www.openfn.org/projects/p5w6xn/runs/r7xd3mp7
This fetched form `aF83yMqfW5AikzRkvca8Bx` from the `wcs_training` Kobo account (see LP). 

**To test on prod... please use the `Consosci Training`.**

### expression.js
https://github.com/OpenFn/ConSoSci/blob/master/automation/02a-syncToPostgres.js

### state.json
Kobo: see LP for `WCS Training Kobo`
DB: see LP for `WCS ConSoSOc DB`

## adaptor
postgres

## Expected behavior
We should be able to re-run this Message without errors if the database is auto-configured correctly: 
https://www.openfn.org/projects/p5w6xn/messages/mmq3b4ng

**Comment by aleksa-krolls** [comment]
@lakhassane I need your help again. We need to filter the `dataArrays` by unique values before executing `upsertMany` statements, otherwise we encounter this error: https://openfn.org/projects/p5x4g4/runs/r9wemzp4
```
The MERGE statement attempted to UPDATE or DELETE the same row more than once. This happens when a target row matches more than one source row. A MERGE statement cannot UPDATE/DELETE the same row of the target table multiple times. Refine the ON clause to ensure a target row matches at most one source row, or use the GROUP BY clause to group the source rows.
```

See state (https://openfn.org/projects/p5x4g4/messages/mrbnqnpd) where we are trying to insert multiple `BigTrees` with the same `btspecies` name. We need to filter this repeat group array by unique `btspecies` before we try to `upsertMany(WCSPROGRAMS_VegetationBigTrees)`
```
"tree_10cm": [
      {
        "tree_10cm/bdbh": "34.5",
        "tree_10cm/bheight": "12.0",
        "tree_10cm/btspecies": "Ficus_vallis-choudae"
      },
      {
        "tree_10cm/bdbh": "48.3",
        "tree_10cm/bheight": "15.0",
        "tree_10cm/btspecies": "Ficus_vallis-choudae"
      },
      {
        "tree_10cm/bdbh": "55.7",
        "tree_10cm/bheight": "23.2",
        "tree_10cm/btspecies": "Newtonia_buchananii"
      },
      {
        "tree_10cm/bdbh": "24.0",
        "tree_10cm/bheight": "18.5",
        "tree_10cm/btspecies": "Ficus_vallis-choudae"
      },
      {
        "tree_10cm/bdbh": "23.0",
        "tree_10cm/bheight": "24.5",
        "tree_10cm/btspecies": "Ficus_vallis-choudae"
      }
    ],
```
See relevant part of job: https://github.com/OpenFn/ConSoSci/blob/master/vegetation/VegetationClassficationAndTreeMeasurementForm.js#L573-L578

**Comment by lakhassane** [comment]
@aleksa-krolls I made the change. Feel free to test.

**Comment by aleksa-krolls** [comment]
@lakhassane Looks like job `2b` is auto-creating jobs with custom ids that have underscores `generated_uuid`. 
But job `2a` that auto-generates the DB config outputs `generateduuid`. 

Therefore when we run the job, we encounter the error `error: column "generated_uuid" of relation "wcs_test_sharksrays" does not exist`. 

Please update job `2b` so that the automatic job mappings will reference `generateduuid` (no underscore) to match the DB. 
See this example job (https://www.openfn.org/projects/p5w6xn/jobs/jvrqp5) generated via this OpenFn run: https://www.openfn.org/projects/p5w6xn/runs/rmkw4r49
