### ISSUE TITLE
Enable openfn static ip

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/ConSoSci#101]
For connecting with the following DBs...
`WCS Programs Database (central db)` (mssql)
`WCS ConSoSOc DB (For automation testing)` (postgres) - this might already be enabled

**Comment by taylordowns2000** [comment]
This is done. https://openfn.slack.com/archives/C01N1ASUKML/p1618926685000200

**Comment by aleksa-krolls** [comment]
@taylordowns2000 Are you sure this is done? Here is the error I'm seeing... it's showing a different IP than the static IP you told me to share with WCS (`35.245.0.180`): 
https://www.openfn.org/projects/p5x4g4/runs/rn5799gd

**Comment by taylordowns2000** [comment]
@stuartc , I've confirmed that the IP address of the database we're trying to connect to with that run is the `wcs` one on this list yet their DB still appears to be blocking our requests. Is it possible that since the job attempts to connect to `wcsprograms.database.windows.net` rather than `41.79.78.106` it's not being routed through the NAT?

```tfvars
fixed_ip_targets = {
  wcs = {
    ip = "40.79.153.12/32"
    description = "NAT Route for WCS Central database"
  },
  ...
}
```

**Comment by stuartc** [comment]
The ip address bound to that dns entry is:40.78.225.32

Using nslookup (for future reference)

So that firewall rule isn't going to redirect for that domain.

Did they change domains or dns or something?

**Comment by taylordowns2000** [comment]
Either that or I got the wrong IP initially—I'd been checking with `ping` rather than `nslookup`. I'm running `terraform apply` now with the new IP.

**Comment by taylordowns2000** [comment]
@aleksa-krolls , updated to the new IP. I think the change should be fairly quick so if you still see failures after ~10min please let me know.

I'm hoping that someone on our team (me?) got the inital IP wrong for that database. If, however, that db is accessible at multiple IPs or if their IPs are changing, this will be a continual problem. (I doubt that's the case, but it would be pretty hilarious.)

**Comment by taylordowns2000** [comment]
@stuartc , let's take a peek at this today—see email from Steve, still doesn't seem to be working.

**Comment by taylordowns2000** [comment]
@aleksa-krolls , we added another WCS IP today and I have re-run a few—things look good but see my email for notes going forward.

![image.png](https://images.zenhubusercontent.com/566ac5e0638e718c995f5356/4f1226be-5edc-452c-b5b2-95eb939237ac)
