### ISSUE TITLE
bns_matrix mappings output `0` instead of `1` for yes values

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/ConSoSci#102]
## Describe the bug
OpenFn is uploading `0` values to the DB, when we expect `1` values for `"yes"` answers. 
![image](https://user-images.githubusercontent.com/16758106/115584410-71719380-a2d3-11eb-8c08-1a7703630724.png)
See issue #3 for context on this job logic. This issue affects `necessary`, `have`, and `quantity` columns. 
https://github.com/OpenFn/ConSoSci/blob/master/bns/survey.js#L79-L89

## To Reproduce
Run is successful but returns `0` values: https://www.openfn.org/projects/p5x4g4/runs/r89ej4ab
In the job it looks like in `alterState` we try to convert yes/no values to 1/0s ... but does not seem to be passing through to the `matrix` item mappings (but I know this logic is interesting, so probably a bug). 

### expression.js
`bns/survey.js` --> mssql adaptor

### state.json
See LP for `WCS Programs Database`. 
https://www.openfn.org/projects/p5x4g4/messages/me6adwqa

## Expected behavior
If we receive "yes" values in these `matrix` questions, we should return `1`, not `0` as is. 

To test, run the sql query `select AnswerId, Necessary, Have, Quantity from WCSPROGRAMS_KoboBnsAnswerGS where AnswerId='71351445'`

**Comment by lakhassane** [comment]
@aleksa-krolls I think the issue might on the sample data.
if you see this line (as well as the one for `necessary`and `quantity`) https://github.com/OpenFn/ConSoSci/blob/56392e08fafe3fba5fcd6af7cef75334f1cbf720/bns/survey.js#L81

We expect the data to be prefixed with `hh_assets`, which is not the case in the sample data joined to that issue. Then the value is translated as `undefined` thus the `0`

**Comment by aleksa-krolls** [comment]
@lakhassane great catch! Please update the job to handle both potential naming styles...
1. `hh_assets/bns_matrix_${item}/bns_matrix_${item}_possess`  (original) OR
2. `bns_matrix_${item}/bns_matrix_${item}_possess` (new)
 
To test, please re-run the following states: 
1. Example state: https://www.openfn.org/projects/p5x4g4/messages/mqqrnjgj
2. Example states: 
https://www.openfn.org/projects/p5x4g4/messages/m4pg6vrw
https://www.openfn.org/projects/p5x4g4/messages/me6adwqa

**Comment by dianedetoeuf** [comment]
Hello, 
What is very strange is that another submission from the same form seems to be sending data properly, see answer ID 677799 for example.

**Comment by aleksa-krolls** [comment]
@daissatou2 can you share the link to the Kobo form? I strangely can't find this data in OpenFn when searching `{"body":{"_id": 677799}}`

https://www.openfn.org/projects/p5x4g4/messages?endDate=2021-04-22T07%3A43%3A23.146Z&searchString=%7B%22body%22%3A%7B%22_id%22%3A%20677799%7D%7D&startDate=2020-04-22T07%3A43%3A28.356Z

**Comment by dianedetoeuf** [comment]
sorry sorry my bad! ID is 72912522

**Comment by aleksa-krolls** [comment]
@dianedetoeuf interesting... we last processed this data in November, so I wonder if we processed this assuming the naming convention was `bns_matrix...`, but then later adjusted it when we saw new data coming in. 

Can I re-process this Message now? My guess is that is we re-run the job, the values will _not_ output correctly in the DB. https://www.openfn.org/projects/p5x4g4/messages/mj6nvrjk

**Comment by dianedetoeuf** [comment]
Yes maybe the mapping was adjusted for Uganda after some of these Ndoki data came in, and as the Ndoki data were cleaned over the last few months it could be the reason why the output was then 0. Yes lets re-run!

**Comment by lakhassane** [comment]
@aleksa-krolls I made the change and check for different path for the value of those columns.

**Comment by aleksa-krolls** [comment]
@dianedetoeuf I've tested the changes and looking good my side. See these 2 examples... can you review to confirm? If looking good, we can re-process these older submissions. 

`hh_assets...` format
1. Message (input): https://www.openfn.org/projects/p5x4g4/messages/mqqrnjgj
2. Run (output): https://www.openfn.org/projects/p5x4g4/runs/rzde9x3m

`bns_matrix` format
1. Message: https://www.openfn.org/projects/p5x4g4/messages/m4pg6vrw
2. Run: https://www.openfn.org/projects/p5x4g4/runs/rg5n89p6

**Comment by dianedetoeuf** [comment]
Looking good! I've added in 1B the forms that should need resyncing.

**Comment by aleksa-krolls** [comment]
@dianedetoeuf fyi, this was re-ran: https://www.openfn.org/projects/p5x4g4/runs/r5ew6wdm

Let us know if anything else pops up, but closing this issue for now. Thanks @lakhassane !

**Comment by dianedetoeuf** [comment]
Thank you both!
