### ISSUE TITLE
Automation jobs: new handling for `select_one` questions to create 1:m relationships

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/ConSoSci#103]
## Background, context, and business value
As discussed, Kobo `select_one` questions typically display a dropdown list of choices, which will be values on a reference table in the destination DB. Therefore WCS requested the development of a `findValue(...)` helper function to more quickly look up parent records and populate foreign keys on related tables. 

## Request
Update jobs `02a` and `02b` to anticipate that every `select_one` or `select_multiple` question indicates that there is a `1:many` or `many:many` relationship in the DB we need to handle. 

If Kobo question is `select_one` or `select_multiple`...
1. Modify the DB sql script (job `02a`), to (1) generate a parent reference table for this select question, as well as (2) relationship columns to link the Kobo answer main tables to this new parent table. 
For example, if Kobo `select_one` question is `Country`...
1. OpenFn to create a table called `{p1}_{p2}_Country` to capture the Country select_one values. This table should have the columns `CountryID`, `CountryName`. Add this logic to the auto-generated sql to create a parent table for every `select` question. 
2. On the main form table ([see L46](https://github.com/OpenFn/ConSoSci/blob/master/automation/auto/sharksAndRays.js#L46)), OpenFn to create column `CountryID` that is a foreign key to the table created in 1 --> `{p1}_{p2}_Country`. This ensures that the main tables auto-generated will be related to these new reference tables. 
```
table: WCS_Sharks_Country, //{p1}_{p2}_{koboQuestion}, 
primary key: CountryID, //{koboQuestionName} + 'ID'
column: CountryName, //{koboQuestionName} + 'Name'
```

2. Modify the auto-generated job (see job `02b` or [this auto example](https://github.com/OpenFn/ConSoSci/blob/master/automation/auto/sharksAndRays.js#L46)) to add a `findValue(...)` helper function to the mappings as a default. For example...
https://github.com/OpenFn/ConSoSci/blob/73566768e61fc1c15079140bf539b0020fc7ab1a/automation/auto/sharksAndRays.js#L46
Because `Country` is a `select_one` Kobo question, this mapping should instead output as...
```
CountryID: await findValue({
uuid: 'CountryID',  //{koboQuestion} + 'ID' //pk
relation: 'WCS_Sharks_Country', //{p1}_{p2}_{koboQuestion} ... parent table
where: {
'CountryName' = dataValue('country')(state)} //{koboQuestionName} + 'Name' = dataValue(koboQ)
}),
```

## state
See LP for `ConSoSci DB (automation)` to test. 
Here is a Kobo form with uid `ayd6iLVGgvEiXnT6bRxWvH` that you can fetch from the `openfn_kobo` account: https://kf.kobotoolbox.org/#/forms/ayd6iLVGgvEiXnT6bRxWvH/summary

## expression
Updates to jobs `02a` and `02b` to auto-generate sql and OpenFn jobs that interpret Kobo `select` questions as needing relationship DB tables & related mappings. 

## Output
See this job auto-generated for SharksAndRays: https://github.com/OpenFn/ConSoSci/blob/master/automation/auto/sharksAndRays.js
Ideally this `auto` update will automatically handle relationship columns and tables. 

Here is some Messages to test the job output: https://github.com/OpenFn/ConSoSci/blob/master/sample_data/state_sharksAndRays.json
https://www.openfn.org/projects/p5w6xn/messages?endDate=2021-04-27T07%3A43%3A26.886Z&triggerId=t9anpe

Another example, if `survey` is a `select_one` question... then create a table `{p1}_{p2}_Survey` to capture these dropbox values. Then map a 1:m relationship in the auto-generated jon...
```
SurveyID: await findValue({
uuid: 'SurveyID',  //{koboQuestion} + 'ID' //pk
relation: '{p1}_{p2}_Survey', //{p1}_{p2}_{koboQuestion} ... parent table
where: {
'SurveyName' = dataValue('survey')(state)} //{koboQuestionName} + 'Name' = dataValue(koboQ)
}),
```

## To Test
You can clear state and re-run this job `00` for this form (https://www.openfn.org/projects/p5w6xn/jobs/jyjxzd) to inspect the outputs of jobs `02a` and `02b`

**Comment by lakhassane** [comment]
@aleksa-krolls First question here:

Here is an example of a auto-generated job for the new reference tables. You see the `undefined` in here because there is not an actual path for `CountryID` or `CountryName`.
Is it fine to just replace it with `dataValue('CountryID')` or what would you advise here?

```js
upsert("OpenFn_Test_country", "GeneratedUuid", {
  country_ID: dataValue("undefined"),
  country_Name: dataValue("undefined"),
  Payload: state.data.body,
  GeneratedUuid: dataValue("__generatedUuid"),
});
upsert("OpenFn_Test_survey", "GeneratedUuid", {
  survey_ID: dataValue("undefined"),
  survey_Name: dataValue("undefined"),
  Payload: state.data.body,
  GeneratedUuid: dataValue("__generatedUuid"),
});
```

**Comment by lakhassane** [comment]
The job is correctly generated here @aleksa-krolls minus my comment on `undefined` path.
https://www.openfn.org/projects/p5w6xn/jobs/jveb4g

And here are the tables created: https://www.openfn.org/projects/p5w6xn/runs/rg5nbpwe

**Comment by aleksa-krolls** [comment]
@lakhassane immediate feedback...
**1. foreign key mappings**
In the `findValue(...)` mappings, make sure the `where` clause points to the Kobo question name (not the destination DB column name, as discussed). For example, see `LandingSite` on L91: https://www.openfn.org/projects/p5w6xn/jobs/jveb4g

Current mapping...
`LandingSite: findValue({uuid: 'LandingSiteID', relation: 'OpenFn_Test_LandingSite', where: { LandingSiteName: dataValue('LandingSite')(state), },}),` <- _and is the comma after `(state),` going to be an issue?_ 

I think the mapping should be referencing `landing_site` instead: 
`LandingSite: findValue({uuid: 'LandingSiteID', relation: 'OpenFn_Test_LandingSite', where: { LandingSiteName: dataValue('landing_site')(state)}}),`

**2. I want to make an adjustment to how we configure & map the reference tables.** 
```
upsert('OpenFn_Test_landing_site', 'GeneratedUuid', {
  LandingSiteID: dataValue('undefined'),
  LandingSiteName: dataValue('undefined'),
  Payload: state.data.body,
  GeneratedUuid: dataValue('__generatedUuid')
}); 
```
Can we please... 
1. always clean the name columns (e.g., `LandingSiteName` to remove `_` and capitalize the first letter. 
2. add another column to these tables that will be called `{QuestionName}ExtCode` (e.g., `LandingSiteExtCode`). Here we can directly map the value from Kobo. Consider if this requires changes to the SQL auto-generated script to configure this as a field that we can use to upsert records (see #3). 
3. `GeneratedUuid` you can get rid of this field mapping for the reference tables only and rather using the `ExtCode` column as the unique lookup. 

Therefore this outputted mapping should look like...
```
upsert('OpenFn_Test_landing_site', ' LandingSiteExtCode', {
  LandingSiteID: dataValue('undefined'),
  LandingSiteExtCode: dataValue('landing_site'), 
  LandingSiteName: dataValue('landing_site').replace(...)
  Payload: state.data.body,
}); 
```

**Comment by lakhassane** [comment]
@aleksa-krolls I made all the requirements in here (see image) but for the `replace()` Im still thinking about the best way. Because we don't only need to generate that function but a whole function that is wrapping the `dataValue()` and that returns values.

<img width="738" alt="Screen Shot 2021-05-11 at 15 11 31" src="https://user-images.githubusercontent.com/8411231/117839894-2bbd4080-b26b-11eb-8b8e-ca6ee78112f4.png">

**Comment by aleksa-krolls** [comment]
@lakhassane Is everything done except for the `replace(...)` question? If yes, can you please...
1. Run the automation solution to auto-generate new DB tables and (2) new job. You can connect to the `WCS ConSoSci DB` for this testing. 
2. Then run the auto-generate job (2) against these states to confirm the data will sync as expected: https://www.openfn.org/projects/p5w6xn/messages/m58d8ak8
https://www.openfn.org/projects/p5w6xn/messages/mqp9padg

This state data is from the same form... so I'd expect it to integrate with the DB with no errors. If there are errors, we may need to adjust the auto-generated outputs from the `02a` and `02b` jobs.

**Comment by aleksa-krolls** [comment]
@lakhassane new states to test with: 
https://www.openfn.org/projects/p5x4g4/messages/mwba4jb3
https://www.openfn.org/projects/p5x4g4/messages/m58d7k8d

**Comment by aleksa-krolls** [comment]
@lakhassane I've done further review of the data and have further feedback below. [See here](https://www.openfn.org/projects/p5x4g4/jobs/jyp96p) for my auto-generated job, and [see here](https://www.openfn.org/projects/p5x4g4/runs/r7xrz3bb) for the sql script. 

1. We need to assign a primary key to the reference tables (e.g., `countryid`)...
![image](https://user-images.githubusercontent.com/16758106/118101922-cf7c2d00-b3e0-11eb-8676-8721f0651571.png)

Otherwise when we load data to child submission data tables, the columns will output `{}` because there is no `ID` to return in this foreign key field. 
![image](https://user-images.githubusercontent.com/16758106/118102026-efabec00-b3e0-11eb-9f0e-12b4e9089854.png)

```
Country: findValue({uuid: 'CountryID', relation: 'OpenFn_Sharks_Country', where: { CountryName: dataValue('country')(state) }}),
```
2. We need to add `AnswerId` as a default column to all of data tables, in additional to `GeneratedUuid`. (This excludes the reference tables and the `Kobodataset` table - not needed on these.) This is the Kobo submission id, so we need it visible on every record related to that submission. 
I thought we had this before, but I no longer see this column in the DB or job output. The mapping should be....
```
AnswerId: dataValue('_id'), 
```

**Comment by lakhassane** [comment]
@aleksa-krolls for your point `1` here do you think using the `identity` query you sent me would solve it? Because I can change the LP now.

**Comment by lakhassane** [comment]
So both of those points were implemented @aleksa-krolls . If you want to use the latest changes for postgresql, feel free to update any job on the latest adaptor version.

**Comment by aleksa-krolls** [comment]
@lakhassane Nearly there... one thing I've noticed is that on the reference tables, if there is no value in state to insert into an available reference table (e.g., `country`, `district`, `survey`)... we still insert a "blank" row. We should expect that with every Kobo submission, a row might _not_ be upserted in the reference tables. 

For example, there is the `openfn_sharks_district` reference table based on the Kobo select_one question `district`. However, [this message](https://www.openfn.org/projects/p5x4g4/messages/m78n56jd) the `district` question was not answered and is not included in the Kobo payload... but we still output a "blank" record in the DB. 
![image.png](https://images.zenhubusercontent.com/5d691cd53295e300013f1cbd/cbab446a-6090-4649-9c90-aceede91f557)

Can we make a change to the logic for auto-generated jobs to only upsert if there is an available value in state? (Wondering if we should consider an `upsertIf(...)` function... what do you think?)
See auto-generated job I was testing with: https://www.openfn.org/projects/p5x4g4/jobs/jyp96p

**Comment by lakhassane** [comment]
@aleksa-krolls yeah I think we might better consider the `upsertIf` otherwise the job is going to be hardly maintenable considering all the adds

**Comment by aleksa-krolls** [comment]
@lakhassane fyi, I just noticed another issue. While the reference table ids are now being set nicely...
![image.png](https://images.zenhubusercontent.com/5d691cd53295e300013f1cbd/f108141e-ab82-4dae-816a-ff6a48a3122d)
... the foreign keys on the child survey tables are still not linking back to these parent tables and shows `{}`. Can you check on that `findValue(...)` function? 
![image.png](https://images.zenhubusercontent.com/5d691cd53295e300013f1cbd/8ab53818-2c22-4c4c-b983-a02a0ed4e594)
I also wonder if maybe we need to generate foreign key constraints when we create these fk columns... I don't see that in the DB table properties, and I wonder if that affects this. 
![image.png](https://images.zenhubusercontent.com/5d691cd53295e300013f1cbd/07874ebc-e080-432f-acd2-7ea4265f97c8)

Please let me know if I can help test/ if I should delete the DB tables for you to re-run.

**Comment by aleksa-krolls** [comment]
@lakhassane in case you missed it, the bottom of this comment has details for testing: https://github.com/OpenFn/ConSoSci/issues/103#issuecomment-840419490

Let me know how it goes/ how I can help with testing.

**Comment by lakhassane** [comment]
@aleksa-krolls I ran the test. See here: https://www.openfn.org/projects/p5x4g4/runs/r44wdmzm

**Comment by aleksa-krolls** [comment]
@lakhassane Same result... let's get on the phone when you're back online to test together. Also with the new vpn setup, we should be able to get you into DBeaver. 
![image.png](https://images.zenhubusercontent.com/5d691cd53295e300013f1cbd/9be6c685-cd1f-44b7-b900-af5b4cf277c5)

**Comment by lakhassane** [comment]
@aleksa-krolls for this last one I think we might need to consider changing syncToOpenFn to generate an alterState with async await. I'm checking for how long it would take.
If running succesfully this job is urgent I can make the manual changes (about 10mn of work) but otherwise, I will update the automation job to try to solve this problem.

**Comment by aleksa-krolls** [comment]
@lakhassane We need to make this change in the automation solution ... it's going to come up again and again. Please keep me posted on estimates and how I can support.

**Comment by lakhassane** [comment]
@aleksa-krolls I think we are good there. I refactor the automation to generate the `alterState` with `async/await` to make this work (see sample https://www.openfn.org/projects/p5x4g4/jobs/jyp96p).

<img width="779" alt="Screen Shot 2021-05-26 at 17 51 24" src="https://user-images.githubusercontent.com/8411231/119707710-fdcf2300-be4a-11eb-9a9e-5fc01039eade.png">

**Comment by lakhassane** [comment]
Next question would be if you think it can happen we need to use findValue on nested repeat group (those operation with the big `each` and `upsertMany`.
If yes, can you open an issue for it and I might need to do the same thing as we did and it's a bit complicated than above.

**Comment by aleksa-krolls** [comment]
@lakhassane This flow is currently failing so I can't test... see run: https://www.openfn.org/projects/p5x4g4/runs/rwapydwn

To replicate, please run job 1 with the following: https://www.openfn.org/projects/p5x4g4/jobs/jyd8gg
```
{ uid: 'apZrpKcK78xzrPcAfRrfac', p1:'WCSPROGRAMS', p2: 'SharksRays', tableId: 'SharksRays'},
```

**We need this resolved today, so please pause WfW work as needed.**
