### ISSUE TITLE
Change `id` to number each element in the repeat groups array for BNS and Price tables

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/ConSoSci#107]
## Request
Currently we map the Kobo Answer `_id` to the `Id` primary key in some of these repeat group tables. This means that repeat group items (e.g., `hhmember`) will have the same primary key if they belong to the same form. 
![image](https://user-images.githubusercontent.com/16758106/118110279-e6278180-b3ea-11eb-8855-15f422375466.png)
WCS wants `Id` to rather show the count of `hhmembers` in the array (e.g., return `0, 1, 2, 3...` instead of `94627217`). 
![image](https://user-images.githubusercontent.com/16758106/118110037-9779e780-b3ea-11eb-9e05-5d1acdbeb41d.png)

Can you please make this change to the `Id` mapping for these 2 tables across the 2 jobs? 
1. `survey.js` count `WCSPROGRAMS_KoboBnsAnswerhhmembers`: 
https://github.com/OpenFn/ConSoSci/blob/928869cf64e962971beb8841c236498e384c7bd8/bns/survey.js#L146-L150

2. `price.js` count `WCSPROGRAMS_KoboBnsPrice`
https://github.com/OpenFn/ConSoSci/blob/master/bns/price.js#L66-L86

## state
See LP for WCS Programs
1. survey - look for the `hh_members: [...]`: https://www.openfn.org/projects/p5x4g4/messages/mqp9bzga
2. price - look for the `good: [...]` : https://www.openfn.org/projects/p5x4g4/messages/mwbg768q

## adaptor
mssql

**Comment by lakhassane** [comment]
@aleksa-krolls I mapped the counts for both those jobs

**Comment by aleksa-krolls** [comment]
@dianedetoeuf thanks for all the screenshots... this should be good to go, going forward. Do we want to re-sync some or all of the BNS and Price surveys?

**Comment by aleksa-krolls** [comment]
@lakhassane I'm now seeing this run failure and I think it's related to the recent change... can you check it out and please advise? 
https://www.openfn.org/projects/p5x4g4/runs/r7x877a7
```
executing insert many via: INSERT INTO WCSPROGRAMS_KoboBnsAnswerhhmembers (DatasetUuidId, Id, AnswerId, Head, Gender, Ethnicity, Birth, LastUpdate) VALUES [--REDACTED--]];
Cannot insert duplicate key row in object 'dbo.WCSPROGRAMS_KoboBnsAnswerhhmembers' with unique index 'idx_uq_WCSPROGRAMS_KoboBnsAnswerhhmembers_DatasetUuidId_AnswerID_ID'. The duplicate key value is (BNS Makira 2021-aVLz2FxFcw99cv89xNY46K, 94627099, 8).

/home/app/priv/language_packs/language-mssql-v2.3.3/lib/Adaptor.js:432
            throw err;
            ^
RequestError: Cannot insert duplicate key row in object 'dbo.WCSPROGRAMS_KoboBnsAnswerhhmembers' with unique index 'idx_uq_WCSPROGRAMS_KoboBnsAnswerhhmembers_DatasetUuidId_AnswerID_ID'. The duplicate key value is (BNS Makira 2021-aVLz2FxFcw99cv89xNY46K, 94627099, 8).
```
I'm wondering if this change we implemented won't work.... because if we have 2 households each with 3 members, the job will try to insert members `1`, `2`, `3` twice (one set for each household)... and therefore we'll have rows on this `hhmembers` table with the same `ID`. 
@dianedetoeuf let's discuss on our call today... I think we'll either need to remove this unique constraint or consider a new `ID` scheme (e.g., `AnswerId + hhmemberID` like `94627099-1`, `94627099-2`, etc.)

**Comment by lakhassane** [comment]
@aleksa-krolls it's not exactly related to the recent changes. 

Here are the duplicated values: `(BNS Makira 2021-aVLz2FxFcw99cv89xNY46K, 94627099, 8)`. 
They correspond to `(datasetId, _id, count(hh_members))` so even if we reverted the changes we will have `(datasetId, _id, _id))` (what we had before) and we will probably have duplications because it seems like we cannot have rows in the DB with the same exact combinations values for those 3 columns.

**Comment by aleksa-krolls** [comment]
@lakhassane So I think we're inserting the repeat group records (`hh_members`) incorrectly / I may have not done a good job communicating the requirement. For example...
1. This state has 8 `hh_member` items: https://www.openfn.org/projects/p5x4g4/messages/m78nw9jp
2. I therefore expect 8 rows to be inserted in the table `WCSPROGRAMS_KoboBnsAnswerhhmembers`... 1 row for every item in the array. And I expect the `id` field to reflect which `n`th item in the array that member is...
![image](https://user-images.githubusercontent.com/16758106/118836192-52632300-b8cc-11eb-8971-f35c7b28539c.png)

Right now in the DB, I only see 1 row for `hh_members` inserted where `id: 8` which looks like the total count... rather than 1 row for every repeat group item. See run failure: https://www.openfn.org/projects/p5x4g4/runs/r898n5xb
![image](https://user-images.githubusercontent.com/16758106/118836402-7b83b380-b8cc-11eb-844d-a0154a9226c8.png)

**Comment by lakhassane** [comment]
ahh I get it now. I understood something else through `count`. I made the correction but for the `insertMany` and not the `insert` where you put 0 as id.

I'm correcting same for `price.js`

**Comment by aleksa-krolls** [comment]
@dianedetoeuf I think this `hh_members` and repeat group issue is resolved now. Can you please verify the output in the db for `"AnswerId": 94627099`? 
See run here that shows how we inserted individual records for every hh member: https://www.openfn.org/projects/p5x4g4/runs/r3xmyb94

If this looks good... I can plan to bulk resync all the BNS submissions :)

**Comment by dianedetoeuf** [comment]
Yes we do have the 9 households!! Well done =) and thank you! Ok to do the bulk resync (I assume its ok too for the prices?)

**Comment by aleksa-krolls** [comment]
@dianedetoeuf yes, please go for it... let me know if you need help/ get stuck.
