### ISSUE TITLE
Legacy plant json data prep help

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/ConSoSci#109]
## Background, context, and business value
The client is trying to move legacy survey data captured outside of Kobo from an old database to their central DB (where all the Kobo data lives). This legacy data for 1 survey submission is spread across 6 tables. 

## The specific request, in as few words as possible
I need your help building a new "state.json" that collapses data from across the 6 tables to output 1 state for every survey submission. This will involve matching and grouping data by `surveyid` from the different JSON files. 

## state.json
Input: We have 6 JSON payloads that contain different data for survey submissions (submission uid: `surveyid`). 
1. biomass: https://www.openfn.org/projects/p5x4g4/messages/ma9bv43q
2. general: https://www.openfn.org/projects/p5x4g4/messages/m5839q6n
3. ground_species: https://www.openfn.org/projects/p5x4g4/messages/mdbqj5e4
4. groundtruthing: https://www.openfn.org/projects/p5x4g4/messages/m4p7jb3q
5. liana_old: https://www.openfn.org/projects/p5x4g4/messages/mv76pn4g
6. native_tree_shrub: https://www.openfn.org/projects/p5x4g4/messages/mpq7nd34

See output for how to combine these, matching on `surveyid`. 

## output.json
We should output several `survey` JSON objects (1 per unique `surveyid`) that include `surveyid`, `survey_area`, `transect_no`, and `Plot_no`, and have related `biomass`, `general`, `ground_species`, etc. records that should be captured as arrays. 
```
{
   "tag": "legacy_plant_data",
   "surveys": {
        "surveyid": "birunguc321",
        "survey_area": "Birungu",
        "Transect_no": "C32",
        "Plot_no": 1,
        "biomass": [
            {
                "Species": "Ficus ingens",
                ...
            }
        ],
        "general": [...],
        "ground_species": [...],
        "groundtruthing": [...],
        "liana_old": [...],
        "native_tree_shrubs": [...]
    }
}
```
**Can you please generate this new state and post back to the WCS inbox?** Make sure it contains `"tag": "legacy_plant_data"` in the Message body. 
https://www.openfn.org/projects/p5x4g4/messages

**Comment by lakhassane** [comment]
And each object is inside that big `surveys`array
```

{
   "tag": "legacy_plant_data",
   "surveys": [ ALL_IN_HERE ]
}
```

**Comment by aleksa-krolls** [comment]
@lakhassane that looks good, please push to inbox!

**Comment by lakhassane** [comment]
Done :)

**Comment by dianedetoeuf** [comment]
Thank you both! Will try and create the job to send those messages.

**Comment by aleksa-krolls** [comment]
@dianedetoeuf Here is the new state produced: https://www.openfn.org/projects/p5x4g4/messages/m8qvjvbr
Remember that I created the custom uid `surveyid`, which is similar to `AnswerId`. 
Keep us posted on you job drafting. Mamadou and I would be happy to jump on a call to walk through your job whenever you're ready. Look for the credential `wcsprograms db` in the WCS project to test this :)

**Comment by dianedetoeuf** [comment]
Hi, I thought I had seen the tag at some point but now can't find it - it should be in the message right?

**Comment by lakhassane** [comment]
@dianedetoeuf probably at the last line
<img width="372" alt="Screen Shot 2021-05-21 at 12 19 23" src="https://user-images.githubusercontent.com/8411231/119136114-c7e70480-ba2e-11eb-943c-c717040b0c9c.png">

**Comment by dianedetoeuf** [comment]
Ha :D thanks!
