### ISSUE TITLE
Update job to handle multiple `observername` paths

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/ConSoSci#111]
## Request
The current job references the data source value `state.data.body.observername` in several places. However, for different Kobo survey versions... the path for `observername` changes. 

In all relevant places, please update the job so that `observername` may be found in...
```
state.data.body.observername || state.data.body.obsevername || state.data.body['general_observations/obsevername']
``` 
## state
See L63 in this message: https://www.openfn.org/projects/p5x4g4/messages/m58q4qdm
See LP for `wcs programs` db... but feel free to re-run this on prod. 

## adaptor
mssql 

## expression
https://github.com/OpenFn/ConSoSci/blob/92bef07957a67569091b9b7b4b145d249a56b27b/vegetation/VegetationClassficationAndTreeMeasurementForm.js#L332-L384

**Comment by aleksa-krolls** [comment]
@lakhassane thanks for sharing. The challenge is that this Kobo form has been changed multiple times... so some Messages might have the paths currently referenced in the job... but then it looks like we might need to handle alternative paths for different Kobo form versions (similar to how we support multiple paths for `observername`. 

Please add alternative paths for these arrays as well please...
1. `state.data.body.brush_repeat` || `state.data.body.liana/brush_repeat` --> and to create a unique set, use `liana/brush_repeat/brus_species`
2. L650: `state.data.body.tree_repeat` || `state.data.body.liana/tree_repeat --> and to create a unique set, use `liana/tree_repeat/shrub_species`
3. L703: `state.data.body.tree_repeat` || `state.data.body.outering/tree_10cm` --> and to create a unique set, use `outering/tree_10cm/btspecies`
4. `state.data.body.st_grass_repeat` || `state.data.body.plot_forest_area/st_grass_repeat` --> and to create a unique set, use `plot_forest_area/st_grass_repeat/grass_species`

And for the standard field assignment mappings, can you advise how I can have the job check 2 paths for a value. For example, if we have...
https://github.com/OpenFn/ConSoSci/blob/ccbdca8523bd511361ddc0ae03544a106e23d4c5/vegetation/VegetationClassficationAndTreeMeasurementForm.js#L676
... can I simply re-write the mapping like this? 
```
WCSPROGRAMS_VegetationTreesCode: data['tree_repeat/shrub_species'] || 
   data['liana/tree_repeat/shrub_species'],
```

**Comment by lakhassane** [comment]
@aleksa-krolls for your second question yes you can do that. But I created a path variable that we can update so we can keep it in one place.

```
  const path = state.data.body.st_grass_repeat
    ? 'st_grass_repeat'
    : 'plot_forest_area/st_grass_repeat';

[....]
 UnknownSpeciesImage: data[`${path}/noknown`],



```

**Comment by lakhassane** [comment]
@aleksa-krolls see line `707`in here. That snippet inserts `tree_repeat`but somehow that line has `tree_10cm`on it (which is inserted in operations below that one). Is it a typo to correct?

https://github.com/OpenFn/ConSoSci/blob/ccbdca8523bd511361ddc0ae03544a106e23d4c5/vegetation/VegetationClassficationAndTreeMeasurementForm.js#L703-L712

**Comment by lakhassane** [comment]
I made the correction for the paths and left you a note in the code for my comment above.

**Comment by aleksa-krolls** [comment]
@lakhassane I'm made some minor corrections per your further testing and notes... but when I went to re-run this across a couple of different forms, I noticed `observername` is still not mapping properly. 

See [this Message](https://www.openfn.org/projects/p5x4g4/messages/m58q4qdm) where  `"general_observations/obsevername": "lukato namuleme"`. It looks like we reference this path, but the data value is returning undefined in the run: https://www.openfn.org/projects/p5x4g4/runs/r6gejrn8
```
Executing query: select WCSPROGRAMS_VegetationObserverID from WCSPROGRAMS_VegetationObserver where WCSPROGRAMS_VegetationObserverExtCode = 'undefined'
```

**Comment by lakhassane** [comment]
@aleksa-krolls I got what the issues is about.
this pattern below implies we expect `general_observations/obsevername` to be an array but it's not (it's a value) so the mapping after for the upsert is not correct.
```js
const dataArray =
    state.data.body.observername ||
    state.data.body.obsevername ||
    state.data.body['general_observations/obsevername'] ||
    []; //turning select_multiple into an arrray
```

But for the other operations it works because we have array in those (e.g `"liana/tree_repeat"`).
I'm fixing it but it's might always required manual corrections if the payload is that heterogeneous.

**Comment by lakhassane** [comment]
drafted correction awaiting @aleksa-krolls review

**Comment by aleksa-krolls** [comment]
@lakhassane Can you help me ensure we're only upserting unique `oberservername` records. See recent run failure: https://www.openfn.org/projects/p5x4g4/runs/r3xmrzwk

And please re-run until we get a success on prod! :)

**Comment by lakhassane** [comment]
@aleksa-krolls Green check :D https://www.openfn.org/projects/p5x4g4/runs/rn5dbp36
