### ISSUE TITLE
New handling for `select` questions in nested repeat groups

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/ConSoSci#113]
## Request
See issue #103 for details. We'll want to implement this same logic for scenarios where a `select` question is in a nested repeat group. 

Your last comment about this: 
Next question would be if you think it can happen we need to use findValue on nested repeat group (those operations with the big `each` and `upsertMany`.
If yes, can you open an issue for it and I might need to do the same thing as we did and it's a bit more complicated than above.

_Originally posted by @lakhassane in https://github.com/OpenFn/ConSoSci/issues/103#issuecomment-848994123_

**Comment by lakhassane** [comment]
@aleksa-krolls I replicated for the other operations as well.

Find the last generated job in here: https://www.openfn.org/projects/p5x4g4/jobs/jyzq3d
