### ISSUE TITLE
Generate message for updated legacy plant data

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/ConSoSci#114]
## Background, context, and business value
See issue #109 for the background and specifications to follow. WCS has cleaned some of the data so we need to repeat this again with a new set of JSON payloads. 

## The specific request, in as few words as possible
Please follow those specs from the old issue to repeat this request, but using the JSON payloads linked to below. Also please use the tag `legacy_plant_data_v2`.  

1. biomass: https://www.openfn.org/projects/p5x4g4/messages/ma9bv43q
2. general: https://www.openfn.org/projects/p5x4g4/messages/mn57zpm6
3. ground_species: https://www.openfn.org/projects/p5x4g4/messages/mdbqj5e4
4. groundtruthing: https://www.openfn.org/projects/p5x4g4/messages/m4p7jb3q
5. liana_old: https://www.openfn.org/projects/p5x4g4/messages/mv76pn4g
6. native_tree_shrub: https://www.openfn.org/projects/p5x4g4/messages/mpq7nd34

## output
Messages created and posted to the WCS inbox should look like this: 
https://www.openfn.org/projects/p5x4g4/messages/mgk5v7dz

**Comment by aleksa-krolls** [comment]
@lakhassane please take this on whenever you're ready to move to the next item in the backlog. @dianedetoeuf we can send you the new Message link when ready, but the structure should be the same... so you can continue using the older Message as reference for what this state.json will look like.

**Comment by lakhassane** [comment]
@aleksa-krolls the new payload is posted to the inbox: https://www.openfn.org/projects/p5x4g4/messages/mv7q93dw
FYI, I think all the payloads are the same but the `general`one.
