### ISSUE TITLE
Add mssql capability to 'automation' solution

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/ConSoSci#115]
## Background, context, and business value
Currently the automation solution integrates with Postgres DB. See issue #51 for original background, and ConSoSci docs site: https://openfn.github.io/ConSoSci/kobo-automation/

## The specific request, in as few words as possible
The client wants all the exact same functionality to work with mssql. Note that the client may still sometimes want to integrate with postgres, so we should preserve this functionality. 
**Question: How will compatibility work... will this be a separate set of jobs? Or will the client simply change the adaptor from `postgres` to `mssql` when they want to change the destination DB? **

## state.json
Kobo - See LP for `openfn_kobo`
DB - See LP for `WCS Test Mssql DB`

## adaptor
mssql

## expression.js
Relevant `automation` jobs, including `02a`
https://github.com/OpenFn/ConSoSci/tree/master/automation

## output.json
Once we have the DB, you can test by running the following through job 1: https://www.openfn.org/projects/p5x4g4/jobs/jyd8gg
```
{ uid: 'apZrpKcK78xzrPcAfRrfac', p1:'WCSPROGRAMS', p2: 'SharksRays', tableId: 'SharksRays'}
```

**Comment by lakhassane** [comment]
@aleksa-krolls so a priori the jobs will remain the same because both of those adaptors have the same set of parameters.

I will more bet on changing the adaptor from `postgres` to `mssql`.

I will open a set of issues in `mssql` as needed

**Comment by aleksa-krolls** [comment]
@lakhassane I added the mssql test db cred details in the issue above. Fyi, it is a copy of their DB... so there will be existing tables and data, but it is a test environment... so no worries about running the automation solution and creating tables and all that.

**Comment by lakhassane** [comment]
Noted @aleksa-krolls thanks

**Comment by lakhassane** [comment]
Using this place to add a bunch of notes:
1. `int4`, `float4` not available in mssql. Should find a way to either alter `processForms.js` (a processForm2.js) or make a quick check in `syncToPostgres.js` to add `4`or remove it depending on the adaptor.

**Comment by lakhassane** [comment]
@aleksa-krolls so it's all good for replicating for `mssql`. Minus the point 1 and 2 and 4 above everything is okae.

I need to make 1 minor change to `processForm.js` that would not affect it.

Though, I would suggest we have a `syncToMssql.js`since I'm not sure inside the job we can detect what adaptor is running and depending on it we would decide if we are using `int4` or `int`

**Comment by aleksa-krolls** [comment]
@lakhassane Is this ready to test? Can we meet later today to walk through it?
