### ISSUE TITLE
Convert lat/long values to integer

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/ConSoSci#118]
## Request
I adjusted the `Latitude` and `Longitude` mappings to include some other possible source values. However, now when I re-run the job it's failing with the error `RequestError: Arithmetic overflow error converting varchar to data type numeric.`
https://www.openfn.org/projects/p5x4g4/runs/r5e49n6g

I think this is because the `east` and `north` values I'm mapping might need to be converted to a format that works with the DB columns configured.

## expression
https://github.com/OpenFn/ConSoSci/blob/dd306159868f2924c8727aeb2026a7a2bfa081ef/vegetation/VegetationClassficationAndTreeMeasurementForm.js#L279-L292

## state
See LP for WCS Programs DB
https://www.openfn.org/projects/p5x4g4/messages/mrbnqnpd

## To Test
Please re-run on prod to get green checks!

**Comment by lakhassane** [comment]
@aleksa-krolls this has to do with the data type in the database. Let me explain
`Latitude` (and longitude) is set as `decimal (8, 6)`. That means when inserting we expect a total of **8** digits in the whole columns but **6** digits after decimal. 

So if we insert something like: 
`26.8993` it turns in the db as `26.899300`
`1` ==> `1.000000`
But in the other hand:
`278594` ==> `278594.000000` which is above what is expected and it fails.

Maybe should consider changing the data type to `float`? or advise if we should clean `east`/`north` to insert

**Comment by aleksa-krolls** [comment]
@lakhassane We need to clean the Kobo data to align with the DB data types. So please transform `east`/`north` to output the correct Lat/Long formats.

**Comment by aleksa-krolls** [comment]
@lakhassane I am asking the client how to transform these values.

**Comment by aleksa-krolls** [comment]
@lakhassane WCS wrote a custom function in sql called `fn_WCS_UTIMtoCoord` to do this conversion. From the client: 
```
You can call it with something like:

SELECT Latitude, Longitude FROM .dbo.fn_WCS_UTIMtoCoord( Zone, East, North )

I used this as the basis for a table valued function:
https://stackoverflow.com/questions/7872539/easting-northing-to-latitude-longitude
 ```
**Can you add a select statement to the end of the job to call this function?** 

To test - you can run this job against the message linked to in the issue above. Then, run this query in the DB to check that Lat and Long have been populated: 
```
SELECT Latitude, Longitude, East, North FROM WCSPROGRAMS_Vegetation WHERE Answer_ID='87261613'
```
cc @dianedetoeuf

**Comment by lakhassane** [comment]
Hey @aleksa-krolls I was checking this and how to use that function. However, Im not sure if `( Zone, East, North )` are litterals or values from state. If it's the latter, we also don't have `Zone` in the state which might be a blocker.

**Comment by aleksa-krolls** [comment]
@lakhassane See slack thread and convo with Steve on Asana task. Feel free to message him directly: https://openfn.slack.com/archives/G2LJCFFDW/p1624387848041000?thread_ts=1624358687.032100&cid=G2LJCFFDW

**Comment by lakhassane** [comment]
@aleksa-krolls I made the conversion to latitude/longitude.
<img width="311" alt="Screen Shot 2021-06-24 at 17 34 37" src="https://user-images.githubusercontent.com/8411231/123307816-74c30e80-d512-11eb-8d54-6109d404dccb.png">
