### ISSUE TITLE
Kobo automation flow - data dictionary expansion

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/ConSoSci#119]
## Background, context, and business value
Extension to the automation solution - [see docs & diagrams](https://openfn.github.io/ConSoSci/kobo-automation/)

## The specific request, in as few words as possible
See summary of request and sample output in [this sheet](https://docs.google.com/spreadsheets/d/1MemLYtWkzQosf0jlpVnWLepAuwnUHohCCcUG4tE4MR8/edit#gid=151768242). 

This should be a separate job in case a user chooses to not implement this part of the solution. This should be an optional add-on, also triggered by job `00`. 

## state.json
See LP for `WCS Test Mssql DB` (mssql) and `WCS ConSoSci DB` (postgres). 
You can use job 00 to trigger: https://www.openfn.org/projects/p5x4g4/jobs/jyd8gg
```
{
      uid: 'apZrpKcK78xzrPcAfRrfac',
      p1: 'WCSPROGRAMS',
      p2: 'Sharks',
      tableId: 'SharksRays',
  }
```

## adaptor
`mssql` AND `postgresql`

## expression.js
New job triggered by job `00`. 

## output.json
See green sheets for sample config + data.

**Comment by lakhassane** [comment]
@aleksa-krolls after reading through the sheet, here are the differents steps I think should be taken,
1. A new job that will build the form structure (similar to `01-processForm`). A new job because you said some might choose not to activate this so we cannot use `01` for this.
2. 1 new job that generate the tables from point 1 output
3. 1 new job that upsert the data in the 3 generated tables.

Now all of this can possibly be 1 big job that is independant from the automation, or 2 jobs still independant. Im building it as 2 jobs for now waiting to see if we can have it better.

**Comment by lakhassane** [comment]
@aleksa-krolls so finally only one job per database (postgresql, mssql) is enough (a total of 2 jobs for the whole flow).

This small change in `01-processForm` ensures we always keep the form definition. Then it can triggers `dataDictionary/02a-syncToProgres` if needed. 
https://github.com/OpenFn/ConSoSci/blob/master/automation/01-processForm.js#L2

**Comment by lakhassane** [comment]
Could you advise for the `uuid` for `kobo_choices`. I think if we add choice_name to list_id we can use that one for it (list_id: `${x.list_name}${formId}${x.name}`),

**Comment by aleksa-krolls** [comment]
@lakhassane great suggestion, let's do that! Whenever complete, let me know and will test... might also ask to jump on a call tomorrow to walk through it :)

**Comment by aleksa-krolls** [comment]
@lakhassane This fails when running on prod: https://www.openfn.org/projects/p5x4g4/runs/rn5jg87y

See run for A1 (job `00`) that triggered this failure to replicate: https://www.openfn.org/projects/p5x4g4/runs/rbgzrwep

Please run successfully on prod! @ritazagoni I configured this new job as job `AD` for now that is triggered by the same automation flow (see specs above for: https://www.openfn.org/projects/p5x4g4/jobs/jvebzq). When Mamadou has this working, can you review the DB output to validate how it looks in capturing the form definition metadata? Mamadou can and Stu help you VPN into the DB, if needed.

**Comment by lakhassane** [comment]
hey @aleksa-krolls so this issue is solved.
However, we might encounter another one about duplicates tuples we are inserting for `kobo_choices`.
Example:
This is how we build list_id ```list_id: `${x.list_name}${formId}${x.name}```. But in the form metadata we might have two question with the same `list_name` and `name` (it's the case for `list_id = gear `and `name = harpoon`) and the difference is in the country for those situations. Shall we also add `x.country` to how we bulk a unique id for `kobo_choices`?
Here are the two guys in question
```json
{
    "name": "harpoon",
    "$kuid": "9R9qbUt9A",
    "label": [
      "Harpoon",
      "Arpão",
      "Harpon",
      null,
      "Bunduki"
    ],
    "country": "mozambique",
    "list_name": "gear",
    "$autovalue": "harpoon"
  },
  {
    "name": "harpoon",
    "$kuid": "y8J3vdqpP",
    "label": [
      "Harpoon",
      "Arpão",
      "Harpon",
      null,
      null
    ],
    "country": "madagascar",
    "list_name": "gear",
    "$autovalue": "harpoon"
  },
```

**Comment by aleksa-krolls** [comment]
@lakhassane Using `country` sounds like a great suggestion... let's go with that, unless there is something similar to `$kuid` on the list-level? (I see this available for choices, so wondering if there is a similar id we can use.)

**Comment by lakhassane** [comment]
@aleksa-krolls using the kuid was a good idea. I dropped name from kobo_choices and replace with that one. 

So far working fine with that green check: https://openfn.org/projects/p5x4g4/runs/r6g45xdz

**Comment by aleksa-krolls** [comment]
@lakhassane I've tested by running this form: https://www.openfn.org/projects/p5x4g4/runs/rn5n656d

Overall looking good, except for some minor questions/feedback on the Dictionary tables: 
1. When we upsert 1 row in the `kobo_forms` table, I see that `languages` column is null... but there should be multiple. 
![Screen Shot 2021-07-08 at 1.23.55 PM.png](https://images.zenhubusercontent.com/5d691cd53295e300013f1cbd/41008079-2f19-4665-b72d-d806d0a6ee87)
![Screen Shot 2021-07-08 at 1.28.29 PM.png](https://images.zenhubusercontent.com/5d691cd53295e300013f1cbd/6ef07eb3-42c0-4f32-acd9-613cf0052460)

2. When reviewing the choice values uploaded to the `kobo_choices` table, it looks like the value for column `choice_label` is repeated multiple times (e.g., `Kililo,Kililo,Kililo,Kililo,Kililo` instead of just `Kililo`). Is there a reason for that? Is that maybe due to language settings in the form? 
![Screen Shot 2021-07-08 at 1.25.24 PM.png](https://images.zenhubusercontent.com/5d691cd53295e300013f1cbd/e07de419-377e-4416-b545-2392a7c2e16b)

3. The `kobo_questions` table seems to be missing several rows/ questions. When I check the form in Kobo, it says there are 221 questions (https://kf.kobotoolbox.org/#/forms/apZrpKcK78xzrPcAfRrfac/landing ) 
... but I only see 21 rows in the `kobo_question` table. 
![Screen Shot 2021-07-08 at 1.30.15 PM.png](https://images.zenhubusercontent.com/5d691cd53295e300013f1cbd/4f80e34e-25ea-4a41-bf03-b68f5b0e68fb)

**Comment by lakhassane** [comment]
@aleksa-krolls 
1. I was missing the correct path for `languages`. It's solved now.
2. is because of how it is written in the form. What would you advise (sometimes it is different values and not repeted values)? I think each value is supposed to be for one language translation
<img width="587" alt="Screen Shot 2021-07-08 at 12 36 59" src="https://user-images.githubusercontent.com/8411231/124922625-32f19800-dfe9-11eb-9c10-4d7135a0a860.png">

<img width="1077" alt="Screen Shot 2021-07-08 at 12 38 40" src="https://user-images.githubusercontent.com/8411231/124922849-6e8c6200-dfe9-11eb-9088-d08c93d9fba6.png">

3. Now this is weird because when I test I see `250` questions that should go in. I will re-run for that one and let you know

**Comment by aleksa-krolls** [comment]
@lakhassane walked WCS through this today. Here is the latest run: 

Some next steps: 
1. On `kobo_questions` table looks like we have 2 columns: `label_en` and `label_fr`... but only `label_en` is filled in and it has ALL of the languages added to this column. Can we therefore then just have 1 `label` column that has all of the translations listed? 
![Screen Shot 2021-08-31 at 6.33.28 PM.png](https://images.zenhubusercontent.com/5d691cd53295e300013f1cbd/993758df-736b-4998-a2b7-7c6b29088689)

2. Can you please go ahead and replicate for mssql? And when this job runs, make sure it prints the SQL script at the bottom so that WCS can review the sql output to provide feedback, as they've done with the rest of the automation solution. 

Keep me posted with questions, thanks!

**Comment by lakhassane** [comment]
@aleksa-krolls this was already done yesterday. I couldn't push due to internet issues.

I replicated on mssql and you can see the tables with the data in the opiant DB. I aslo use `label` as by the 1st point.

<img width="290" alt="Screen Shot 2021-09-01 at 10 23 04" src="https://user-images.githubusercontent.com/8411231/131655423-16b3b759-a7f9-4422-ab9e-f6fb1808d68c.png">

**Comment by aleksa-krolls** [comment]
Amazing @lakhassane!! For next steps, can you please..
1. Link the new mssql file to this job on prod, and make sure the adaptor version and sql `write` settings are correct (if needed): https://www.openfn.org/projects/p5x4g4/jobs/jv79zn
2. Then run this job `A1` which will trigger that job to run... to make sure it succeeds on prod: https://www.openfn.org/projects/p5x4g4/jobs/jyd8gg

I will then go and review the output and let you know if further feedback :-)

**Comment by lakhassane** [comment]
Done @aleksa-krolls see here:
https://www.openfn.org/projects/p5x4g4/runs?dateRange=custom&endDate=2021-09-01T10%3A53%3A10.587Z&jobId=&page=1&perPage=10&searchString=&startDate=2021-09-01T10%3A51%3A00.000Z&success=

**Comment by aleksa-krolls** [comment]
@lakhassane Looking food, just one change request so far... can we rename the Dictionary tables with this prefix `KoboToolBox_`? 
`KoboToolBox_Forms`, 
`KoboToolBox_Choices`, 
`KoboToolBox_Questions`

**Comment by lakhassane** [comment]
@aleksa-krolls tables renamed.
What is `KoboToolBox_`

**Comment by aleksa-krolls** [comment]
@lakhassane WCS is not ready to sync the automation solution directly to their main DB to auto execute changes there. For now, they want to pilot an approach where they run the automation solution, and then copy, edit, and manually execute the printed SQL in their DB. 

For the data dictionary, this run (https://www.openfn.org/projects/p5x4g4/runs/rbg4njaa) currently prints the SQL for the DB configuration of the Data Dictionary tables and columns. Ideally, they also want a SQL script that can be run **on-demand** to load rows of data into these DD tables, because they don't want to connect a job to their master DB that has the power to manipulate DB metadata. 

Potential options...
1. Is it possible to print the SQL output of the `upsert(...)` operations currently used in the job to upload the data values? And then WCS could run this script on demand whenever ready to load data into the DD tables. 
2. Otherwise I wonder if we can move all of these `upsert()` operations to a separate job that only has the purpose of syncing data (and does NOT modify the DB metadata)? If the job is _only_ syncing data and not modifying tables, then I think WCS would be comfortable connecting that job to the DB via OpenFn, and we could skip the manual step.

**Comment by aleksa-krolls** [comment]
@lakhassane As discussed...
1. After this current DD job finishes running, let's (1) post the form definition to the inbox with the tag `"Type": "Form Definition", and (2) set up a 2nd message filter job that will execute the `upsert(...)` operations to insert rows of data into the DD tables. For (2) - You can link to the job here to test: https://www.openfn.org/projects/p5x4g4/jobs/jyp5d9
2. Then (low priority) let's make a change to the `mssql` and `postgressql` adaptors that will allow users to specify in jobs whether they want to turn on/off logging data values so we can see what data is being upserted in destination tables. Ideally this setting should default to `off` unless specified otherwise.

**Comment by aleksa-krolls** [comment]
@lakhassane keep me posted with questions as you're working through this today. Happy to help test on prod whenever ready and new job is linked (see my last comment re: preconfigured job).

**Comment by lakhassane** [comment]
@aleksa-krolls I made the changes for `Mssql` and pushed on prod.
However before executing you need to change the credentials to `raw credential` so that we can add the `openfnInboxUrl`.
Here is the job you must change creds for: https://www.openfn.org/projects/p5x4g4/jobs/jv79zn

**Comment by aleksa-krolls** [comment]
@lakhassane I was able to successfully test the first DD job (https://www.openfn.org/projects/p5x4g4/runs/rg5xdb4z) that posts the form definition to the OpenFn Inbox....
...but now when I try to sync this form definition message with this job ( https://www.openfn.org/projects/p5x4g4/jobs/jyp5d9), it fails with the error `TypeError [Error]: Cannot read property 'name' of undefined`. See run failure: https://www.openfn.org/projects/p5x4g4/runs/r7x69bm6

Can you please take a look and make sure we can sync this state of the form definition? 
https://www.openfn.org/projects/p5x4g4/messages/mdb4wbdn

**Comment by lakhassane** [comment]
@aleksa-krolls here is the complete and correct message sent to the inbox: https://www.openfn.org/projects/p5x4g4/messages/mn5akbmr

I will run the update when the queue is free but it should trigger and run fine

**Comment by ritazagoni** [comment]
I ran the automation for testing and encountered 2 errors:
1. `AD. Sync Data Dictionary` error: https://www.openfn.org/projects/p5x4g4/runs/rn5p8dy6 `value too long for type character varying(100)`
2. `DD. Update Data Dictionary` job failed https://www.openfn.org/projects/p5x4g4/runs/r44gawr7
with a SQL  `RequestError: String or binary data would be truncated.` 
Related `AD. Sync Data Dictionary` run: https://www.openfn.org/projects/p5x4g4/runs/ryazbk4j

**Comment by lakhassane** [comment]
@ritazagoni both of these issues are related probably. We are inserting a column with a value longer than what is expected. Probably it's this one. From what I saw it's the column `constraint` that should expect 30 chars but had `218` instead
What would you advise here:
1. truncat to 100.
2. increase the column to more than 100 chars
cc @aleksa-krolls

**Comment by ritazagoni** [comment]
@aleksa-krolls should we ask Steve do decide?

**Comment by aleksa-krolls** [comment]
@lakhassane @ritazagoni `constraint` tells us what validation rules have been programmed into the Kobo forms... these can be long. Therefore, when we auto-generate the Data Dictionary tables, let's make sure the columns are longer. 

@lakhassane what are you using for default column lengths across the `Questions` and `Choices` tables? 
In addition to `constraints`, I think we can expect `labels` to be long data values if the form has multiple translations... therefore should we also have higher character limits for any `label` columns as well?

**Comment by lakhassane** [comment]
@aleksa-krolls I was using 100 chars as default but I can change both of them to `max` so we would be good

**Comment by lakhassane** [comment]
@ritazagoni I made the update

**Comment by ritazagoni** [comment]
@lakhassane we have the same error with the `AD. Sync Data Dictionary Postgres` job: https://www.openfn.org/projects/p5x4g4/runs/rg5m9ake ` value too long for type character varying(100)`

**Comment by aleksa-krolls** [comment]
@ritazagoni Looks like we needed to delete the DD tables in the test DB and then re-run so that the column configuration is updated to no longer have the 100 char limit. I've now synced all the BNS and NRGT forms successfully. Will ask WCS for further input. 

@lakhassane Looking pretty good! I'm inspecting the form definition uploaded to the DD tables in the `wcs test mssql db`.. and have some minor feedback on the data output generated via this `03b-updateDataDictionaryMssql.js` job (https://www.openfn.org/projects/p5x4g4/jobs/jyp5d9): 
1. On `KoboToolBox_Forms`, the column `table_id` is only showing `undefined_undefined_undefined` data values instead of the `tableId` defined in the first A1 job: https://www.openfn.org/projects/p5x4g4/jobs/jyd8gg
<img width="894" alt="Screen Shot 2021-09-14 at 10 13 36 PM" src="https://user-images.githubusercontent.com/16758106/133320039-30f14d35-2453-458e-8c6b-fb8be5c18911.png">

2. On `KoboToolBox_Questions`, can we please add column that shows the unique `list_id` value so we know exactly _which_ list in the table `KoboToolBox_Choices` each question links to? Currently we only have the column `select_from_list_name`
<img width="588" alt="Screen Shot 2021-09-14 at 10 21 57 PM" src="https://user-images.githubusercontent.com/16758106/133321021-b5594347-a78e-40b7-9db4-3f2173782726.png">

**Comment by lakhassane** [comment]
@aleksa-krolls I made the correction for point 1.

For point 2, it might be a little complicated. `list_id` in `KoboToolBox_Choices` are build using `${x.list_name}${formId}${x['$kuid']}` (`$kuid` being the specific kuid for that `list_name`). So we can have in `KB_Choices` the same list_name but different `kuid`.
<img width="459" alt="Screen Shot 2021-09-15 at 10 31 33" src="https://user-images.githubusercontent.com/8411231/133417794-bc23e093-fd9d-463a-959d-72e298bfb47b.png">

So, when we are in `KoboToolBox_Questions` we cannot have access to that $kuid for the `list_name` to build the same `list_id`.

Let me know if it's better to talk it through in engineering

**Comment by aleksa-krolls** [comment]
@lakhassane Looking pretty good now! Last question for the time being... I'm noticing that some (not all) of the `KoboToolBox_Forms.table_id` values still include `undefined`... any idea why that's the case? 
<img width="448" alt="Screen Shot 2021-09-15 at 2 44 54 PM" src="https://user-images.githubusercontent.com/16758106/133427614-aa6e47d0-6209-44ae-b96e-b049d221e9d5.png">

**Comment by aleksa-krolls** [comment]
@lakhassane re-ran and looking good now. You can go ahead and replicate for mssql... but this is lower priority, so moving this to the middle of the backlog.

**Comment by lakhassane** [comment]
@aleksa-krolls I replicated for postgres.

I don't know if it makes sens to have another job to udpdate data on postgres (because this one https://github.com/OpenFn/ConSoSci/blob/master/datadictionary/03b-updateDataDictionaryMssql.js) works for both DB (if you change the adaptor before running).

But in any case there is `updateDataDictionaryPostgres` available for you
