### ISSUE TITLE
Manual cursor not set after clearing job state 

### ISSUE THREAD

**Issue by ritazagoni** [OpenFn/ConSoSci#121]
## Describe the bug
After clearing job state, `Fetch Form Responses` doesn't fetch submission data submitted after manual cursor time. See run https://www.openfn.org/projects/p5x4g4/runs/rwa85g4b.

### expression.js
Link to the job itself in Github: https://github.com/OpenFn/ConSoSci/blob/master/automation/03-getKoboData.js

### state.json

Kobo: `openfn_kobo`
DB: `WCS ConSoSci`

## Expected behavior
After clearing job state, data submitted after manual cursor date are fetched. 

## To test/resolve
 Please test the change on OpenFn.org by re-running this related job (https://www.openfn.org/projects/p5x4g4/jobs/jv4b69) and confirming success... there should be submissions there to return.

**Comment by lakhassane** [comment]
@ritazagoni I have checked on the browser using this url (which should fetch submissions if they exist)
https://kf.kobotoolbox.org/api/v2/assets/REPLACE_UID/data/?format=json&query={"end":{"$gte":"REPLACE_WITH_MANUAL_CURSOR"}}
However it shows this.
<img width="449" alt="Screen Shot 2021-07-12 at 16 36 15" src="https://user-images.githubusercontent.com/8411231/125324266-48d7c380-e32f-11eb-8a12-df02de035c80.png">

 So I think it's because there is no submissions or they are not accessible.

**Comment by lakhassane** [comment]
ok this is up and running after using `_submission_time` for query filter

**Comment by aleksa-krolls** [comment]
@dianedetoeuf @ritazagoni We before used the Kobo `end` field to filter by date, but this form for some reason doesn't seem to have that in its JSON body, while we had assumed all forms did. We've switched to using `_submission_time` to filter by dates... can you please test out Mamadou's changes to verify this works now? Process is still the same... specify a date for `manualCursor`, clear state, and run the job!

**Comment by dianedetoeuf** [comment]
Hi, great it works! Now I need to figure out why the messages being fetched are not going into the auto/vegetation job... I've added "formType: vegetation" to that form in the job "Fetch form responses", but it doesn't seem to appear in the messages so the trigger for the vegetation job is not activated. Should I add the formType somewhere else?

**Comment by aleksa-krolls** [comment]
@dianedetoeuf @ritazagoni hmm... looks like `formType` wasn't being appended to the Messages created via this job. I just [made a change](https://github.com/OpenFn/ConSoSci/commit/c15fdc063dce740ccc58f5df982d440ae093123f#diff-dbf060365718967028cc34c734ca72cc8657e38fd707d603a8932ea4384797aa) that should fix that... want to try re-running now to confirm?
