### ISSUE TITLE
Add standard WCS fields & constraints to the automation solution

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/ConSoSci#125]
## Background, context, and business value
The automation solution will auto-generate DB tables in both Postgres and Mssql based on Kobo forms. The number of tables we create depend on the Kobo form... but ALL tables auto-generated need to include WCS standard columns and configuration settings to ensure they can more quickly use and report on the data. 

See the solution docs: https://openfn.github.io/ConSoSci/kobo-automation/

## The specific request, in as few words as possible
Please modify the SQL auto-generated by the automation solution to include: 

1. Standard columns that should be included on every table
2. Standard foreign key constraints

See this document for the db specifications from Steve. If you have any questions/clarifications, please leave comments in the doc and @ritazagoni can follow up with Steve via Skype to get those answers. 
https://docs.google.com/document/d/1AgFIkYzyCOxzigIdLR-LsUkZgnMuOA6EQQRSWsXaeig/edit

## state.json
See LP for `OpenFn Kobo`, `WCS ConSoSci DB (postgres)`, and `WCS Test Mssql DB`
You can use job 00 and the form Id currently there to trigger the flow `apZrpKcK78xzrPcAfRrfac`: https://www.openfn.org/projects/p5x4g4/jobs/jyd8gg

## adaptor
postgres AND mssql

## expression.js
Changes need to be made to the automation jobs to modify the SQL outputted by these 2 jobs: 
https://github.com/OpenFn/ConSoSci/blob/master/automation/02a-syncToPostgres.js
https://github.com/OpenFn/ConSoSci/blob/master/automation/02c-syncToMssql.js

## output.json
Every table should have these fields.

**Comment by taylordowns2000** [comment]
Breaking for lunch and some BD work this afternoon. Have pushed a concept on the `standard_columns_and_constraints` branch

**Comment by taylordowns2000** [comment]
Draft PR opened, outstanding questions needing answers before work continues: https://github.com/OpenFn/ConSoSci/pull/127/files

1. How do we map data to these new columns?
2. Which prefix is Steve referring to when he says `TablePrefix`

**Comment by aleksa-krolls** [comment]
@taylordowns2000 Feedback from the client...can you or Mamadou take this on today? @ritazagoni can then support with testing on prod when implemented. 

1. For standard fields, no need to map data to these new columns because they all have default values. Therefore these standard fields only need to be included in the auto-generated SQL (jobs `02a` and `02b`)... but NOT in the auto-generated OpenFn job (created via `02b`). 
2. `TablePrefix` is the auto-generated table names we create based on the `p1`, `p2` prefixes and `tableId` that are defined in job `00`. However, note that 1 Kobo form might trigger several tables to be generated... some for the main survey, some tables to capture repeated groups and related reference data. Therefore `TablePrefix` is relative to what table is being generated.... I'm sure @lakhassane can help explain (or maybe you want to assign this issue to him?)

```
p1_p2__tableId{ID}
p1_p2__tableId{Name}
p1_p2__tableId{Code}
p1_p2__tableId{Description}
```

**Comment by taylordowns2000** [comment]
@lakhassane , let's discuss this and my [PR](https://github.com/OpenFn/ConSoSci/pull/127) when you're done with itau 44.

**Comment by lakhassane** [comment]
@aleksa-krolls this is ready to go. However note Taylor comment about the missing default value for some fields.

**Comment by taylordowns2000** [comment]
@lakhassane , we also need to add in a section of "constraints" — see the second and third section of https://docs.google.com/document/d/1AgFIkYzyCOxzigIdLR-LsUkZgnMuOA6EQQRSWsXaeig/edit?ts=60fea075

**Comment by aleksa-krolls** [comment]
@lakhassane Is this done? I've been testing this morning, but wondering if there are more changes coming that I should plan time to test later.

**Comment by aleksa-krolls** [comment]
@lakhassane @taylordowns2000 I'm wondering if we _do_ need to map the default values of the [WCS standard fields](https://docs.google.com/document/d/1AgFIkYzyCOxzigIdLR-LsUkZgnMuOA6EQQRSWsXaeig/edit#) when we insert records into the DB. 

Check out this run failure when trying to sync [this message](https://www.openfn.org/projects/p5x4g4/messages/mbp3nq4p) to the test mssql DB: 
https://www.openfn.org/projects/p5x4g4/runs/ryapdr7g
```
RequestError: Cannot insert the value NULL into column 'WCSPROGRAMS__SharksRays_OrganizationID_Owner', table 'wcsprograms_opiant.dbo.WCSPROGRAMS__SharksRays'; column does not allow nulls. UPDATE fails.
```
I thought if there was a default value in the sql config, the column would save that default value as the row is being saved... but the DB seems to think we're inserting a `null` value into this `NOT NULL` column. 
```
[TablePrefix_OrganizationID_Owner] INT NOT NULL DEFAULT(1),
```
Have we misunderstood how default column values work? Should we map these standard fields in the auto-generated job (https://www.openfn.org/projects/p5x4g4/jobs/jy3kr6)?

**Comment by aleksa-krolls** [comment]
@lakhassane I see you have green checks for the output. Now I'm running the auto-generated job against a real Message ( https://www.openfn.org/projects/p5x4g4/messages/mbp3nq4p) and changing the adaptor and credentials on this job (https://www.openfn.org/projects/p5x4g4/jobs/jy3kr6) to test. I'm seeing...
1. postgres sync error: `error: column "answerid" of relation "wcsprograms__sharksrays" does not exist`
https://www.openfn.org/projects/p5x4g4/runs/rwa9rwzn
2. mssql sync error: `RequestError: Invalid column name 'GeneratedUuid'`
https://www.openfn.org/projects/p5x4g4/runs/rd76wb5a

**Comment by lakhassane** [comment]
Quick update on here.

It's all good minus the constraint part. I need few testing about the variables in this script before pushing to prod

**Comment by aleksa-krolls** [comment]
@lakhassane thanks for the update.Keep me posted on how I can help with testing or questions!

**Comment by lakhassane** [comment]
@aleksa-krolls quick question
In the google doc we have this
```sql
ALTER TABLE [dbo].[TablePrefix_TableName]  WITH CHECK ADD  CONSTRAINT [FK_TablePrefix_TableName_TablePrefix_SecuritySettingID_Row] FOREIGN KEY([TablePrefix_SecuritySettingID_Row])
REFERENCES [dbo].[TablePrefix_SecuritySetting] ([TablePrefix_SecuritySettingID])
GO
```

That should add constraint to let’s say a table like this => `WCSPROGRAMS_SharksRays_District_SecuritySetting`
However there is no table ending with `SecuritySetting`

It’s the same for `Organization`

**Comment by lakhassane** [comment]
@aleksa-krolls I added the scripts for foreign keys. 
However, I ignored the one at the section **`Constraints to add?`** (check Doc) because we already handled in the adaptor to add a `PRIMARY KEY` for any `identity` column.

https://github.com/OpenFn/language-mssql/blob/0efc250ddefbb82c4676bf0731cb571ba7d402fb/src/Adaptor.js#L714

**Comment by aleksa-krolls** [comment]
Okay cool. @lakhassane let me know on Slack when everything is pushed to prod so I can test? 

@taylordowns2000 can you review this `Constraints to add?` ([see here](https://docs.google.com/document/d/1AgFIkYzyCOxzigIdLR-LsUkZgnMuOA6EQQRSWsXaeig/edit#heading=h.japhusj120gc)) and confirm with Mamadou no other changes need to be made/ no follow up questions should go to Steve? I don't full understand what that constraint is... so it's hard for me to verify if we've satisfied Steve's requirement.

**Comment by lakhassane** [comment]
Feedback on this @aleksa-krolls.
Considering we should use the queries in the script to alter table, we drop the use of `identity` for the `standard columns` from WCS.
The use of identity was to directly make the adaptor specify any column that should be primary key.
This will not affect any other table but only the tables that are using the standard WCS fields.
The script with the `alters table` will do the job by running the raw sql provided.

Check this log to see the output for mssql https://openfn.org/projects/p5x4g4/runs/renrb8eb

**Comment by aleksa-krolls** [comment]
@lakhassane DB sql output looking good, but now...

I'm trying to load [this message](https://www.openfn.org/projects/p5x4g4/messages/m78n56jd) into the DB, and I'm encountering these run failure... could this be related to the identity and constraint changes made yesterday? 
cc @taylordowns2000 re: our `Constraints to add?` debate

1) mssql error: 
```
RequestError: Cannot insert the value NULL into column 'WCSPROGRAMS__SharksRaysID', table 'wcsprograms_opiant.dbo.WCSPROGRAMS__SharksRays'; column does not allow nulls. UPDATE fails.
```
https://www.openfn.org/projects/p5x4g4/runs/rpd6d4jb

2) postgres error: 
```
error: null value in column "wcsprograms__sharksraysid" violates not-null constraint
```
https://www.openfn.org/projects/p5x4g4/runs/rbgmgy7w

**Comment by aleksa-krolls** [comment]
Client asked us to ignore the `constraint to add?` for now and keep identity fields as-is. Now working in latest re-run: https://www.openfn.org/projects/p5x4g4/runs/r7xbxp4z

**Comment by aleksa-krolls** [comment]
@lakhassane Based on Skype chats, here is the feedback from WCS I think we need to implement... let me know if you want to discuss. Fyi, I'm referencing this SQL script output as an example: https://www.openfn.org/projects/p5x4g4/runs/r7xbxp4z

1. [Standard fields](https://docs.google.com/document/d/1AgFIkYzyCOxzigIdLR-LsUkZgnMuOA6EQQRSWsXaeig/edit) need to be included in ALL tables we auto-generate. Looks like these don't exist on some of the auto-generate reference and relationship tables for the `select` questions. 
2. ALL standard fields need to make sure the table prefix is included in the column name (`CountryID` vs. `WCSPROGRAMS__CountryID`). 

For example, this table auto-generated via `select` question includes the fields `ID`, `Name`, and `ExtCode`... but (1) other standard fields like `SecuritySettingID_Row` are missing, and (2) there is no table prefix (e.g., `TargetedID` vs. `WCSPROGRAMS__TargetedID`). 
```
Preparing to create table via: CREATE TABLE WCSPROGRAMS__Targeted (
        TargetedID int   PRIMARY KEY IDENTITY (1,1) , TargetedName varchar(100)    , TargetedExtCode varchar(100)  UNIQUE  , Payload nvarchar(max)    
      );
```
