### ISSUE TITLE
When `gps` field is received in Kobo, create `latitude` and `longitude` columns in DB

### ISSUE THREAD

**Issue by ritazagoni** [OpenFn/ConSoSci#126]
## Background, context, and business value

The automation solution will auto-generate DB tables in both Postgres and Mssql based on Kobo forms. See solution docs: https://openfn.github.io/ConSoSci/kobo-automation/

## Request
We need to make updates to always capture `latitude` and `longitude` in the connect DB. 
1. If a Kobo form includes a question with question `name:` `gps`, we want to also create 2 additional columns on the main table auto-generated via the automation solutions. These columns should be included in the auto-generated sql scripts of the `02a-syncToPostges` and `02c-syncToMssql` jobs.
- Columns to add:  `latitude` and `longitude`, `type: decimal`.
- For SharksAndRays, `latitude` and `longitude` would be configured on the main `SharksAndRays` table. Or in the diagram below, for the `SWMMarche2020` survey, these columns would belong on the main survey table `WCS_Marche_SWMMarche2020`. 
<img width="328" alt="Screen Shot 2021-07-21 at 9 42 02 AM" src="https://user-images.githubusercontent.com/16758106/126443660-866ce718-7e27-4d8e-bbec-e0708ed7acb2.png">

2. Add mappings to the auto-generated job created via `02b-syncToOpenFn.js`. 
When writing the Kobo submission data in these columns, we want to parse the `gps` field value and map it to `lat` and `lon`:  `latitude: ${gps}[0]`, `longitude:${gps}[1]`
So these default mappings should take `"gps":"0.439449 38.37319 0 0"` --> and return `latitude: 0.439449`, `longitude: 38.37319`

## state.json

See LP for `OpenFn Kobo, WCS ConSoSci DB` (postgres), and `WCS Test Mssql DB`
You can use job 00 and the form Id currently there to trigger the flow `apZrpKcK78xzrPcAfRrfac` 
Simply re-run this job to test the flow on prod: https://www.openfn.org/projects/p5x4g4/jobs/jyd8gg
You can inspect the DB and job output to validate. 

## adaptor

postgres AND mssql

## expression.js
Changes need to be made to the following automation jobs:
1. https://github.com/OpenFn/ConSoSci/blob/master/automation/01-processForm.js to create new columns in the sql scripts generated in the `02a-syncToProgres` and `02c-syncToMssql` jobs. 
2. https://github.com/OpenFn/ConSoSci/blob/master/automation/02b-syncToOpenFn.js to map the data to these columns.

**Comment by aleksa-krolls** [comment]
@ritazagoni Need your help on feedback below. Please update, assign to TD, and add to backlog. 
For 1. Confirming this is the right table where these new columns should live. (And not `KoboData`? Please adjust as needed)
For 2. In one you say the columns are `latitude` and `longitude`, but in 2 you say these are called `lat` and `lon`... please be consistent otherwise these mappings won't work.

**Comment by ritazagoni** [comment]
thanks @aleksa-krolls, 1. yes correct, these are the tables for the new columns. 2. edited

**Comment by ritazagoni** [comment]
@taylordowns2000 When ready to test just let me know, we'll test it on prod.

**Comment by taylordowns2000** [comment]
@ritazagoni , please see the [PR above](https://github.com/OpenFn/ConSoSci/pull/129) and review the code there. it's a very small change, but I think it's doing what you want. Have a look at the code and the questions on the PR, and then we're good to merge and test on prod.

**Comment by aleksa-krolls** [comment]
@ritazagoni does this look okay to you? If yes, will have Taylor merge this so that I can test... will plan to run a couple of tests to change all the other field type changes as well.

**Comment by ritazagoni** [comment]
hey @taylordowns2000 and @lakhassane  Ran a few tests, Postgres DB updates look good but ran into a `ReferenceError [Error]: col is not defined` error for Mssql, see run log https://www.openfn.org/projects/p5x4g4/runs/rg5gd958. Not sure which recent change is causing it.

**Comment by ritazagoni** [comment]
Solved, see https://www.openfn.org/projects/p5x4g4/runs/ryapdmzx
