### ISSUE TITLE
Automation: `select_multiple` Kobo questions should auto-generate tables to create m:m relationships

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/ConSoSci#131]
## Background, context, and business value
Follow up to issue #103... keep the logic for `select_one` as is. But for `select_multiple` Kobo questions, we want to generate tables that will automatically create many-to-many relationships between related tables. 

## The specific request, in as few words as possible
If Kobo question `select_multiple` type...
1. Modify the automated DB sql script output (jobs `02a` and `02b` for postgres and mssql), to (1) generate a parent reference table for this select question, (2) generate a junction table to capture the m:m relations, as well as (3) relationship columns to link this junction table with the main Kobo answer tables + the new reference table.

For example, if Kobo select_multiple question is `gear`...
1. OpenFn to create a reference table called `{p1}_{p2}_Gear` to capture the `select_multiple gear` values. This table should have the standard WCS columns ([see doc](https://docs.google.com/document/d/1AgFIkYzyCOxzigIdLR-LsUkZgnMuOA6EQQRSWsXaeig/edit#) - includes `GearID`, `GearName`, `GearExtCode`). Add this logic to the auto-generated sql to create a parent reference table for every select_multiple question. _(This logic might already have been implemented in issue #103)
2. Then, create a "junction" table called `{p1}_{p2}_{parentTableId}Gear` that will have foreign keys to relate to the parent tables. 
On this junction table create 2 foreign keys: 
- `{p1}_{p2}__GearID` that looks up to the reference table `{p1}_{p2}_Gear`
- `{p1}_{p2}__{tableID}` that looks up to the parent survey table `{p1}_{p2}_{parentTableId}`
Columns to create...
```
table: WCS_Programs__SharksGear, //{p1}_{p2}_{tableId}{koboQuestion}, 
primary key `INT IDENTITY(1,1)`: WCS_Programs__SharksGearID, //{p1}_{p2}_{tableId}{koboQuestionName} + 'ID'
fk1: WCS_Programs__GearID, //`{p1}_{p2}_{koboQuestionName}`
fk2: WCS_Programs__SharksID, //`{p1}_{p2}_{pa![WCS Automated Kobo __ Postgres data flow v2 - m_m (1).png](https://images.zenhubusercontent.com/5d691cd53295e300013f1cbd/72f3fec5-ae16-4adb-8fde-6d31c02c345a)rentTableId}`
```
![WCS Automated Kobo __ Postgres data flow v2 - m_m (1).png](https://images.zenhubusercontent.com/5d691cd53295e300013f1cbd/3c25abfd-3a01-4926-9467-0bdd254c21ce)

## state.json
See LP for `OpenFn Kobo`, `WCS ConSoSci DB (postgres)`, and `WCS Test Mssql DB`

### To test
1. You can use job 00 and the form Id currently there to trigger the flow `apZrpKcK78xzrPcAfRrfac`: https://www.openfn.org/projects/p5x4g4/jobs/jyd8gg
2. If we get green checks on the sql and job auto-creation, we can then run the auto-generated job against this Message to confirm successful data sync: https://www.openfn.org/projects/p5x4g4/messages/mbp3nq4p

## adaptor
postgres AND mssql

## expression.js
Changes need to be made to the automation jobs to modify the SQL outputted by these 2 jobs: 
https://github.com/OpenFn/ConSoSci/blob/master/automation/02a-syncToPostgres.js
https://github.com/OpenFn/ConSoSci/blob/master/automation/02c-syncToMssql.js

## output.json
There are a couple of `select_multiple gear` questions in this Kobo form

**Comment by lakhassane** [comment]
@aleksa-krolls I ran some tests.
In the provided form, we have 2 select_mulitples questions.

They are created as tables but also here are the junctions tables
<img width="427" alt="Screen Shot 2021-07-28 at 18 31 26" src="https://user-images.githubusercontent.com/8411231/127376856-714810b4-61d2-49c7-927c-95b5270947a0.png">

For now both the columns in those tables are `int` let me know if they should be something else.
<img width="686" alt="Screen Shot 2021-07-28 at 18 31 53" src="https://user-images.githubusercontent.com/8411231/127376918-64b5020c-0428-404c-a649-7aab57e24fea.png">

This is the test for `postgresql`. `mssql` should not be different and the changes are actually in `processForm` since that's where we build the tables to be created.

**Comment by lakhassane** [comment]
By the way, I saw an invisible bug that we had and never realized. We had a lot of `select_one` questions that weren't created as tables for a reason. I corrected that and now we see a lot more tables than before that are all select_one questions in the form.

<img width="383" alt="Screen Shot 2021-07-28 at 18 34 07" src="https://user-images.githubusercontent.com/8411231/127377214-21d97376-6705-4f89-a440-5baf6bc3dedc.png">

**Comment by aleksa-krolls** [comment]
@lakhassane Great catch on the bug :D
At a glance, looking good... but will validate when able to test. See my comment on #125.

**Comment by aleksa-krolls** [comment]
@lakhassane I'm inspecting the data I was able to successfully upload, and I'm not sure the foreign key columns are populating correctly on any child tables that have relationships with other parent tables. 
See my auto-generated job: https://www.openfn.org/projects/p5x4g4/jobs/jy3kr6
(It was produced by this run: https://www.openfn.org/projects/p5x4g4/runs/rn5m53k8)

For example, see this Message (https://www.openfn.org/projects/p5x4g4/messages/m78n56jd )where there are `select_one` questions like `Survey` and `Country`. 
These should be foreign key columns on the main survey table `WCSPROGRAMS__SharksRays` that look up to the reference tables `WCSPROGRAMS__Survey` and `WCSPROGRAMS__Country`. 

However, although the data is in the Message state... it doesn't look like these fk columns are being populated when the data is loaded into the DB: 
![Screen Shot 2021-07-29 at 5.17.05 PM.png](https://images.zenhubusercontent.com/5d691cd53295e300013f1cbd/36e72cf2-a2ee-4e8c-b0c7-faf6375b3728)

The parent reference records are there... just the FK relationship is not being filled in on the survey table. 
![Screen Shot 2021-07-29 at 5.19.48 PM.png](https://images.zenhubusercontent.com/5d691cd53295e300013f1cbd/ddba20e0-9bf1-4e24-8db3-dccf4ac50aa8)

**Comment by lakhassane** [comment]
@aleksa-krolls are you able to retry to give more feedbacks. 
I just try running the same job with the same message and got it in the database.
<img width="589" alt="Screen Shot 2021-07-29 at 16 11 25" src="https://user-images.githubusercontent.com/8411231/127527279-94bda0ad-d4d8-48c2-9e7f-c60e749b4246.png">
