### ISSUE TITLE
Update auto-generate job mappings to the `select` tables

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/ConSoSci#133]
## Background, context, and business value

Related to #125 and #131 

## The specific request, in as few words as possible

In the auto-generated job created via job `02b`... make sure all the mappings to the `select` tables are correct. We now made sure these select tables' columns include the prefix in the column name (e.g., `WCSPROGRAMS__CountryID` vs. `CountryID`) so need make sure the data will sync to these accordingly. 

## state.json
see LP for `test wcs mssql`
Here is state you can load into the db auto-generated: https://www.openfn.org/projects/p5x4g4/messages/me65gvwk

## expression
https://github.com/OpenFn/ConSoSci/blob/master/automation/02b-syncToOpenFn.js

**Comment by aleksa-krolls** [comment]
@lakhassane fyi, when I'm testing now... the mssql script is generating ok so far... but the job to auto-create openfn jobs immediately fails: https://www.openfn.org/projects/p5x4g4/runs/rrk8nmr4
<img width="1038" alt="Screen Shot 2021-07-30 at 3 26 57 PM" src="https://user-images.githubusercontent.com/16758106/127652850-d8806454-ab72-43a5-bf86-71a59b08493f.png">

**Comment by lakhassane** [comment]
Corrections made for this issue.
Check slack thread for more context: https://openfn.slack.com/archives/G2LJCFFDW/p1627674454028500

**Comment by aleksa-krolls** [comment]
@lakhassane See my last Slack comment and let me know if you want to discuss.

**Comment by aleksa-krolls** [comment]
@lakhassane I'm not sure if everything is on prod? Seeing this weird error when trying to run the job for language-mssql: https://www.openfn.org/projects/p5x4g4/runs/rpd64erx

To test on prod...
Here is the related Message: https://www.openfn.org/projects/p5x4g4/messages/mbp3nq4p
Here is the auto-generated job: https://www.openfn.org/projects/p5x4g4/jobs/jy3kr6

**Comment by lakhassane** [comment]
@aleksa-krolls re-ran the failed message after changes on the adaptor.
green check here for the conversion error https://www.openfn.org/projects/p5x4g4/runs/renrgza6
