### ISSUE TITLE
Vegetation EU `Error converting data type varchar to numeric`

### ISSUE THREAD

**Issue by ritazagoni** [OpenFn/ConSoSci#134]
### Describe the bug

We have a failed [run](https://www.openfn.org/projects/p5x4g4/runs/rn5mapx3) on this [message](https://www.openfn.org/projects/p5x4g4/runs/rmkgbmxp)  with ``Error converting data type varchar to numeric` error.

### expression.js
Link to the job itself in Github: https://github.com/OpenFn/ConSoSci/blob/master/vegetation/VegetationClassficationAndTreeMeasurementForm.js

### adaptor
`mssql`

### state.json
Example: https://www.openfn.org/projects/p5x4g4/messages/mv7v4883
See LP `WCS Programs Database`

### To test/resolve
After the desired output is working locally (from the CLI), please push commits to master
Please test the change on OpenFn.org by re-running this run https://www.openfn.org/projects/p5x4g4/runs/rn5mapx3 and confirming success.

**Comment by aleksa-krolls** [comment]
@ritazagoni The logic before was incorrectly reversed `!isNaN(...)`... changed to `isNaN(...)` and now getting a new error: 
https://www.openfn.org/projects/p5x4g4/runs/rn5mapx3

**Comment by aleksa-krolls** [comment]
@ritazagoni going to assign back to you... the new error seems to indicate we're inserting the wrong datatype into a column. Can you pinpoint where? This will hint how we might need to change job transformations.

**Comment by ritazagoni** [comment]
In state: https://openfn.org/projects/p5x4g4/messages/mv7v4883 I'm seeing
`"bareground": "5",`, we're not doing any conversion in the job. The DB expect an `int`
`Bareground int NULL,`
See run https://openfn.org/projects/p5x4g4/runs/rn5mapx3

**Comment by ritazagoni** [comment]
edited issue description to reflect current error.

**Comment by lakhassane** [comment]
@ritazagoni for this one and potentially the other issues where we have this error, you need to use `v2.6.0` for `mssql`.
and also set options in your operation as this: 
```js
...
 return upsert('TABLE', 'GeneratedUuid', mapping, {setNull: ["''", "'undefined'"})(state); 
```

The novelty here is using setNull so that any value that is empty of undefined will be set to `Null`

**Comment by aleksa-krolls** [comment]
@lakhassane I thought I implemented this correctly on the Vegetation job ([see L429](https://github.com/OpenFn/ConSoSci/blob/master/vegetation/VegetationClassficationAndTreeMeasurementForm.js#L429)), but it still fails with the error `RequestError: Error converting data type varchar to numeric`. 

Can you please check it out and let me know if I'm doing something wrong?

**Comment by lakhassane** [comment]
@aleksa-krolls in this one there was a misuse of `isNaN`

The condition was written as this
```js
 Latitude: isNaN(latlong.latitude)
      ?  latlong.latitude
      : dataValue("$.body.plot_gps")(state).split(" ")[0]
```
but it should be like this below. Because isNaN tests if latitude is not a number then we use plot_gps
```js
 Latitude: isNaN(latlong.latitude)
      ?  dataValue("$.body.plot_gps")(state).split(" ")[0]
      : latlong.latitude
```

It's solved here https://openfn.org/projects/p5x4g4/runs/ryagmm3e

**Comment by aleksa-krolls** [comment]
@lakhassane Thank you! 

@ritazagoni Realizing the other thing causing the split error what that we weren't checking if `plot_gps` was defined before splitting... we were only checking if lat/long were defined. 

@dianedetoeuf All Vegetation EU errors are now resolved except for this last one below that affects [5 messages](https://openfn.org/projects/p5x4g4/messages?dateRange=720&endDate=2021-08-04T09%3A47%3A20.210Z&jobStates=fail&page=1&perPage=10&searchString=&startDate=2021-07-05T09%3A47%3A17.090Z&triggerId=t9jxxe). 
```
RequestError: Cannot insert the value NULL into column 'WCSPROGRAMS_VegetationSoilColorID', table 'wcsprograms.dbo.WCSPROGRAMS_Vegetation'; column does not allow nulls. UPDATE fails.
```
https://openfn.org/projects/p5x4g4/runs/rmkgrrxk

**It looks like no soil value was provided for these... how do you want to handle this scenario? Is there an "unknown" soil we can map to as a default if no matching one is found or provided by Kobo?**
