### ISSUE TITLE
landscape returning no value in the DB

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/ConSoSci#135]
## Description
@dianedetoeuf has reported that `landscape` column in DB showing undefined value... `landscapeMap` mapping does not seem to be mapping properly. 

## expression
https://github.com/OpenFn/ConSoSci/blob/c1edef53d804b0d22e5774b1d32dbf232a6ab16c/bns/survey.js#L137-L141

## state
Feel free to re-run on prod: https://www.openfn.org/projects/p5x4g4/messages/mv7vm3e3
See LP for `wcsprograms db`

**Comment by aleksa-krolls** [comment]
@taylordowns2000 Mamadou is focused on the other wcs issue... can you please check this one out sometime today and let me and @dianedetoeuf know how you resolved for our learning?

**Comment by aleksa-krolls** [comment]
@taylordowns2000 can you provide some quick troubleshooting help sometime today? cc @ritazagoni

**Comment by aleksa-krolls** [comment]
@taylordowns2000 see here for the original requirement: https://github.com/OpenFn/ConSoSci/issues/95

`landscape` is linked to the Site where data was collected. Based on the Site defined in the `formName`, we want to return a corresponding default value for `landscape`. If no matching `landscape` can be found... then return `''`.

**Comment by dianedetoeuf** [comment]
Hi, as discussed in our meeting, for Prices we need to use the form name to map as the landscape field is not always in the forms, however on the BNS survey job there is always a landscape value so it might be easier to use that value and map as follow: 
    tns: 'ndoki',
    'ltlt': 'lac_tele',
    mtkb: 'kahuzi',
    crossriver: 'crossriver',
    mamabay: 'makira'
The other landscape names don't need to be changed.

**Comment by aleksa-krolls** [comment]
Thanks @dianedetoeuf. So @taylordowns2000 this means...
1. **BNS price** --> we want to use `formName` to inform how `landscape` is set (re: issue #95 ). Sounds like it's still worthwile re-writing this to return `''` if a `landscape` name matching the `formName` is not found (as discussed).
 
2. **BNS Survey** --> this is more of a typical mapping table requirement. Check if Kobo value is in `landscapeMap`... if yes, return value for matching key. If no, return empty string `''`. (No need to check `formName - change from our discussion.)
```
landscapeMap: {
tns: 'ndoki',
'ltlt': 'lac_tele',
mtkb: 'kahuzi',
crossriver: 'crossriver',
mamabay: 'makira'
}
```

**Comment by dianedetoeuf** [comment]
Exactly! And for BNS price keep the name matching as it is currently mapped in the price job. Hope this is not too confusing :)

**Comment by taylordowns2000** [comment]
@aleksa-krolls and @dianedetoeuf , I've left `bns/price.js` how it is... that logic looks good.

For a normal mapping, there are two things you need to do:

1. add a mapping object (`landscapeMap`, in this case) to state. here, the issue is that it was added as a constant inside a custom code block, but never added to state so not available to subsequent operations. see https://github.com/OpenFn/ConSoSci/commit/25b891710cb64077e1aaf3f875ad7c7a833d4a54
2. select a value from that mapping object _by its key_, like this: `state => state.mappingObject[state.data.formName]`. see https://github.com/OpenFn/ConSoSci/commit/b35f16c5d7dc0a6dd79306af4bdbc0e52246d845

here's the run: https://www.openfn.org/projects/p5x4g4/runs/r7xbda96

**Comment by aleksa-krolls** [comment]
@dianedetoeuf do you want to verify the output in the DB for this run? Comment @ taylordowns2000 if any questions on the above. https://www.openfn.org/projects/p5x4g4/runs/r7xbda96

Then, if everything looks good... is it okay if you wait until end of day to re-process the BNS surveys? (We're actively testing some of the other issues, so it would be great not to fill up the runs queue with BNS runs to allow for this quicker testing. Thanks!)

**Comment by dianedetoeuf** [comment]
Oh no sorry I’m just seeing this!!

How do I kill the ongoing runs? :)

Diane
