### ISSUE TITLE
Estimation for test harness for automation solution

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/ConSoSci#136]
To allow us to test offline. Search project for the `AUTO` jobs to see what's relevant. 
https://www.openfn.org/projects/p5x4g4/jobs

## Taylor's initial spec here:
https://docs.google.com/document/d/1vMP0WWhcO4cecHsex0aDWlJYh4xRYi9Lz0HJRZUCwC8/edit#

**Comment by aleksa-krolls** [comment]
@taylordowns2000 @stuartc What's the latest here? Is there more of a concrete estimate/ pitch I can share back to WCS this week?

**Comment by taylordowns2000** [comment]
hey @aleksa-krolls , sorry for the delay here. 3-4 days of WCS-specific work is our best estimate. There may be a bit more, beyond that, rounding out to about a week, but OpenFn could invest that chunk as it would be re-usable, if WCS could raise money for the ~3.5d.
