### ISSUE TITLE
Automation solution - repeat group table adjustments 

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/ConSoSci#139]
## Background, context, and business value
The client is reviewing the auto-generated SQL script and OpenFn job for the Sharks & Rays form and has provided the following feedback. 
- MSSQL: https://www.openfn.org/projects/p5x4g4/runs/r6g8nb36
- Job: https://www.openfn.org/projects/p5x4g4/jobs/jy3kr6
https://github.com/OpenFn/ConSoSci/blob/master/sharks_rays/autoSharksRays.js

## The specific request, in as few words as possible
Feedback...
1. Remove all underscores `_` between the parent table and repeat group name. Example: `WCSPROGRAMS_SharksRays_Boat` --> `WCSPROGRAMS_SharksRaysBoat`
2. Definition of FK's in detail tables for repeat groups is missing. 
For example with `WCSPROGRAMS__SharksRaysBoat` we have...
- `WCSPROGRAMS_SharksRaysBoat.WCSPROGRAMS_SharksRaysID` int (the FK field from the child table to the parent PK)
- The FK definition that is missing: 
```
ALTER TABLE [dbo].[WCSPROGRAMS_SharksRaysBoat]  WITH CHECK ADD  CONSTRAINT [FK_WCSPROGRAMS_SharksRaysBoat_WCSPROGRAMS_SharksRaysID] FOREIGN KEY([WCSPROGRAMS_SharksRaysID])
REFERENCES [dbo].[WCSPROGRAMS_SharksRays] ([WCSPROGRAMS_SharksRaysID])
GO
ALTER TABLE [dbo].[WCSPROGRAMS_SharksRaysBoat] CHECK CONSTRAINT [FK_WCSPROGRAMS_SharksRaysBoat_WCSPROGRAMS_SharksRaysID]
GO
```

## state.json
Re-run job A1 with these form inputs to test for formid `apZrpKcK78xzrPcAfRrfac`: https://www.openfn.org/projects/p5x4g4/runs/r9w3jn74

Let me and @daissatou2 if you want help testing. 

## adaptor
Note that getting this right for `mssql` is priority... but we'll need to have it working for Postgres as well. 

## expression.js
https://github.com/OpenFn/ConSoSci/tree/master/automation

**Comment by aleksa-krolls** [comment]
@lakhassane For point 2, I think WCS wants to not only rely on the AnswerId and generated uuids to link the repeat group tables. Therefore...
- Every time we create a repeat group table, there should be a `ID` column that is configured as the FK to the parent table. 
- This column should be an `int` with a FK constraint. 
- The naming convention should be `{parentTableName}ID`. 

For example, if we have the repeat group `boat`... then on the table `WCSPROGRAMS__SharksRaysBoat` there should be the columns: 
- `WCSPROGRAMS__SharksRaysBoatID` (pk that already exists)
- `WCSPROGRAMS__SharksRaysID` (FK TO CONFIGURE - that links to parent table `WCSPROGRAMS__SharksRays`)
<img width="692" alt="Screen Shot 2021-08-10 at 7 48 31 PM" src="https://user-images.githubusercontent.com/16758106/128900857-c111e018-5b03-4a87-ae38-58a8fa68dc53.png">

Let me know if that makes sense or if you want to talk this through?

**Comment by lakhassane** [comment]
@aleksa-krolls @daissatou2 this is done and ready.
if you check the DB in table (e.g `WCSPROGRAMS_SharksRaysSales`) you will have the new foreign key created as well as the column `WCSPROGRAMS_SharksRaysID`
