### ISSUE TITLE
Automation: FK definitions for `select` reference tables missing

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/ConSoSci#140]
## Describe the bug
Follow up to issues #131  and point 2 in #139. The client is saying that FK definitions are also missing in the lookup reference tables auto-generated from Kobo `select` questions. 

For example, the m:m table `WCSPROGRAMS__SharksRaysSGearType `is created by not referenced in FK definitions. 
- MSSQL script: https://www.openfn.org/projects/p5x4g4/runs/r6g8nb36
- Auto Job: https://www.openfn.org/projects/p5x4g4/jobs/jy3kr6
https://github.com/OpenFn/ConSoSci/blob/master/sharks_rays/autoSharksRays.js

## state.json
Re-run job A1 with these form inputs to test for formid `apZrpKcK78xzrPcAfRrfac`: https://www.openfn.org/projects/p5x4g4/runs/r9w3jn74

Let me and @daissatou2 know if you want help testing. 

## adaptor
Note that getting this right for `mssql` is priority... but we'll need to have it working for Postgres as well. 

## expression.js
https://github.com/OpenFn/ConSoSci/tree/master/automation

**Comment by lakhassane** [comment]
@aleksa-krolls finally there. I made the change. So additionally to what we did in #139 we will also have FKs in the m:m relationships (junction tables). So you might see 2 new FKs one for the master table and another one linking the select_multiple table.

<img width="540" alt="Screen Shot 2021-08-11 at 18 00 22" src="https://user-images.githubusercontent.com/8411231/129080088-c0b15fb8-41a6-4c57-8252-c8cb424c1125.png">

**Comment by aleksa-krolls** [comment]
@lakhassane These FKs are looking good when I'm reviewing the DB output in the test mssql DB... but I don't see any reference to these `FK`s in the SQL script generated in the run log: https://www.openfn.org/projects/p5x4g4/runs/r8974db6
See after L778 `Logging queries` - there is no mention of these FKs in this SQL script. WCS will probably be manually running the sql script rather than auto-executing in mssql so we need to make sure these output includes everything.

**Comment by lakhassane** [comment]
change made here. Just noting that for `sql()` now you have to add the options if you want to log the queries.

```js
sql({
    query: state => `query String...`,
    options: {
        writeSql: true, // Keep to true to log query (otherwise make it false).
        execute: true, // keep to false to not alter DB
     },
})
```

Im adding this to the readme

**Comment by aleksa-krolls** [comment]
@lakhassane it doesn't look like the FK definitions exist for `select_one` questions between the main survey tables and the lookup tables. 

See MSSQL script: https://www.openfn.org/projects/p5x4g4/runs/r5e8dnyw
See ERD diagram the client made of the config to be generated... no direct relationships between these tables and the lookup ones? 
![sharks and rays tables](https://user-images.githubusercontent.com/16758106/130731898-97eb55c4-5e6a-47ea-97c1-69fa2ee9658e.png)

For example, the main table `WCSPROGRAMS_SharksRays` has columns for the select_one questions `Country`, `Survey`, `Surveyor`, `Market`, etc. ... but I don't see any FKs linking this table to the related lookup tables. 
<img width="674" alt="Screen Shot 2021-08-25 at 8 28 33 AM" src="https://user-images.githubusercontent.com/16758106/130731886-40bc4d81-9aa7-4346-afa1-36197bc298e9.png">

**Comment by lakhassane** [comment]
@aleksa-krolls I corrected this to allow FK for select_one columns.

One impact is also select_one questions that were created as `nvarchar` in the main will now be `int` to reference the PK in `lookupTables`.
<img width="982" alt="Screen Shot 2021-08-25 at 15 29 39" src="https://user-images.githubusercontent.com/8411231/130819829-a571d715-42cc-46d7-bcd9-3740e6d521fa.png">

**Comment by aleksa-krolls** [comment]
@lakhassane The changes sound good. I've tried to test, but two things have come up...
1. Failing on prod with error `RequestError: Could not create constraint or index. See previous errors.`
https://www.openfn.org/projects/p5x4g4/runs/r9w8en65

2. Before testing on prod, I was reviewing the config in the test DB and I noticed that a `select_one` column on a repeat group table `WCSPROGRAMS_SharksRaysVendor.vendorsex` looked like it was still configured as nvarchar rather than an int column with a FK to the lookup table. This might have been old config I was reviewing, but 
I want to confirm this recent change has been applied to all survey repeat group tables (e.g., `WCSPROGRAMS_SharksRaysVendor`, `SharksRaysBoat`, etc.) as well as the main table `WCSPROGRAMS_SharksRays`? 
Thanks and keep me posted on how I can help with testing!

**Comment by lakhassane** [comment]
@aleksa-krolls Im back on this to have a look.

This error might happen because the tables were not created in order. Is it possible to go on a fresh test. Can you delete all the tables related to this form so I can re-run on local and test. I might have problem knowing exactly what those tables are

**Comment by aleksa-krolls** [comment]
@lakhassane Is there still work on this? You moved to `backlog`?

**Comment by lakhassane** [comment]
@aleksa-krolls probably a mistake. But it was fully done

**Comment by aleksa-krolls** [comment]
@lakhassane WCS is reviewing the latest version of the auto-generated SQL script: https://www.openfn.org/projects/p5x4g4/runs/rbg47p46

When I tested this I thought the DB output looked okay (I was seeing the relationships between the main tables and the select lookup tables... but maybe I didn't check all of them or maybe the definitions are just not right in the printed script....but not totally sure what I should be looking for in the script.) Can you help? See the below ERD they've created by running the SQL script from the link above... maybe we're auto-creating the FK definitions but not including them in the printed sql script?

They're reporting: "For the S&R setup, We still don't see relationships for 24 of the 42 tables that would be created by the script."
![image.png](https://images.zenhubusercontent.com/5d691cd53295e300013f1cbd/0f86d595-d846-412b-8dfd-55ca96ce367c)
I think `wcsprograms_secondarygear` is an example table to look at. 

**Today - can you please spend time to determine the issue? (No need to resolve today).** Once you see something wrong in the script or if you're not sure what they're talking about, please let me know and we can jump on a call to discuss next steps before starting any work? I want to make sure I understand what's going on and the level of effort to fix, so that I can help prioritize across other items in backlog... thanks!

**Comment by aleksa-krolls** [comment]
@lakhassane It looks like we're mapping to the "select" lookup table fine from the main `WCSPROGRAMS_SharksRays` table. See FK definitions correctly configured...yay! But...
<img width="704" alt="Screen Shot 2021-09-03 at 1 06 36 PM" src="https://user-images.githubusercontent.com/16758106/131989098-36ef82c0-b081-442d-9202-1c57249eb613.png">

However, on the child survey tables for repeat groups (e.g., `WCSPROGRAMS_SharksRaysBoat`), the FK definitions to the select loop up tables are missing...
<img width="770" alt="Screen Shot 2021-09-03 at 1 06 48 PM" src="https://user-images.githubusercontent.com/16758106/131989084-12b27a97-20db-4313-aa41-953777b71d17.png">

For example, `secondarygear` is a Kobo select_one question. It's corresponding column `WCSPROGRAMS_SharksRaysBoat.SecondaryGear` should have a FK to the lookup table `WCSPROGRAMS_SecondaryGear`. 
<img width="620" alt="Screen Shot 2021-09-03 at 1 06 59 PM" src="https://user-images.githubusercontent.com/16758106/131989075-d8d8c359-548f-4178-8a9f-d29e4a4eeac9.png">

**Comment by lakhassane** [comment]
@aleksa-krolls I pushed the fix as discussed

**Comment by aleksa-krolls** [comment]
@lakhassane SharksRays mssql job is failing on prod with error `Could not create constraint or index. See previous errors.` ... so unable to validate your changes. 
https://www.openfn.org/projects/p5x4g4/runs/r44gra8z
Can you please...
1. Correct the issue
2. Clear state & run this job on prod to make sure all green checks: https://www.openfn.org/projects/p5x4g4/jobs/jyd8gg
I can then check out the DB output later tonight/this weekend.

**Comment by lakhassane** [comment]
@aleksa-krolls issue is fixed.

I added for you in `processForm.js` a log that prints a query to delete all the tables. 
<img width="1426" alt="Screen Shot 2021-09-06 at 12 13 42" src="https://user-images.githubusercontent.com/8411231/132215913-8105c15c-8f73-4fdd-a49f-b8e4cef25e08.png">

see run here: https://www.openfn.org/projects/p5x4g4/runs/rzdg8zr4

**Comment by aleksa-krolls** [comment]
@lakhassane A couple of new change requests based on the latest S&R script (https://www.openfn.org/projects/p5x4g4/runs/rzdg8zr4): 

1. Only if `select` questions in Kobo forms are required (`required: true` in form definition), then in the corresponding column needs to be set as `not null: true`
- E.g., The question `select_one survey_type` is required in the Kobo form. Therefore for `FK_WCSPROGRAMS_SharksRays_SurveyType`... this FK column should be set as not null. 
<img width="613" alt="Screen Shot 2021-09-10 at 7 44 41 AM" src="https://user-images.githubusercontent.com/16758106/132800976-9bca923f-ca87-40a3-9fa4-453a9809ae5c.png">

2. For select question FK columns that look up to other lookup tables (e.g., `Market`, `Survey`, `SurveyType` on `WCSPROGRAMS_SharksRays` table), the client ideally wants these FK columns to be named the same as the parent table's corresponding PK. 
For example, currently we have a `Market` column...
`FK_WCSPROGRAMS_SharksRays_Market`
Ideally this would instead be named as `WCSPROGRAMS_MarketID` (same as the PK column name on the parent lookup table `WCSPROGRAMS_Market`)...
`FK_WCSPROGRAMS_SharksRays_WCSPROGRAMS_MarketID`

Another example: `WCSPROGRAMS_SharksRays.SurveyType` --> `WCSPROGRAMS_SharksRays.WCSPROGRAMS_SurveyTypeID` with 
`FK_WCSPROGRAMS_SharksRays_WCSPROGRAMS_SurveyTypeID`

**Comment by lakhassane** [comment]
@aleksa-krolls I made both changes.

For point 2, it needed a bunch of rework also on `syncToOpenfn` to add `findValue` for those foreign keys.

Could you review this generated job and tell me what you think: https://gist.github.com/lakhassane/fcf6e2f7a49b079b6538ec7338067137

**Comment by aleksa-krolls** [comment]
@lakhassane Eish! Nicely done, the auto-generate job is looking good... only one quick question re: the mappings: 
```
alterState(async (state) => {
  const mapping = {
    Verification: dataValue("verification"),
    Consent: dataValue("consent"),
```
**Don't we have to append `(state) to the end, every time we reference `dataValue()` within an alterState block?** For example: 
```
alterState(async (state) => {
  const mapping = {
    Verification: dataValue("verification")(state),
    Consent: dataValue("consent")(state),
```
**Lastly, can I test end-to-end on prod now? Have you cleared the tables from the test mssql DB>**

**Comment by lakhassane** [comment]
@aleksa-krolls 

1. no not needed unless we are doing some manipulations before assigning it will be done in the adaptor
2. Let me clear the db but yes you can test. Also I append a log with a DROP TABLE in processForm that you can use for that matter.
