### ISSUE TITLE
Automation: Ensure no double underscore `_` in table names

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/ConSoSci#141]
## Background, context, and business value
Follow up to issue #62. WCS wants to make sure all table names always follow the naming convention `{prefix}_{tableName}` (only 1 underscore)... _unless_ there are 2 prefixes: `{p1}_{p2}_{tableName}` (but even this will only have 1 `_` between prefixes and never `__`). 

## The specific request, in as few words as possible
Currently if a user enters the following for job A1... this outputs tables with 2 underscores `WCSPROGRAMS__SharksRays`.
```
{
  formId: 'apZrpKcK78xzrPcAfRrfac',
  tag: 'Sharks & Rays TEST FORM 11 june',
  url: 'https://kf.kobotoolbox.org/api/v2/assets/apZrpKcK78xzrPcAfRrfac/?format=json',
  prefix1: 'WCSPROGRAMS',
  prefix2: '',
  tableId: 'SharksRays',
  lastModified: '2021-07-23T09:23:00.386611Z'
}
```
If there is only 1 prefix defined, then please return only 1 underscore... so table names should look like `WCSPROGRAMS_SharksRays`, `WCSPROGRAMS_SharksRaysBoats`, etc. 

## state.json
Re-run job A1 with these form inputs to test for formid `apZrpKcK78xzrPcAfRrfac`: https://www.openfn.org/projects/p5x4g4/runs/r9w3jn74

Let me and @daissatou2 if you want help testing. 

## adaptor
Note that getting this right for `mssql` is priority... but we'll need to have it working for Postgres as well. 

## expression.js
https://github.com/OpenFn/ConSoSci/tree/master/automation

**Comment by lakhassane** [comment]
handle with commit #4c7aec5

**Comment by aleksa-krolls** [comment]
@lakhassane See my latest test.... `WCSPROGRAMS__KoboDataset` still has a double underscore. Please change to 1 `_`. 
https://www.openfn.org/projects/p5x4g4/runs/r8974db6

**Comment by lakhassane** [comment]
@aleksa-krolls I corrected this one

**Comment by aleksa-krolls** [comment]
@lakhassane Looks like the auto-generated job still needs to be updated to ensure no tables include double underscores. 
For example, see `WCSPROGRAMS__Country` in the auto job: https://www.openfn.org/projects/p5x4g4/jobs/jy3kr6

See run failure + sample data to test against: https://www.openfn.org/projects/p5x4g4/runs/rg56ypj7

**Comment by lakhassane** [comment]
Check slack thread for feedback https://openfn.slack.com/archives/G2LJCFFDW/p1629276327000300?thread_ts=1629232368.032300&cid=G2LJCFFDW
