### ISSUE TITLE
Automation: Remove `Payload` column from all select lookup tables

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/ConSoSci#144]
## The specific request, in as few words as possible
Currently it looks like we're uploading the whole JSON payload to almost every auto-generated table. This `Payload` column really only needs to exist on the main survey table (i.e., `WCSPROGRAMS_SharksRays`). 

See latest auto-generated script: https://www.openfn.org/projects/p5x4g4/runs/rbg47p46
For example, see `WCSPROGRAMS_Country.Payload`... doesn't really make sense to have this column there. 

## state.json
Re-run job A1 with these form inputs to test for formid `apZrpKcK78xzrPcAfRrfac`: https://www.openfn.org/projects/p5x4g4/runs/r9w3jn74

## adaptor
Note that getting this right for `mssql` is priority... but we'll need to have it working for Postgres as well. 

## expression.js
https://github.com/OpenFn/ConSoSci/tree/master/automation

**Comment by lakhassane** [comment]
@aleksa-krolls I removed payload from the other tables.

**Comment by aleksa-krolls** [comment]
@lakhassane We correctly removed this `Payload` column from the SQL script, but not from the auto-generated job. Therefore, I'm now encountering this error when testing syncing data: https://www.openfn.org/projects/p5x4g4/runs/r89pay69
```
Executing upsert via : MERGE WCSPROGRAMS_Country AS [Target]
          USING (SELECT [--REDACTED--]) 
          ON [Target].[--VALUE--] = [Source].[--VALUE--]
          WHEN MATCHED THEN
            UPDATE SET [--REDACTED--] 
          WHEN NOT MATCHED THEN
            INSERT (Payload, WCSPROGRAMS_CountryExtCode, WCSPROGRAMS_CountryName) VALUES [--REDACTED--];
Invalid column name 'Payload'.```

Example auto-generated job: https://www.openfn.org/projects/p5x4g4/jobs/jyk5mw

**Comment by lakhassane** [comment]
@aleksa-krolls weird. Is it possible that this could be an old job? I see it was created `08/17` while I removed the payload `08/31`. I'm saying because actually the `syncToOpenfn` does not create column

**Comment by lakhassane** [comment]
@aleksa-krolls there were a small typo in how we update. it's corrected now and changes (payload removed from everywhere but main table) are reflected.
