### ISSUE TITLE
BNS: Use `geolocation` field if `lat` and `long` are not in state

### ISSUE THREAD

**Issue by ritazagoni** [OpenFn/ConSoSci#145]
## Background, context, and business value

In [[BNS-2B] BNS Survey](https://github.com/OpenFn/ConSoSci/blob/master/bns/survey.js) we are currently using the `gps/lat` and `gps/long` fields to [map to the DBs `lat` and `long` columns](https://github.com/OpenFn/ConSoSci/blob/37f59e1e6c3dd10e2411d89b3f36c06a76af3e9d/bns/survey.js#L242-L243).
These fields are not always available in `state`.

## The specific request, in as few words as possible
 
When `gps/lat` and `gps/long` fields are not available in `state`, use the `_geolocation` field to map these values.
For example:
`"_geolocation": [
      -15.376998,
      48.968732
    ],`

Mapping:
`lat: -15.376998,`
`long:  48.968732`

An example run: https://www.openfn.org/projects/p5x4g4/runs/r3xz36zn on message https://www.openfn.org/projects/p5x4g4/messages/mv7e3qe6.

## state.json
See LP `WCS Programs Database (central db)` for DB credentials.

## adaptor

`language-mssql`

## expression.js
Update the job: https://github.com/OpenFn/ConSoSci/blob/master/bns/survey.js

**Comment by aleksa-krolls** [comment]
@ritazagoni @dianedetoeuf moved to the backlog for Mamadou to look at

**Comment by lakhassane** [comment]
@ritazagoni I made the change to use _geolocation whenever needed.

<img width="247" alt="Screen Shot 2021-09-01 at 11 24 17" src="https://user-images.githubusercontent.com/8411231/131663166-0b5f8f4f-ded2-4968-8379-b32701d202c0.png">

**Comment by ritazagoni** [comment]
thanks @lakhassane!

**Comment by dianedetoeuf** [comment]
Thank you!!
