### ISSUE TITLE
Landscape update for NRGT jobs

### ISSUE THREAD

**Issue by dianedetoeuf** [OpenFn/ConSoSci#146]
## Describe the bug
I'm trying to update the landscape names in the NRGT data, the same way as we did for the BNS jobs. Used the same coding, the run fails but without giving any message.

## To Reproduce
1. Run for NRGT 2019: https://www.openfn.org/projects/p5x4g4/runs/rrkpmaee
2. Run for NRGT historical: https://www.openfn.org/projects/p5x4g4/runs/ryaz4j37

### expression.js
NRGT historical: https://github.com/OpenFn/ConSoSci/blob/master/ngrt/2017.js
NRGT 2019: https://github.com/OpenFn/ConSoSci/blob/master/ngrt/2019.js

## Expected behavior
Landscape names should be updated as follow: 
      tns: 'ndoki',
      mamabay: 'makira',
      mtkb: 'kahuzi',

**Comment by aleksa-krolls** [comment]
@dianedetoeuf It looks like your copy/pasted the code _outside_ of `alterState(...)`. We also need to do transformations _within_ a custom function where we call `state`... if it standards alone the job won't compile properly and you'll run into issues like TypeErrors.  Check out my commit here and now re-run to test! 
https://github.com/OpenFn/ConSoSci/commit/06d4f2ffed998bc8c80db70363d71694fcf4efc8#diff-07f4034d9084bb7eb8b664adb9ca392e9a1d20486ade001b4ab7ca1963be2193

Fyi, in newer jobs we're now replacing `alterState(...)` with `fn(...)`... so you will now see this `fn` instead in some jobs like bns ([see here](https://github.com/OpenFn/ConSoSci/blob/master/bns/survey.js#L3)). It means the same thing and works the same way, but it's just shorter and aligns with our namesake open function :)

Keep us posted if that does the trick :)

**Comment by dianedetoeuf** [comment]
Great, it works!! 
Now I'd like to resync... but last time I did a bulk resync of all messages corresponding to a trigger, it re-synced also testing messages that were coming from either testing forms or practice in the field that were deleted from Kobo.
Is there a way I can re-sync only what is currently on the real kobo forms?

**Comment by aleksa-krolls** [comment]
@dianedetoeuf I'd recommend running all the forms through batches again via the `historical` fetch job to make sure you're pulling the latest from Kobo. Keep me posted on Skype tomorrow if still questions

**Comment by dianedetoeuf** [comment]
Got it, thank you!
