### ISSUE TITLE
Automation job 2 fails: TypeError [Error]: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/ConSoSci#147]
## Describe the bug
See run: https://www.openfn.org/projects/p5x4g4/runs/r5em8gne

## To Reproduce
See job #1 run: https://www.openfn.org/projects/p5x4g4/runs/rpdpz4kg

### expression.js
automation 

### state.json
Job 1 with this form info: 
```
{
  formId: 'aV5DSSQjLk9xqRsGDmC8NP',
  tag: 'Copy of BNS Parc 2020',
  url: 'https://kf.kobotoolbox.org/api/v2/assets/aV5DSSQjLk9xqRsGDmC8NP/?format=json',
  prefix1: 'WCSPROGRAMS',
  prefix2: '',
  tableId: 'BNS',
  lastModified: '2021-09-02T16:58:03.018799Z'
}
```

**Comment by aleksa-krolls** [comment]
@lakhassane And when I try to run for another form... 
```
{
  formId: 'ay3PPxnKjr54Uwrb9T5wL5',
  tag: 'Copy of BNS Survey TBCA (TZ)',
  url: 'https://kf.kobotoolbox.org/api/v2/assets/ay3PPxnKjr54Uwrb9T5wL5/?format=json',
  prefix1: 'WCSPROGRAMS',
  prefix2: '',
  tableId: 'BNS',
  lastModified: '2021-09-02T17:25:07.595306Z'
}
```
...the data dictionary run fails: https://www.openfn.org/projects/p5x4g4/runs/ryaz4my8

**Comment by lakhassane** [comment]
I made the check here @aleksa-krolls and tested locally

**Comment by aleksa-krolls** [comment]
@lakhassane All runs succeed on SharksRays, but when testing for other forms... seeing other automation failures: 
`RequestError: Could not create constraint or index. See previous errors.`
Ran job 1 for formId `ay3PPxnKjr54Uwrb9T5wL5`: https://www.openfn.org/projects/p5x4g4/runs/r6gwpxby
- Mssql error: https://www.openfn.org/projects/p5x4g4/runs/r89rpg7g
- OpenFn job error: https://www.openfn.org/projects/p5x4g4/runs/rbg4nx9w

**Comment by lakhassane** [comment]
@aleksa-krolls this one was really tricky.

There are some begin_group considered as question and then mapped as table while it should not be the case.
I made a fix for it and see the history run for the formId `ay3PPxnKjr54Uwrb9T5wL5 `

https://www.openfn.org/projects/p5x4g4/runs?dateRange=custom&endDate&jobId=&page=1&perPage=10&searchString=&startDate=2021-09-08T13%3A57%3A52.151Z&success=
