### ISSUE TITLE
Assigning different datasetyear for 1 dataset

### ISSUE THREAD

**Issue by dianedetoeuf** [OpenFn/ConSoSci#148]
## Describe the bug
Normally for the BNS survey, teams collect data about every 2 years, using a different form each time. We take the year of the mid-point of the data collected with a form to determine the DatasetYear. 
See for example message https://www.openfn.org/projects/p5x4g4/messages/m78gbk7e 
Job: [BNS survey](https://github.com/OpenFn/ConSoSci/blob/master/bns/survey.js)

On the BNS Cross River dataset however, they collected data from 2017 to 2020 using the same form. We'd like to split up the data so that the DatasetYear takes the Today value, but just for this BNS CrossRiver dataset.

How do I code in the BNS job something that says:
 DatasetYear: _normal mapping_ || year of Today if (DatasetName is 'BNS Cross River 2017-2020') ?

Thank you!

## adaptor
See LP for `WCS Programs Database (central db)`

**Comment by ritazagoni** [comment]
@lakhassane 
Please the use the value of the field "today". For example:
```
 "today": "2021-04-19",
if "DatasetName" = "BNS Cross River 2017-2020" 
then "DatasetYear" = 2021
```

**Comment by lakhassane** [comment]
@ritazagoni changes made as per our talk

**Comment by ritazagoni** [comment]
thanks @lakhassane 
@dianedetoeuf this is ready

**Comment by dianedetoeuf** [comment]
Hi, thanks Mamadou and Rita!
I've run the historical job to resync the Cross river data and it looks like the 1B failed: https://www.openfn.org/projects/p5x4g4/runs/raa46xpj
But it looks like the messages are being processed with the 2B successfully...

**Comment by ritazagoni** [comment]
@lakhassane pls check this failed run https://www.openfn.org/projects/p5x4g4/runs/rzdgn53x

**Comment by ritazagoni** [comment]
opened new issue #149

**Comment by dianedetoeuf** [comment]
Hi, in the DB the dataset year is now 2021 so it's not exactly what we expected. But the transformation might be more difficult than just reassigning the dataset year...

This "BNS Cross River 2017 - 2020" is considered as 1 dataset in the DB, but we need it to be split into one dataset per year. So there should be 3 datasets: 
- one for data collected in 2017
- one for data collected in 2018 and 19
- one for data collected in 2020

With corresponding datasetyear. Is this feasible?

**Comment by ritazagoni** [comment]
@dianedetoeuf How can we differentiate the 3 parts of the dataset? Could you walk me through an example sometime today?

**Comment by dianedetoeuf** [comment]
We can differentiate them using the value of the "today" field. Happy to talk about it on skype today!

**Comment by ritazagoni** [comment]
New issue: #150
