### ISSUE TITLE
BNS survey: `Error converting data type varchar to float.`

### ISSUE THREAD

**Issue by ritazagoni** [OpenFn/ConSoSci#149]
## Describe the bug
BNS survey job fails with  `Error converting data type varchar to float.`

## To Reproduce
1. Here is a link to a failed run on OpenFn.org wihch is indicative of the bug: https://www.openfn.org/projects/p5x4g4/runs/rn5pgywr

### expression.js
Link to the job itself in Github: https://github.com/OpenFn/ConSoSci/blob/master/bns/survey.js

### state.json

See LP for `WCS Programs Database (central db)`

## To test/resolve
Feel free to re-run https://www.openfn.org/projects/p5x4g4/runs/rn5pgywr

**Comment by lakhassane** [comment]
Hey @ritazagoni I checked here and so the issue is with `Lat` and `Long` being null.
It is mapped as this 
```js
 Long: state => {
    return dataValue('gps/long')(state)
      ? dataValue('gps/long')(state)
      : state.data._geolocation[1];
```
however both the path provided here are absent from state. Is there another option we should map ? Or return 0 if it's null?

**Comment by lakhassane** [comment]
so currently I mapped undefined if it's null

**Comment by dianedetoeuf** [comment]
Thank you, mapping undefined is fine
