### ISSUE TITLE
Automation: Change request for how we create unique `select` lookup tables

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/ConSoSci#152]
## Background, context, and business value
This builds upon issues #131 , #133 , #141 . 

Currently the solution creates a "lookup" table for every unique question name. Every time we see a `select_one` or `select_multiple` question in the Kobo form definition, we auto-generate lookup tables to capture the choice values for these questions. For example: 
question `type: select_one, name: sex` --> table `WCSPROGRAMS_Sex`
question `type: select_one, name: vendor_sex` --> table `WCSPROGRAMS_VendorSex`

## The specific request, in as few words as possible
WCS is concerned that this is creating too many lookup tables when the choice value options are the same across multiple questions. Multiple Kobo questions might link to 1 choice value `list`. 
For example... Kobo questions `sex` and `vendor_sex` both link to the _same_ choice value list `sex`. 
<img width="438" alt="Screen Shot 2021-09-13 at 10 08 55 AM" src="https://user-images.githubusercontent.com/16758106/133041185-e3d9ad10-2b9d-410a-953f-afffcf76e16c.png">
<img width="142" alt="Screen Shot 2021-09-13 at 10 09 59 AM" src="https://user-images.githubusercontent.com/16758106/133041195-a4c07ad9-001a-4a2a-a7e4-a0d9b96495ed.png">

Is it possible to only generate lookup select tables based on unique **choice list names**, rather than unique question names? This way, multiple survey tables might map to the same lookup table because they share the same choice list...
- question `type: select_one sex, name: sex` --> lookup tbl `WCSPROGRAMS_Sex`, fk: `WCSPROGRAMS_SharksRays.WCSPROGRAMS_SexID`
- question `type: select_one sex, name: vendor_sex` --> lookup tbl `WCSPROGRAMS_Sex`, fk: `WCSPROGRAMS_SharksRaysVendor.WCSPROGRAMS_SexID`

Consider the implications for both `select_one` and `select_multiple` questions... this could be tough. Let me know if helpful to talk through. 

## state.json
Mssql: `WCS test mssql`
Postgres: `WCS Consosci DB`

Run job `A1` for Sharks & Rays form: https://www.openfn.org/projects/p5x4g4/jobs/jyd8gg
```
{
      uid: 'apZrpKcK78xzrPcAfRrfac',
      p1: 'WCSPROGRAMS',
      p2: '',
      tableId: 'SharksRays',
 },
```

## adaptor
mssql AND postgres 

## expression.js
`automation` jobs

## output.json
This should reduce the number of auto-generated tables in the DB... because we should have only 1 table `WCSPROGRAMS_Sex`, and no longer need `WCSPROGRAMS_VendorSex`.

**Comment by aleksa-krolls** [comment]
@lakhassane How is this going? Anything to talk through? (When you get the chance, would you please share a quick update and any questions for me to include in my call with them later today?)

**Comment by lakhassane** [comment]
@aleksa-krolls I might have one concern here:

So basically we should use the list name instead of question name.
One example in the current form I have is `yesno` select list name. We have 2 questions (`boat_info`, `targeted` and `release_shark_ray`) using the same select list name. So per the specs we should create only one table for all of them `WCSPROGRAMS_YesNo`.

However, the way we were generating the openfn job: here are the operations for those select_one tables:
```js
alterState(async (state) => {
  const mapping = {
    WCSPROGRAMS_BoatInfoName: dataValue("boat/boat_info"),
    WCSPROGRAMS_BoatInfoExtCode: dataValue("boat/boat_info"),
  };
  return upsertIf(
    dataValue("boat/boat_info"),
    "WCSPROGRAMS_BoatInfo",
    "WCSPROGRAMS_BoatInfoExtCode",
    mapping,
    { setNull: ["''", "'undefined'"] }
  )(state);
});

alterState(async (state) => {
  const mapping = {
    WCSPROGRAMS_TargetedName: dataValue("boat/targeted"),
    WCSPROGRAMS_TargetedExtCode: dataValue("boat/targeted"),
  };
  return upsertIf(
    dataValue("boat/targeted"),
    "WCSPROGRAMS_Targeted",
    "WCSPROGRAMS_TargetedExtCode",
    mapping,
    { setNull: ["''", "'undefined'"] }
  )(state);
});
```

With that new change we should not do this anymore but generate an operation for `yesno`while there is no path in the form data for a `yesno` question (as there are for `boat_info` or `targeted`)

**Comment by lakhassane** [comment]
@aleksa-krolls so I was able to create only one table for all the list names (e.g. `WCSPROGRAMS_YesNo`) and then only one operation that will map to that table using any of the select_one question.

Now we might still have that same issue where we upsert multiple times the same row. I'm going to make a test to see if I can trigger it and see how to put a fix for it.

**Comment by aleksa-krolls** [comment]
@lakhassane Thanks for the update. It sounds like work is still in progress here, but have your changes been pushed? Is it valuable for me to run a test now?

**Comment by lakhassane** [comment]
@aleksa-krolls I think I finally got there.
This is a sample job generated https://gist.github.com/lakhassane/7e8eb0863d5c1192cca2b0df7ac72d6d

Have a look at some of the lookup talbes (`[WCSPrograms_Yesno](https://gist.github.com/lakhassane/7e8eb0863d5c1192cca2b0df7ac72d6d#file-newjob-js-L379-L393)`)

The trick is for select questions, I dynamically build an array of list of values that exists in the form definition. So, when upserting a table for that selection question, I iterate through that array for it's values and insert one by one.

look here for an exemple of how those array are represented in the job: https://gist.github.com/lakhassane/7e8eb0863d5c1192cca2b0df7ac72d6d#file-newjob-js-L411

**Comment by aleksa-krolls** [comment]
@lakhassane This is some dark magic :D. My reactions below - but let me know if you want to jump into a hangout to talk this through...
1. Lookup tables - looking great!
2. Data arrays built into jobs... so will these be hardcoded into the job? What happens if data values changed in the Kobo form? (Wondering if there's a more dynamic way of doing this, or whether the client will need to continually check for Kobo form changes in order to upsert the job?)
3. I think we upsert the select tables using `ExtCode`, yes? I'm looking here: https://gist.github.com/lakhassane/7e8eb0863d5c1192cca2b0df7ac72d6d#file-newjob-js-L390
If yes, then let's using `ExtCode` for the `where` in the `findValue(...)` function...
` where: { WCSPROGRAMS_yesnoExtCode: dataValue("boat/targeted") },`

4. Also... WCS wants all FK columns on child tables to have the same name as the PK on the parent select table. So if we have questions `targeted` and `boatinfo` that link to the `yesno` list... the FK column names should both be `WCSPROGRAMS_YesNoID` (and not include the question names `Targeted` and `BoatInfo`. 
**See below for desired mapping example:** 
```
 WCSPROGRAMS_YesNoID: await findValue({ //replaced WCSPROGRAMS_TargetedID:
        uuid: "wcsprograms_yesnoid",
        relation: "WCSPROGRAMS_yesno",
        where: { WCSPROGRAMS_yesnoExtCode: dataValue("boat/targeted") }, //replaced WCSPROGRAMS_yesnoName
      })(state),
```

**Comment by taylordowns2000** [comment]
My 2c...

1. find form defintion (in `processForm` ?)
2. find `choices` array
3. group items in `choices` array by `select_list_name` (create `choice_list_dictionary` :white_check_mark: )
4. in `syncToPostgres`…
5. … add/update tables
6. … pre-populate choices tables with valid choices

because this is “build time” configuration for the DB… it all has to get done before any OpenFn jobs try to load data to the DB.

the argument is that our previous separation between “build tables” and “load data” was actually not the best fundamental mental separation

a **better logical separation would be “setup database” and “stream submission data”**

if you look at DB setup for other webapps, you typically have two steps:
- run the migrations (to create tables)
- run the “seeds” (to add prepopulated data… like “plans” and “products” in the OpenFn db.)

And _then_ runtime (not build time) is when users, messages, runs, etc., get inserted

cc @aleksa-krolls  just spoke with @lakhassane  and he’s on board with this refactor. (the language / logical-separation-stuff above is super important to all be on the same page about)

**Comment by lakhassane** [comment]
@aleksa-krolls updates on this. So 1..5 are done. Just need to finish iterating on the choices array and populate the pre-built tables and we are done.

Also on your comment above Taylor's one I have implemented the changes requested. Might finish the rest later today or tomorrow morning.

**Comment by aleksa-krolls** [comment]
Thanks @lakhassane @taylordowns2000 Refactor is sounding good... but can we talk this through today after standup? I want to make sure what you're envisioning here will work given how I expect WCS to be using this automation solution vs. actions they plan to take manually. 

Also, @lakhassane can you provide a timeline estimate for when these changes will be ready for testing? This morning, I need to send WCS new timelines so that we & they can plan their weeks accordingly.

**Comment by aleksa-krolls** [comment]
Thanks @lakhassane @taylordowns2000 Refactor is sounding good... but can we talk this through today after standup? I want to make sure what you're envisioning here will work given how I expect WCS to be using this automation solution vs. actions they plan to take manually. 

Also, @lakhassane can you provide a timeline estimate for when these changes will be ready for testing? This morning, I need to send WCS new timelines so that we & they can plan their weeks accordingly.

**Comment by lakhassane** [comment]
@aleksa-krolls it's all check. I will merge this branch to master so you could run the process and test.
I also cleaned the DB

**Comment by aleksa-krolls** [comment]
@lakhassane I'm reviewing the [latest sql script](https://github.com/OpenFn/ConSoSci/blob/master/sharks_rays/autoSql_SharksRays.sql) and have some feedback...

1. Following up to my change request `4` in my last comment - the FK columns need to have the naming convention `ParentPkID_QuestionName` (e.g., `WCSPROGRAMS_SexID_VendorSex`, `WCSPROGRAMS_SexID_SSex`). 
However, currently it looks like `ID` is appended at the name of the column (e.g., `WCSPROGRAMS_Sex_VendorSexID`, `WCSPROGRAMS_Sex_SSexID`). Can you please correct this? 

2. Change request from WCS: Add `not null` constraint for required questions. 
If select questions in Kobo forms are _required_ (`required: true` in Kobo form definition), then in the corresponding DB column needs to be set as `not null`. 

E.g., The questions `select_one vendor_sex` and `select_one survey_type` are required in the Kobo form. Therefore the fk columns `WCSPROGRAMS_SexID_VendorSex`, `WCSPROGRAMS_SurveyTypeID_SurveyType` should be set as `not null` because we always expect a lookup value to be provided in these columns. 

![image](https://user-images.githubusercontent.com/16758106/134120528-13ca5912-e347-45af-b0c7-f5f5e034943d.png)

**Comment by lakhassane** [comment]
@aleksa-krolls feedback on here: 
1. All the sql to copy/paste is now after the `Logging queries` log (https://www.openfn.org/projects/p5x4g4/runs/r7xpm8ww). If you look at line `1427` you can find the one that populate the DB.
2. I made the change accordingly (look at line 
3. It was already implemented from what I see. See screenshot below for `WCSPROGRAMS_SexID_VendorSex`. The same can be found for `WCSPROGRAMS_SurveyTypeID_SurveyType` and others.
<img width="735" alt="Screen Shot 2021-09-21 at 10 02 20" src="https://user-images.githubusercontent.com/8411231/134151845-18d087e2-ed36-461b-a90a-09469cb64f8c.png">

**Comment by aleksa-krolls** [comment]
@lakhassane thank you!!! Latest sql script shared with the client, and also copied to github here: https://github.com/OpenFn/ConSoSci/blob/master/sharks_rays/autoSql_SharksRays.sql
