### ISSUE TITLE
Automation: Auto-generated S&R job fails to sync data

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/ConSoSci#155]
## Request
Given the changes made for issue #152 , we now need to replicate this in the auto-generated job: https://www.openfn.org/projects/p5x4g4/jobs/jyk5mw

When I've tried syncing data against the auto-generated job, I'm only encountering failures. See example: 
TypeError: https://www.openfn.org/projects/p5x4g4/runs/0614b16b-5000-703c-986c-cf15cee36cbd

## adaptor
Pls prioritize mssql first (also needs to be made for postgres)

## state
`WCS test mssql db`
Please test against these Message states: 
1. https://www.openfn.org/projects/p5x4g4/messages/0611b5f1-f000-7de6-ad7e-033bfba9bf63
2. https://www.openfn.org/projects/p5x4g4/messages/m66wrjdd

## expression
Auto-generated job: https://www.openfn.org/projects/p5x4g4/jobs/jyk5mw
https://github.com/OpenFn/ConSoSci/blob/master/automation/02b-syncToOpenFn.js

**Comment by lakhassane** [comment]
Hey @aleksa-krolls could you give me more context on this one please?

**Comment by aleksa-krolls** [comment]
@lakhassane Sorry I think I was looking at an older version of the auto-generated job. I've updated the issue with details on the current problems I'm experiencing. Let me know if you need more info!

**Comment by taylordowns2000** [comment]
@lakhassane , line `84-85` of the auto-generated job is `Latitude: state => state.data.gps.split(' ')[0]`.

@aleksa-krolls , assuming that the desired outcome is for cases when no GPS sends to set this field as `null` in Postgres, we should @lakhassane , change this to use something like `state.data.gps?.split(...)`

**Comment by aleksa-krolls** [comment]
@lakhassane looking good... and we have sign off from Steve on the auto-generated sql (WAHOOOOO!!!). Good work dude :)
