### ISSUE TITLE
Automation: If all `execute` options are `false`, do not check for existing tables and generate create SQL script

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/ConSoSci#162]
## Background
Currently the automation fails if this option is `execute: false`. However, sometimes we don't want to check an existing DB if tables or columns exist because the client doesn't want to compare with only 1 DB... sometimes the client wants to generate a base sql script and then adjust from there as needed for each destination.  

https://github.com/OpenFn/ConSoSci/blob/865934c831d2cbd33f87784d79caefe7fffd8776/automation/02c-syncToMssql.js#L25-L29

## Request
If all options `execute: false` do not check the DB for existing tables & columns, but rather go ahead and generate a SQL script assuming that all tables and columns do not exist and need to be created. 

## adaptor
First mmsql (and then postgres)

## expression 
automation/02c-syncToMssql.js

## state
See LP for `wcs test mssql db`
Re-run job `A1` in order to generate a new state.

**Comment by lakhassane** [comment]
This is handled with the latest update on `02b-syncMetadataMssql` and `02c-syncToMssql`.

**Comment by lakhassane** [comment]
@aleksa-krolls I added some inline comments and a bigger one at the top to explain what's going on. Let me know if this is helpful.
https://github.com/OpenFn/ConSoSci/blob/master/automation/02c-syncToMssql.js#L1-L5
