### ISSUE TITLE
Automation: Update table naming syntax

### ISSUE THREAD

**Issue by ritazagoni** [OpenFn/ConSoSci#165]
## The specific request, in as few words as possible

Currently we're using the convention `prefix1_prefix2_tableID` to name database tables in the automation solution.

We would like to update it to use the following syntax: `prefix1_prefix2tableID`
For example:
```
p1: 'WCSPROGRAMS',
p2: 'SocioEco',
tableId: 'SocioEcoSurvey'
```
Current table name: `WCSPROGRAMS_SocioEco_SocioEcoSurvey`
Desired table name: `WCSPROGRAMS_SocioEcoSocioEcoSurvey`

The change needs to be done in the following jobs:
https://github.com/OpenFn/ConSoSci/blob/master/automation/00-findUpdates.js
https://github.com/OpenFn/ConSoSci/blob/master/automation/01-processForm.js
https://github.com/OpenFn/ConSoSci/blob/master/automation/02a-syncToPostgres.js
https://github.com/OpenFn/ConSoSci/blob/master/automation/02b-syncToOpenFn.js
https://github.com/OpenFn/ConSoSci/blob/master/automation/02c-syncToMssql.js

## state.json
Kobo ([findUpdates job](https://github.com/OpenFn/ConSoSci/blob/master/automation/00-findUpdates.js
)): `OpenFn Kobo Toolbox`
Mssql: `WCS test mssql`
Postgres: `WCS Consosci DB`

## adaptor
language-http
language-openfn
mssql
postgres

**Comment by aleksa-krolls** [comment]
@lakhassane Ready to work on. This should be applied to the entire automation solution... this is the new default naming convention. Let @ritazagoni know if any questions!

**Comment by lakhassane** [comment]
@ritazagoni I updated the job for new naming convention.

The updates needed to be done only in `syncToOpen`, `syncToMssql`, and `processForm`

**Comment by aleksa-krolls** [comment]
@ritazagoni @lakhassane remember we had to make copies of these jobs for Trillion Trees... can you coordinate to make the relevant changes here? (Or not sure if it should go elsewhere/if Rita has setup the new repo yet.)

https://github.com/OpenFn/ConSoSci/tree/master/automation/trillion-trees

**Comment by ritazagoni** [comment]
@lakhassane I'm moving the Trillion Trees jobs now - I'll let you know once ready so you can make the changes there

**Comment by ritazagoni** [comment]
@lakhassane please update the Trillion Trees jobs here: https://github.com/WCS-ConsTech/OpenFn-TrillionTrees
