### ISSUE TITLE
Automation: Ensure solution handles `select_many` Kobo questions & generates `m:m` tables properly

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/ConSoSci#168]
## Request
WCS says this Arcadia Kobo form has `select_many` questions that display data in the standard format we should expect across the automation solution. 

E.g., Kobo question `select_multiple surveys_planned` will have JSON submissions that look like: 
`"surveys_planned": "basic_necessities_survey camera_trapping other_passive_sensor"`

Can you please run the automation solution for this form and make sure that the auto-generated job syncs data as expected? 
Job `A1`: https://www.openfn.org/projects/wcs/jobs/jyd8gg
```
{
        uid: 'aDgPJqN4SAYohZ4ZueEeYU',
        p1: 'WCSPROGRAMS',
        p2: 'Arcadia',
        tableId: 'SiteSurvey'
},
```

### expression.js
https://github.com/OpenFn/ConSoSci/tree/master/automation

### state.json
See LP for `wcs test mssql db`
Sample states with select_multiple questions: 
1. https://www.openfn.org/projects/wcs/messages/061a644e-7f3e-77cb-b02c-7d20229edb67
2. https://www.openfn.org/projects/wcs/messages/061a644e-7f3e-7d5d-92da-5ea9efb89501
3. https://www.openfn.org/projects/wcs/messages/061a644e-6e43-78ca-8c81-b0db133dd09b

## Expected behavior
Please make sure the data for m:m tables is syncing properly. See above for some sample states that have data for different m:m tables.

**Comment by aleksa-krolls** [comment]
@lakhassane can you please share a status update and estimated time needed to complete? Need to keep WCS informed and prioritize accordingly, thanks!

**Comment by aleksa-krolls** [comment]
@lakhassane See Slack for the test I tried to re-run: https://openfn.slack.com/archives/C031G8JAU/p1639066046018900?thread_ts=1639040890.001800&cid=C031G8JAU

Before signing off today, can you please leave me a summary of (1) what you've changed, and (2) what is working now, and (3) issues if any? Need to share with WCS bc they are waiting for us to sort this before they run again. I need to leave now... but will check back online later tonight for your updates!

**Comment by lakhassane** [comment]
@aleksa-krolls quick feedback here:

1. I have changed : (1) how we generate data manipulation for `select_multiple` questions. Now we don't consider them as arrays anymore; (2) groups were wrongly input as arrays also, and that's corrected.
2. Generating DB script and DB structure works fine, as well as generating the job.
3. Main issue is just removing some auto-generated column as `GeneratedUuid` that we were using in the past as uuid but not anymore. And it should be the last thing to worry about

**Comment by aleksa-krolls** [comment]
@lakhassane Please prioritize this today while you still have context built up... but can you please refresh the estimate on this issue based on what you think is left to complete today? 

Keep me posted on when I can retest, and don't hesitate to reach out if you need to discuss anything.

**Comment by aleksa-krolls** [comment]
@lakhassane for the m:m table Ids, as discussed - let's use `_id`, question `name`, and what # item it is in the array.

**Comment by aleksa-krolls** [comment]
@lakhassane last change needed for the prefixes... 
If `p1` only: `p1_FormName` (e.g., `WCSPROGRAMS_SiteSurvey`)
If also `p2`: `p1_p2FormName`  (e.g., `WCSPROGRAMS_ArcadiaSiteSurvey`)

Current behavior: 
If `p1` only: `p1FormName` (e.g., `WCSPROGRAMSSiteSurvey`... needs underscore!)
If also `p2`: `p1_p2FormName` (correct!)

**Comment by lakhassane** [comment]
@aleksa-krolls I made the changes for point 1 here

**Comment by aleksa-krolls** [comment]
@lakhassane Tests are looking good so far! Thank you for all of the hard work, and for updating the default mssql adaptor version to `v2.6.9`. 
I will continue testing, as well as hand-off to WCS for additional review.
