### ISSUE TITLE
Arcadia: Help correct WCS edits made to the job

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/ConSoSci#169]
## Describe the bug
We created this existing job... but WCS made a handful of change that broke the job by copying/pasting similar examples from other jobs. **Can you please help to correct & get this job up and running again for all Arcadia messages?** 

From Steve: 
```
There are 4 items in this xls that were added to the Kobo form. 
I've also attached the definition for the supporting tables.
It is 1 bit field, 2 lookups, and one m:m relationship.
```
1. Form changes (see green highlighted rows): https://docs.google.com/spreadsheets/d/1jlZdl8xt8rPrFrV36JJyS5ywZdQO_eEWlq53IMFEn0E/edit?usp=drive_web&ouid=101430720901034004945
2. SQL definition: https://drive.google.com/file/d/1yxVv6uRy5s_jvzJ2H5qDSU0e7ABGU_dI/view?usp=sharing

Based on these form changes^, Diane tried to make job edits (see commit history). Please reach out to her on Skype to chat or get on a call if you have any questions regarding these changes. 

## To Reproduce
Example run failure: https://www.openfn.org/projects/wcs/runs/061a7aca-cb48-7c2c-ac99-75ccf1cbf7e5
Feel free to re-run on prod. 

### expression.js
https://github.com/OpenFn/ConSoSci/blob/master/arcadia/arcadiaSiteDataCollection.js

### state.json
See LP for `wcs programs db`
We need to make sure **all these Message states run successfully:** https://www.openfn.org/projects/wcs/messages?dateRange=custom&endDate=2021-12-01T18%3A16%3A08.614Z&jobStates=&page=1&perPage=10&searchString=&startDate=2021-11-01T18%3A16%3A06.440Z&triggerId=t9vjw8

**Comment by aleksa-krolls** [comment]
@lakhassane pls prioritize today... I also sent a calendar invite for you and Diane to sync in case you have questions. If that doesn't work for you, feel free to message her directly on skype to coordinate a time.

**Comment by lakhassane** [comment]
Questions that could help for the call.

1. What is the mapping for the table `WCSPROGRAMS_ProjectAnnualDataPlanCameraTrapSetting`. Where would each column comes from?
2. ...

**Comment by lakhassane** [comment]
@dianedetoeuf you can find the last version in the file `arcadiaSiteDataCollection.js` for testing. Beware you might find some issues while testing occasionnaly about: 
- missing columns (to add in the mapping),
- columns not accepting `NULL` because there is no value for them in the state while they are mandatory (this is the case of `WCSPROGRAMS_ProjectID`)

**Comment by dianedetoeuf** [comment]
Hi Mamadou, thank you! I don't understand the error that I have (https://www.openfn.org/projects/wcs/runs/061a9e26-b0a1-71cb-bc38-f842d7e9e39a) do you know which columns to add/make nullable?

**Comment by lakhassane** [comment]
@dianedetoeuf the job needed a newer adaptor version. Check here you will see some of the errors I was talking about https://www.openfn.org/projects/wcs/runs/061a9e9d-58c9-716f-80e2-d713599afb6b

**Comment by aleksa-krolls** [comment]
@dianedetoeuf If the below mapping is returning nothing, maybe it cannot find `"swm_site": "2022"` in the DB? And/or is the mapping right?
```
 WCSPROGRAMS_ProjectID: await findValue({
      uuid: 'wcsprograms_projectid',
      relation: 'WCSPROGRAMS_Project',
      where: { WCSPROGRAMS_ProjectExtCode: dataValue('$.body.swm_site') },
    })(state),
```

**Comment by dianedetoeuf** [comment]
I think the mapping is right, maybe it's just IDs missing in the lookup tables. Will check with Steve. Thank you!
