### ISSUE TITLE
TT automation TypeError

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/ConSoSci#175]
See the issue logged on the non-OpenFn repo: https://github.com/WCS-ConsTech/OpenFn-TrillionTrees/issues/3

Please replicate any changes made there in these automation jobs.

**Comment by aleksa-krolls** [comment]
@ritazagoni I think we need to create an issue on `consosci` for every TT issue to make sure it shows up on the board _and_ to make sure changes are replicated.

**Comment by lakhassane** [comment]
Changes replicated from the commit from the TT issue

**Comment by ritazagoni** [comment]
Handed over to Diane.
