### ISSUE TITLE
Automation: Replicate all mssql changes in Postgres

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/ConSoSci#181]
## The specific request, in as few words as possible
See recent data flow docs where we flagged some Automation changes made for mssql have not been replicated for Postgres. Can you please replicate any changes in the postgres jobs? 
https://lucid.app/lucidchart/72aa1aa9-3b8a-4a67-aafe-488e98ff7e0d/edit?invitationId=inv_c1d02e73-35d9-466e-88fc-2365f0610e37&page=0_0#

## state.json
Mssql: `WCS test mssql`
Postgres: `WCS Consosci DB`

## expression
https://github.com/OpenFn/ConSoSci/tree/master/automation

## adaptor
postgres

**Comment by lakhassane** [comment]
@aleksa-krolls I replicated all the change in `SyncToPostgres` and updated the diagram
