### ISSUE TITLE
Modify NRGT job `2017_v2.js` to handle different Kobo data structure

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/ConSoSci#182]
## Background, context, and business value
NRGT is a Kobo data collection form to help assess natural resource governance. In 2020, OpenFn and WCS wrote a job to sync this Kobo form with a Microsoft SQLServer DB. 

Over the years, this Kobo form has been modified by different data collection teams to localize and add new questions. Now we're finding that one of these Kobo form versions has a slightly different data structure than the other forms, for which the OpenFn job was written. 

## The specific request, in as few words as possible
Modify the job `2017_v2.js` to handle this new Kobo form version where `state.data` looks like [this Message](https://www.openfn.org/projects/wcs/messages/06219083-c751-7123-864b-5cc8420539ae). Changes will include: 
1.  **For each item** in the `group_scores` array (see L43 in [the Message](https://www.openfn.org/projects/wcs/messages/06219083-c751-7123-864b-5cc8420539ae)), upsert 1 record in the DB table `WCSPROGRAMS_KoboNrgtNrgtanswergs`). 
- The current job version currently does not expect this data to be submitted as an array. 
- Consider using the `each(...)` helper function: https://docs.openfn.org/documentation/jobs/each/
2. Update [the mappings](https://github.com/OpenFn/ConSoSci/blob/master/ngrt/2017_v2.js#L57-L78) for DB table `WCSPROGRAMS_KoboNrgtNrgtanswergs` to consider the new JSON paths given the presences of the `group_scores` array in this form version (e.g., JSON path for `accountability` is --> `group_scores/accountability` given this new state.data)

## state.json
Use the following to create your `state.json` file. The destination db is `wcsprograms`, so contact the WCS team if you don't already have access. 

```json
{
  "configuration":  {
    "userName": "shhh",
    "password": "secret",
    "server": "something.database.windows.net",
    "database": "dbName"
  },
  "data": { <paste Message>  }
}
```
See Message for state.data: https://www.openfn.org/projects/wcs/messages/06219083-c751-7123-864b-5cc8420539ae

## adaptor
language-mssql: https://github.com/OpenFn/language-mssql

## expression.js
Feel free to commit directly to the master branch for this job: 
https://github.com/OpenFn/ConSoSci/blob/master/ngrt/2017_v2.js

Here are the OpenFn/Devtools docs if you want to test & run locally: https://docs.openfn.org/documentation/devtools/home#usage

## Expected output
For each item in the `group_scores` array, upsert 1 record in the DB table `WCSPROGRAMS_KoboNrgtNrgtanswergs`. Ensure that all relevant columns are mapped in this table. 

Once this data has been successfully synced, let us and Diane know to test across other Kobo form submissions.

**Comment by vmasanas** [comment]
@aleksa-krolls  would you modify the job to support both scenarios or create a new job to handle the new form and modify the current job to filter out the specific messages for the new form?

**Comment by vmasanas** [comment]
@mvazquez4 FYI
