### ISSUE TITLE
Load Archived Kobo Monitoring Form Data to MSSQL DB #1

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/ConSoSci#191]
This issue is captured on *another WCS-owned repo*. I'm linking to it here so that we can view on Zenhub. 
Please see here for the issue link and push all work to that `OpenFn-WCS-Projects` repo. 
https://github.com/WCS-ConsTech/OpenFn-WCS-Projects/issues/1

**Comment by aleksa-krolls** [comment]
@jayesse this is done, yes? can we close?

**Comment by jayesse** [comment]
Issue is done. Closing now
