### ISSUE TITLE
`Trillion Trees` Kobo Monitoring Job not loading the `Country` field

### ISSUE THREAD

**Issue by jayesse** [OpenFn/ConSoSci#192]
## Describe the bug
The Trillion Trees Kobo Monitoring Job is not loading some fields when the [KM2. Fetch Kobo Forms Data job](https://github.com/WCS-ConsTech/OpenFn-WCS-Projects/blob/main/kobo_monitoring/getFormDataFromKobo.js) runs. 

The reported fields are:
~`Languages`~ (oops. bad issue. this field was already properly mapped.)
~`Default language`~ (oops. bad issue. this field was already properly mapped.)
~`Date created`~ (oops. bad issue. this field was already properly mapped.)
~`Date modified`~ (oops. bad issue. this field was already properly mapped.)
~`Version ID`~ (oops. bad issue. this field was already properly mapped.)
~`Date deployed`~ (oops. bad issue. this field was already properly mapped.)
- `Country`
~`Number of questions`~ (oops. bad issue. this field was already properly mapped.)

## To Reproduce
1. Run the the [KM1. Get List of Kobo Forms job](https://github.com/WCS-ConsTech/OpenFn-WCS-Projects/blob/main/kobo_monitoring/getKoboFormsFromDB.js). This will trigger the  [KM2. Fetch Kobo Forms Data job](https://github.com/WCS-ConsTech/OpenFn-WCS-Projects/blob/main/kobo_monitoring/getFormDataFromKobo.js) and finally the  [KM3. Upsert Kobo Monitoring Data job](https://github.com/WCS-ConsTech/OpenFn-WCS-Projects/blob/main/kobo_monitoring/upsertKoboMappingData.js) . 
2. Log into the `WCS test mssql` DB and check the `TT_KoboData` table.

### expression.js
**⚠️ Please create a `Staging` branch and make all changes on this branch; do NOT commit to Master.** 
Link to the job itself in Github: [KM2. Fetch Kobo Forms Data job](https://github.com/WCS-ConsTech/OpenFn-WCS-Projects/blob/main/kobo_monitoring/getFormDataFromKobo.js) 

### state.json
Run the the [KM1. Get List of Kobo Forms job](https://github.com/WCS-ConsTech/OpenFn-WCS-Projects/blob/main/kobo_monitoring/getKoboFormsFromDB.js) using the details below. This will trigger the  KM2. Fetch Kobo Forms Data job

**MSSQL DB**
See LP for `WCS test mssql db`
Once logged into the `wcsprograms_opiant` DB, select the `dbo` schema and find the table called `TT_KOBODATA`.

**Note**: You will require OpenFn VPN / Wireguard to connect to the DB.

**KOBO TOOLBOX**
See LP for `Trillion Trees Kobo (TT) ` 
[Here ](https://github.com/WCS-ConsTech/OpenFn-WCS-Projects/blob/main/kobo_monitoring/sample_data/koboFormDeploymentResponse.js) is a sample json from Kobo that serves as input to Job 2

```json
{
  "configuration": ["SEE LAST PASS: 'client cred'"],
  "data": { "a": 1 },
  "cursor": "2020-01-19 00:00:00"
}
```

## Expected behavior
Data should be fetched from Kobo and used to trigger the sync Job (KM 3) to upsert data in the DB.

## To test/resolve
1. After the desired output is working locally (from the CLI), please [push commits to staging branch || open a pull request].
2. Joseph will test on platform to confirm that the job is now able to fetch the right data from Kobo

## Toggl 

WCS Support 2023

**Comment by mtuchi** [comment]
@taylordowns2000 
https://github.com/WCS-ConsTech/OpenFn-TrillionTrees

**Comment by taylordowns2000** [comment]
@jayesse , see above. i've edited this issue to reflect the real request and opened a new one for the new request on `Last submission time`

**Comment by jayesse** [comment]
@mtuchi As discussed, the issues here seem to be resolved from my end. Please move this to QA pending the client's confirmation. We will tackle the addition of new fields in issue #193. Thanks

**Comment by aleksa-krolls** [comment]
@jayesse can we close this out? We can always re-open or create another ticket if new issues

**Comment by jayesse** [comment]
Issue closed as it is resolved
