### ISSUE TITLE
OpenFn Log Suggests BNS Price Job is loading data into mssql DB but query is returning zero results 

### ISSUE THREAD

**Issue by daissatou2** [OpenFn/ConSoSci#199]
## Describe the bug
This OpenFn run [log](https://www.openfn.org/projects/consosci/runs/065afd2e-59c5-78f5-ab80-89e64db6c14d) says that 4 rows were inserted into the WCS database. However, when we query the db for those rows, we get zero results. 

## To Reproduce
1. Here is a link to a failed run on OpenFn.org which is indicative of the bug: https://www.openfn.org/projects/consosci/runs/065afd2e-59c5-78f5-ab80-89e64db6c14d

### expression.js
Link to the job itself in Github: https://github.com/OpenFn/ConSoSci/blob/master/bns/price.js

### state.json

Message: https://www.openfn.org/projects/consosci/messages/065afd2e-5129-7e1f-90c0-c92002093cf1

```json
{
  "configuration": ["SEE LAST PASS: 'WCS Programs Database (central db)'"],
  "data": { "See message link above" },
}
```

## Expected behavior
There should be 4 new rows in the database table `WCSPROGRAMS_KoboBnsPrice` where `AnswerId` = '295675596'

## To test/resolve
1. After the desired output is working locally (from the CLI), please [open a pull request].
2. [Please test the change on OpenFn.org by re-running this run (https://www.openfn.org/projects/consosci/runs/065afd2e-59c5-78f5-ab80-89e64db6c14d) and confirming success.]

**Comment by aleksa-krolls** [comment]
@mtuchi please take this on tomorrow and keep @daissatou2 posted on your updates
