### ISSUE TITLE
New workflow to check if new forms shared with Kobo user & to notify WCS admin

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/ConSoSci#206]
## Background, context, and business value
WCS teams around the world using Kobo Toolbox to collect data. WCS's admin on the global IT team would like to be notified when a team deploys a new Kobo form for data collection so that she can consult with the research team, make sure the form information is up-to-date, and ensure the form data can be automatically synced using OpenFn. 

[See the high level spec](https://docs.google.com/document/d/1pZvEF9bzh4GowcDy2j0F0Yuh3nWi_9VNs_tb_7yHS98/edit) shared by the client --> we've used this to inform our workflow logic & mapping spec. 

## The specific request, in as few words as possible
Create a new workflow (probably 4 jobs) to automate checking if new Kobo forms have been shared with the WCS kobo user. If yes, then these new forms must be (1) added as rows to GoogleSheets and then (2) trigger a new Asana Task to be created and assigned to the WCS Admin (Diane). 
- [See workflow diagram](https://lucid.app/lucidchart/346b8e5c-6fb6-4a33-9d02-53e5059bd698/edit?beaconFlowId=084EDC490DE90DA7&invitationId=inv_d1431bce-05ae-4005-9b6a-9c279141a3a3&page=0_0#)
- [See mapping spec](https://docs.google.com/spreadsheets/d/1dEjcKwLWLFsROsGXefWsryHRi0pvUGGTLndFwhifWU4/edit#gid=1822444315) that has 2 main sheets (1 for adding rows to GoogleSheets, and 1 for upserting Tasks in Asana)

**Note: WCS is still on OpenFn v1 and we don't expect to move them to v2 until EOY because of features they need. Therefore, please note that all of this logic must be written in the job logic - paths and path conditions are _not_ supported in V1.**

### Resources for testing
- When you get forms from Kobo, it will return a [JSON payload like this](https://github.com/OpenFn/ConSoSci/blob/master/sample_data/sample-asset-list.json)
- [See this Google Sheet](https://docs.google.com/spreadsheets/d/1s7K3kxzm5AlpwiALattyc7D9_aIyqWmo2ubcQIUlqlY/edit#gid=0) for a sample list of forms WCS is currently syncing via OpenFn. 
- [See example Asana task](https://app.asana.com/0/1198901998266253/1206947685222161) we want to create if a new form is detected

### API docs
- Kobo: https://kf.kobotoolbox.org/api/v2/assets/
- GoogleSheets: https://developers.google.com/sheets/api/guides/concepts
- Asana: https://developers.asana.com/reference/createtask

## jobs (expression.js)
Please create a new branch off of `master` --> create 4 new jobs that should be saved in a new folder `form-sharing`. 

The 4 jobs needed should be named as follows: 
- `1-getNewKoboForms.js`  (adaptor: kobo)
- `2-getSheetsList.js` (adaptor: googlesheets)
- `3-updateSheetsList.js` (adaptor: googlesheets)
- `4-upsertAsanaTask.js` (adaptor: asana)

### Job 1: Kobo 
- configuration: see LP `OpenFn Kobo Toolbox (for WCS data access!)`
- data: {}

### Job 2 & 3: GoogleSheets 
- configuration: For now use your Google user - you have access to [this sheet](https://docs.google.com/spreadsheets/d/1s7K3kxzm5AlpwiALattyc7D9_aIyqWmo2ubcQIUlqlY/edit#gid=0)
- data: { new kobo forms detected}

### Job 4: Asana 
- configuration: For now use your Asana user - you have access to [this project](https://app.asana.com/0/1198901998266253/1206947685222161)
- data: { new kobo forms detected}

## output
If a new Kobo form is detected that has a keyword & was not previously in the GoogleSheet...
1. New row added to the GoogleSheet that looks like [Row 9](https://docs.google.com/spreadsheets/d/1s7K3kxzm5AlpwiALattyc7D9_aIyqWmo2ubcQIUlqlY/edit#gid=0)
2. New task created in Asana that [looks like this](https://app.asana.com/0/1198901998266253/1206947685222161)

When ready to test, we'll configure the jobs [in this V1 project](https://v1.openfn.org/projects/consosci-training/jobs)

## toggl
Log your time spent on this project: [WCS Support 2023/24](https://track.toggl.com/3335160/projects/195655331/tasks)

**Comment by aleksa-krolls** [comment]
@hunterachieng let's walk through this spec when we sync shortly. Once we've chatted and you've reviewed the estimate, pls add an estimate to this issue (the # of hours you _think_ this will take to build). 

FYI @taylordowns2000 this request must be delivered on v1 (not v2).

**Comment by aleksa-krolls** [comment]
welcome back @hunterachieng - are you going to be able to pick this up today?

**Comment by aleksa-krolls** [comment]
@hunterachieng as discussed on slack - use this Asana test project for now until we find the original one: https://app.asana.com/0/1207011095845846/list

**Comment by aleksa-krolls** [comment]
hey @hunterachieng I see this is in `Code Review`... does this mean this is ready for testing? I don't get notifications when you move issues between columns, so please communicate with me on here or Slack when ready to hand issues back over

**Comment by hunterachieng** [comment]
@aleksa-krolls  It is still under review by @mtuchi . After it is approved then it will be moved to review/QA and you can test. You can also test now since I added you as a reviewer

**Comment by aleksa-krolls** [comment]
@mtuchi can you pls review this today and move to Review/QA? 

@hunterachieng I will test later this afternoon after my calls

**Comment by mtuchi** [comment]
@aleksa-krolls i have already reviewed this issue and approved the PR, it's related to this PR #208

**Comment by aleksa-krolls** [comment]
@hunterachieng @mtuchi I have merged the PR to master so the client can test on v1. Now I can't get this workflow running on the platform app...

I've configured the 4 jobs [on this v1 project](https://v1.openfn.org/projects/consosci/jobs)... search `FS` to see the relevant jobs: 
<img width="1223" alt="Screenshot 2024-04-21 at 7 28 42 PM" src="https://github.com/OpenFn/ConSoSci/assets/16758106/13aa3491-ea7a-462f-ac23-d9a3bb3d310b">

When I run the workflow, it fails at step 2 with **[this run failure](https://v1.openfn.org/projects/consosci/runs/066253e9-4656-7ef4-9867-a09b45b7252d)** - looks like maybe something is off with the adaptor.
<img width="1171" alt="Screenshot 2024-04-21 at 7 32 07 PM" src="https://github.com/OpenFn/ConSoSci/assets/16758106/16d1c3c8-a0cb-42f8-9219-4889ffbbd3cf">
 
```
TypeError [ERR_INVALID_ARG_TYPE]: The "request" argum***t must be of type string. Received type boolean (true)
    at new NodeError (node:internal/errors:405:5)
    at validateString (node:internal/validators:162:11)
    at Function.paths (node:internal/modules/cjs/helpers:133:5)
    at getModuleDetails (/home/app/assets/node_modules/@op***fn/core/lib/utils.js:11:30)
    at Object.handler (/home/app/assets/node_modules/@op***fn/core/lib/cli/execute-command.js:24:27)
    at /home/app/assets/node_modules/yargs/build/index.cjs:1:8993
    at j (/home/app/assets/node_modules/yargs/build/index.cjs:1:4956)
    at _.handleValidationAndGetResult (/home/app/assets/node_modules/yargs/build/index.cjs:1:8962)
    at _.applyMiddlewareAndGetResult (/home/app/assets/node_modules/yargs/build/index.cjs:1:9604)
    at _.runCommand (/home/app/assets/node_modules/yargs/build/index.cjs:1:7231) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

Please advise on how I can fix this. If you want to re-test, you can also create your own GoogleSheets credential and link to [job FS2](https://v1.openfn.org/projects/consosci/jobs/4fGyat) and [job FS3](https://v1.openfn.org/projects/consosci/jobs/Jqa1i3) to test.

**Comment by aleksa-krolls** [comment]
Oauth issue seems to be resolved. I'm now testing on platform v1.
