### ISSUE TITLE
Create two new jobs to load data from Kobo to Googlesheets and to Asana

### ISSUE THREAD

**Issue by daissatou2** [OpenFn/ConSoSci#207]
## Background, context, and business value

WCS is looking to expand the existing [Kobo -> Asana workflow](https://v1.openfn.org/projects/wcs-grievances-kobo-to-asana/messages?dateRange=720&endDate&jobStates=&page=1&perPage=10&searchString=&startDate=2024-03-01T13%3A33%3A36.974Z&triggerId=) where OpenFn currently fetches Kobo form submissions and creates Asana tasks for each one. 

See the new [workflow diagram](https://lucid.app/lucidchart/3f6e91d6-feac-4c12-9602-60a0f9029943/edit?invitationId=inv_6fe97638-7d35-4930-9e00-ca2e538688eb&page=OQGlZYTqVO5E#) below. Everything in grey is the existing logic.
![image](https://github.com/OpenFn/ConSoSci/assets/80456839/e2791c04-4584-43a3-8ce4-f5a7c01144d2)

## The specific request, in as few words as possible

After the existing workflow upserts the data to Asana, OpenFn should do the following:
1. Sync the Kobo data to the "Form dan Log Case Keluhan" tab in this [GoogleSheet](https://docs.google.com/spreadsheets/d/1RU2Y1K7DIX_MmCaMbgIIst2Zj4v-_7J7/edit#gid=165048308) using the [mapping specifications](https://docs.google.com/spreadsheets/d/1D3_smWDjelubR_Lg-1xex9TLl6lAEGMSbGDyw8whqx4/edit#gid=1275153608). Store the `task id` returned from the upsert to Asana step (from the existing workflow logic) in the the Googlesheet. This column will be used as the UUID for the upsert steps.
2. Set up a cron step that each night will check if any changes have been made to any of the rows in the Google sheet. If there has been an update in the row, upsert the related task in Asana with the latest data using the mapping specifications. Use the "Task ID" as the UUID for the upsert step.

## state.json

**Kobo**:
configuration: see LP OpenFn Kobo Toolbox (for WCS data access!)

**Googlesheets**
For now use your own Google Account - you have access to this [sheet](https://docs.google.com/spreadsheets/d/1RU2Y1K7DIX_MmCaMbgIIst2Zj4v-_7J7/edit#gid=165048308)

**Asana**
For now use your own Asana Account - you have access to this [project](https://app.asana.com/0/1201871867457230/1204961634372655)

## adaptor
kobotoolbox
asana

## expression.js

The existing upsert to Asana job: https://github.com/WCS-ConsTech/OpenFn-GrievanceRedressMechanism/blob/master/asana/upsert-Task_Indonesia.js 

Create two new jobs:

1. Upsert Kobo data to Googlesheets (after having loaded it to Asana)
2. Upsert Asana tasks with changes recorded in Googlsheets. 

## Toggl
WCS GRM WP 1 - 2024

**Comment by daissatou2** [comment]
@mtuchi the mappings for the GoogleSheet -> Asana flow has been completed. This is ready for you to pick back up. 
https://docs.google.com/spreadsheets/d/1D3_smWDjelubR_Lg-1xex9TLl6lAEGMSbGDyw8whqx4/edit#gid=373544466

**Comment by mtuchi** [comment]
@daissatou2 i have created this issue on Grivience repo, See the issue https://github.com/WCS-ConsTech/OpenFn-GrievanceRedressMechanism/issues/3.

**Comment by aleksa-krolls** [comment]
@daissatou2 did we hear from Diane? Or are we still blocked here next week?

**Comment by daissatou2** [comment]
@aleksa-krolls I left a comment on the issue on the WCS repo: https://github.com/WCS-ConsTech/OpenFn-GrievanceRedressMechanism/issues/3

I gave Mtuchi feedback so this is back in backlog.
