### ISSUE TITLE
`PullKoboGrievanceData` job should not sync historical data more than 1 week old

### ISSUE THREAD

**Issue by daissatou2** [OpenFn/ConSoSci#220]
## Background, context, and business value

WCS has asked us to restrict historical Kobo data syncing to limit the risk of overwriting data in Asana.

## The specific request, in as few words as possible

Update the [PullKoboGrievanceData](https://github.com/WCS-ConsTech/OpenFn-GrievanceRedressMechanism/blob/staging/asana/PullKoboGrievanceData.js) job as follows:

1. If the cursor is greater than 1 week before the current date/time, do not fetch any records from Kobo. Throw an error and log message: "cursor x is older than 1 week. OpenFn will not sync Kobo records that are older than 1 week to avoid overwriting data in Asana."
2. If the cursor is "undefined", do not fetch any records from Kobo. Throw an error and log message: "cursor is undefined. Please define a cursor date no greater than 1 week ago and try again."
3. Add a comment above this new logic explaining what this does. Something like "OpenFn will not sync Kobo records that are older than 1 week to avoid overwriting data in Asana."

## state.json

```json
{
  "configuration": { "See LP : OpenFn Kobo Toolbox (for WCS data access!)" },
  "cursor": "2020-01-19 00:00:00"
}
```

## expression.js
[PullKoboGrievanceData](https://github.com/WCS-ConsTech/OpenFn-GrievanceRedressMechanism/blob/staging/asana/PullKoboGrievanceData.js)

**Create a new branch against staging. Do not merge changes to staging--create a PR.** 

## Testing instructions
1. Test with cursor date greater than 1 week -- verify job fails
2. Test with `undefined` cursor -- verify job fails 
4. Test with cursor date less than or equal to 1 week -- verify job succeeds

## toggl
WCS Support 2023/24

**Comment by daissatou2** [comment]
@aleksa-krolls This is ready for build. Can we add to the top of Mtuchi's backlog for next week's sprint?

**Comment by aleksa-krolls** [comment]
For sure @daissatou2! @mtuchi pls sync with Aissatou on this Monday

**Comment by mtuchi** [comment]
@daissatou2 just need more clarity on 2nd request 
>If the cursor is "undefined"

For a cursor to be `undefined` it means the input state does not have `state.lastEnd`. [Cleared stated or Job is running for the first time]. The way the job is set is it will use `state.lastEnd or manualCursor`. ie `manualCursor = 2023-06-13T06:01:18.729Z`. 

Just confirming, we don't want to use the `manualCursor` at all or do we want to make sure even if we are using the manualCursor it should still be within the 1 week period ?

**Comment by mtuchi** [comment]
Hiya @daissatou2 i have opened a PR 👉🏽  https://github.com/WCS-ConsTech/OpenFn-GrievanceRedressMechanism/pull/7

In this PR 
- [x] `PullKoboGrievanceData.js` will throw an error If the cursor is greater than 1 week 
- [x] `PullKoboGrievanceData.js` will throw an error if `state.cursor` is not defined 
- [x] Formatted the job code with prettier  
- [x] Added a comment on top of `isMoreThanAWeekOld` function

**Comment by aleksa-krolls** [comment]
hey @mtuchi I think what you implemented in your PR will work. I _think_ throwing an error for both scenarios (where either cursor date is > 1 week and/or if cursor date is not defined) should solve the problem @daissatou2 is hoping to solve... but I'll let her confirm 100% once she is back online tomorrow.

**Comment by mtuchi** [comment]
Okay noted @aleksa-krolls, i will wait for @daissatou2 feedback then
