### ISSUE TITLE
Update `PullKoboGrievanceData` job to log Kobo ids & trigger a failure if an empty message will be posted to the inbox

### ISSUE THREAD

**Issue by daissatou2** [OpenFn/ConSoSci#221]
## Background, context, and business value

We discovered that the `PullKoboGrievanceData` job occasionally sends empty messages to the OpenFn inbox that look like [this](https://v1.openfn.org/projects/wcs-grievances-kobo-to-asana/messages/0661e571-8eb4-76e8-aea1-3a79f7b1a4ae). WCS has asked us to update this job to proactively flag when an empty message will be sent to the inbox so that we can inspect what went wrong with the fetch from Kobo.

## The specific request, in as few words as possible

**There are two change requests:** 

1. Log the `GrievanceID` for each form that is fetched from Kobo. For example, lines 27-28 of this [log](https://v1.openfn.org/projects/wcs-grievances-kobo-to-asana/runs/0668db2e-1ce7-733e-84d5-44e01267ee2f) says that 1 form was fetched from Kobo. It should now include the `GrievanceID` for each from that is retrieved from Kobo and posted to the inbox. 
2. If an empty message was sent to the OpenFn inbox, throw an error at the end of the `PullKoboGrievanceData` job with the following message: "OpenFn sent {X number of} empty message to the inbox for {form id}. Please troubleshoot why this happened. No data will be sent to Asana for these records." Note: the job should only fail at the end after having sent all available forms submissions to the inbox. It should not fail as soon as it encounters the empty message because we want to process as much data as possible. 

## state.json

```json
{
  "configuration": { "See LP : OpenFn Kobo Toolbox (for WCS data access!)" },
  "cursor": "2024-07-09 00:00:00"
}
```

## expression.js

[PullKoboGrievanceData](https://github.com/WCS-ConsTech/OpenFn-GrievanceRedressMechanism/blob/staging/asana/PullKoboGrievanceData.js)

**Create a new branch against staging. Do not merge changes to staging--create a PR.** 

## Testing instructions 
1. You can use the cursor above to test the first requirement. Ensure that the `GrievanceID` is showing in the logs
2. We do not know what causes OpenFn to send the empty message to the inbox for certain forms so we don't have proper test data. Please test by feeding the job an empty kobo submission to try and replicate. 

## toggl
WCS Support 2023/24

**Comment by daissatou2** [comment]
@aleksa-krolls placeholder for next week

**Comment by mtuchi** [comment]
@daissatou2 i need more information before i start working on this, Will sync today after standup

**Comment by daissatou2** [comment]
Ready for you @mtuchi !

**Comment by mtuchi** [comment]
@daissatou2 i am blocked, I can't fetch the GrievanceData, i am getting `404`. Will sync after standup today

**Comment by mtuchi** [comment]
I have pushed changes but they are work in progress, they need testing. See PR https://github.com/WCS-ConsTech/OpenFn-GrievanceRedressMechanism/pull/8

**Comment by aleksa-krolls** [comment]
hey @daissatou2 what's the status here? And is there any anticipated follow-up work this week?

**Comment by mtuchi** [comment]
We couldn't test this properly last week since we didn't have the actual appropriate credentials to test the changes, But the PR https://github.com/WCS-ConsTech/OpenFn-GrievanceRedressMechanism/pull/8, has address the two comments in this issue 

cc @aleksa-krolls @daissatou2

**Comment by daissatou2** [comment]
@mtuchi I merged to staging and I am getting this [error](https://v1.openfn.org/projects/wcs-kobo-asana-staging/runs/06696d1a-e36a-756f-ba99-6b56ae702e95). Can you please investigate? 

`TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received undefined`. Feel free to test this on the staging project on platform.

**Comment by mtuchi** [comment]
@daissatou2 Can you confirm that `openfnInboxUrl` in your credential is set ?. This error happens when we are trying to post to openfn inbox

**Comment by mtuchi** [comment]
I have tried to `console.log(state.configuration.openfnInboxUrl)` i am getting undefined. [See the error here ](https://v1.openfn.org/projects/wcs-kobo-asana-staging/runs/0669760d-35e3-72bf-b42a-0f38222a9fd8). Please ask @dianedetoeuf to add `openfnInboxUrl` in that credential or create a different credential. Here is the credential schema 
```
{
    "username": "Kobo Username",
    "password": "Kobo Password",
    "openfnInboxUrl": "V1 Inbox Url"
}
```
