### ISSUE TITLE
Google Apps Script Documentation 

### ISSUE THREAD

**Issue by daissatou2** [OpenFn/ConSoSci#223]
**I have added a "Making changes to the App Script:" section to the [User Guide](https://docs.google.com/document/d/1vAPLG1Sc4pSe6L0z3J5qVfmQFcvuJ1zEGmEKuExs5iI/edit).** Can you please list any considerations there? For example, please detail:

1. How to change the cursor (which line)
2. How to change the inbox URL (which line)
3. How to "deploy" these any changes. (I see a deploy button with 3 options).
4. ...anything else to consider?

**Comment by daissatou2** [comment]
cc @aleksa-krolls for this week.

**Comment by mtuchi** [comment]
Hiya @daissatou2 i have updated the [User Guide](https://docs.google.com/document/d/1vAPLG1Sc4pSe6L0z3J5qVfmQFcvuJ1zEGmEKuExs5iI/edit) to include instruction for 
- How to change cursor
- How to change inboxUrl [it's called apiUrl in code.gs]
- And included some learnings about owner of the trigger (we call it cursor in openfn)

You don't need to deploy anything so no deploy instruction
