### ISSUE TITLE
Make a plan for managing WCS IP address updates

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/ConSoSci#50]
In the longer term, when we move WCS to their own cluster & server setup - we can provision them a static IP address. However, while they're still using OpenFn.org, the IP address regularly updates and causes job runs to fail. 

We either need to move them to a cluster or make a plan for proactively monitoring when these IP addresses update and asking Steve accordingly.... don't want to wait until WCS pings me every time/ jobs fail during regular syncs. This also don't seem like a sustainable plan given that we'll have multiple WCS integrations and DB connections running on an ongoing basis.

**Comment by taylordowns2000** [comment]
https://cloud.google.com/nat/docs/gke-example
