### ISSUE TITLE
Data dictionary requirement estimate

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/ConSoSci#76]
# Request for estimate
[See here](https://docs.google.com/document/d/1sbMbifKZ9PaaWALiD3rMdXM9T0gSGwj5dRJskBqvZx4/edit#heading=h.20fgonsklsew) for the summary of the request to create a "Data Dictionary" catalog of all Kobo metadata that is synced to the database via the Automation solution ([see data flow here](https://lucid.app/lucidchart/46b68e68-fd0d-45ca-95b7-48f887e8595f/edit?shared=true)). 
Can you please provide a dev estimate for implementing this feature? 

Consider...
1. Not only do we want to map Kobo metadata --> but we want to record the correspond DB table & column name generated as an output of the `02a` job --> see [`dataLocation` on mock questions table](https://docs.google.com/spreadsheets/d/1MemLYtWkzQosf0jlpVnWLepAuwnUHohCCcUG4tE4MR8/edit#gid=1362861050)
2. We also want to map translated labels (1 form could have multiple translations)

# state
Sample form definition
https://github.com/OpenFn/ConSoSci/blob/master/sample_data/sample-form-definition.json#L227

## Output
See sample DB table output: https://docs.google.com/spreadsheets/d/1MemLYtWkzQosf0jlpVnWLepAuwnUHohCCcUG4tE4MR8/edit#gid=0
Every time a Kobo form is synced...
1. 1 record in `forms` table is upserted
2. X records in `questions` table is upserted (where X is the # of questions in the form - see [`"survey":[...]`](https://github.com/OpenFn/ConSoSci/blob/master/sample_data/sample-form-definition.json#L227))
3. Y records in `choices` table is upserted (where Y is the # of choices in the form - see [`"choices":[...]`](https://github.com/OpenFn/ConSoSci/blob/master/sample_data/sample-form-definition.json#L819))

**Comment by lakhassane** [comment]
@taylordowns2000 should we take 5mn to talk about this? It's at the top of the backlog

**Comment by lakhassane** [comment]
@aleksa-krolls after discussions, we could go on something like:
1. 1 hour For a working prototype
2. An additional hour for refactoring
3. Test and feedbacks (from Rita and you) and corrections around 4-8h
