### ISSUE TITLE
Auto-generated job fails due to TypeError

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/ConSoSci#91]
## Describe the bug
This run is failing with `TypeError [Error]: Cannot read property 'map' of undefined`. 
https://www.openfn.org/projects/p5x4g4/runs/raa5zkb4

I _think_ we need to ensure that any repeat group mappings in these auto-generated jobs are written by default to handle undefined values. There may be scenarios where the data collector does not complete a repeat group. 

Ping @ritazagoni if you want to talk this through. 

## To Reproduce
1. This job was auto-generated via the job `02b`: https://www.openfn.org/projects/p5x4g4/runs/renkbmrz
2. Job `02b` was triggered by job `00` for Kobo form id `ayd6iLVGgvEiXnT6bRxWvH`: https://www.openfn.org/projects/p5x4g4/jobs/jyd8gg

### expression.js
Related to job `2b`

### state.json
Kobo: `openfn_kobo`
DB: `WCS ConSoSci`

## To test/resolve
See `To Reproduce` steps.

**Comment by ritazagoni** [comment]
hey @lakhassane after running the process from scratch the job failed https://www.openfn.org/projects/p5x4g4/runs/rn5a63ad

**Comment by ritazagoni** [comment]
After updating to latest `language-postgres v2.4.1` the error is the following: https://www.openfn.org/projects/p5x4g4/runs/r449x9ex
Kobo form id `ayd6iLVGgvEiXnT6bRxWvH` fetched by https://www.openfn.org/projects/p5x4g4/runs/rd7a3awp

**Comment by aleksa-krolls** [comment]
@ritazagoni can we close this now? :D
