### ISSUE TITLE
Review job-writing docs

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/ConSoSci#93]
See here: https://github.com/OpenFn/ConSoSci/blob/master/docs/5-jobWriting.md

Please suggest any changes and submit a pull request with any suggested its: https://github.com/OpenFn/ConSoSci/blob/master/docs/5-jobWriting.md

Here is the [mapping spec](https://docs.google.com/spreadsheets/d/1eGw8qxvDm34ZH6OM-6yJluMuyNwHwrax0yw-Wb2JBlw/edit#gid=0) WCS drafted themselves, and [here](https://kf.kobotoolbox.org/#/forms/a7Dx4vpFcj7ziwaKE4682U/landing) is the Kobo form (see LP  for `openfn_kobo` acct). 

They want to try writing a job for this independently, so if we can give them guidance on job patterns to consider, this will help them get started :)

**Comment by aleksa-krolls** [comment]
@lakhassane keep me posted! They're going to look at this on Monday :)

**Comment by lakhassane** [comment]
@aleksa-krolls was there any additional work needed here?

**Comment by aleksa-krolls** [comment]
@lakhassane nope, good for now! Just waiting for that `findValue(...)` function :D
