### ISSUE TITLE
Search formName for key word

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/ConSoSci#95]
## Request
We have this mapping drafted, but we can't map `formName` directly...
https://github.com/OpenFn/ConSoSci/blob/ea5f6e394d4a60b841748a30bf16417788895491/bns/price.js#L73

We want to look up the landscape (see L24) if the `formName` contains any of these key words:
https://github.com/OpenFn/ConSoSci/blob/ea5f6e394d4a60b841748a30bf16417788895491/bns/price.js#L24-L34

`formName` might be long like `"BNS Ndoki Prix 2020"` --> if anywhere in the `formName` string there is `Ndoki`, I want to return `ndoki` for landscape. What's the best way to do that? Using the method `.search()`? 

Sample state: 
https://www.openfn.org/projects/p5x4g4/messages/me6g4z4j

**Comment by lakhassane** [comment]
@aleksa-krolls you are good to test

**Comment by aleksa-krolls** [comment]
thanks @lakhassane! Passed off to the client :)

**Comment by aleksa-krolls** [comment]
@lakhassane Here is the message I've been testing against: https://www.openfn.org/projects/p5x4g4/messages/m3jq4dvn

Keep me posted when re-run on prod and I'll checkout the BD to confirm.
