### ISSUE TITLE
Update job for Vegetation form

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/ConSoSci#96]
## Background, context, and business value
We've run a new Kobo `Vegetation` form through the automated solution to generate this job: 

## The specific request, in as few words as possible
WCS wants to modify this job so that data will map to relevant relationship tables. 
- [See mapping specs](https://docs.google.com/spreadsheets/d/1eGw8qxvDm34ZH6OM-6yJluMuyNwHwrax0yw-Wb2JBlw/edit#gid=0) WCS drafted and see _yellow_ rows for changes to implement. Note that for the m:m relationships, I've already drafted the mappings for you in-line. 
- See the `Database structure` tab for the core data model, but please note that I don't think this includes all relationships. 

We need to implement changes to support both `1:m` and `m:m` relationships (highlighted rows). **Ideally, we can leverage the new `findValue(...)` function... but if this will not be available today, we need to start work on the job and  will need to follow the patterns [documented here](https://openfn.github.io/ConSoSci/jobs/#2-mapping-many1-relationships-look-ups-in-a-relational-database)** that leverage multiple sql queries to set these relationships. 

## state.json
See LP for `WCS Programs Database (central db)`
https://openfn.org/projects/p5x4g4/messages/m4pb5b8g
https://openfn.org/projects/p5x4g4/messages/mrbnqnpd
https://openfn.org/projects/p5x4g4/messages/mk57w7a4

## adaptor
`language-mssql`

## expression.js
https://openfn.org/projects/p5x4g4/jobs/jvnjwd
`vegetation/VegetationClassficationAndTreeMeasurementForm.js`

## output.json
Multiple related records upserted in mssql db. 
Feel free to run tests against the Messages (above) on prod.

**Comment by lakhassane** [comment]
@aleksa-krolls I used the pattern `findValue`to map the IDs of some relationships.

Sidenote: I saw some table names where `vegetation`is repeated twice. I don't know if that's intended but it's worth looking into those.

**Comment by aleksa-krolls** [comment]
@lakhassane I ran against a Message and encountered `UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'query' of undefined`. See run here: https://openfn.org/projects/p5x4g4/runs/rpdx6a73

Please feel free to re-run on prod as needed. See link above for additional Messages to test against, thanks!

**Comment by lakhassane** [comment]
So @aleksa-krolls I somehow made the corrections but Im bumping on some (mapping?) issues? Im trying to correct them but for some of them I can't know the right column name. Could you double check please?
<img width="614" alt="Screen Shot 2021-04-06 at 11 31 14" src="https://user-images.githubusercontent.com/8411231/113704408-9a870700-96cb-11eb-916e-a44ace265a9a.png">

<img width="571" alt="Screen Shot 2021-04-06 at 11 31 02" src="https://user-images.githubusercontent.com/8411231/113704374-935ff900-96cb-11eb-9a51-43de1909679c.png">

**Comment by aleksa-krolls** [comment]
@lakhassane We learned that some of the state samples I shared were from an old version of the Kobo form with different mappings... so please see the above links for new states like this that should align better with the mapping template: https://openfn.org/projects/p5x4g4/messages/m4pb5b8g

Feedback so far: 
1. We need to handle for scenarios where the `findValue(...)` lookup value in the `where` filter may not be defined. 
For example, see this run (https://openfn.org/projects/p5x4g4/runs/rwazbbn7) because `plotClass` is not present in state.
https://github.com/OpenFn/ConSoSci/blob/master/vegetation/VegetationClassficationAndTreeMeasurementForm.js#L64
If lookup values like `plotClass` are not defined, no need to `findValue(...)`. 

2. Add data cleaning to the lookup values like `plotClass`, `Cropstatus`, etc. to clean the dataValues to replace `_` with ` `, and capitalize the first letter. For example, if dataValue = `human_fire`, then return `Human fire`. 

3. In all of the `upsertMany(...)` operations where we build `dataArrays` from `select_multiple` questions... we should skip this operation and mapping all together if the value is not defined. 
For example, this run (https://openfn.org/projects/p5x4g4/runs/r5ed88xj) failed when `ddriver` was not defined. We should skip this part of the job if that's the case: https://github.com/OpenFn/ConSoSci/blob/master/vegetation/VegetationClassficationAndTreeMeasurementForm.js#L206-L230

**Comment by lakhassane** [comment]
@aleksa-krolls Im making the implementation here but could you clarify some points please?
1. Your first point, can we know beforehand that the lookup value is not defined or should we make a check it in the job? Having to do this will complexify it a bit. 
2. If we decide to not use `findValue` for `plotClass` what should its value be in the mapping ? `undefined` or something else? If the answer is undefined, then `findValue`will still set it to that. 

My worry is we cannot know what exist or not before we run the state, so we cannot _manually_ omit `findValue`.

**Comment by aleksa-krolls** [comment]
@lakhassane we cannot know if a value will be defined until we receive state. 
If `plotClass`, for example, is not defined in state... I expect L69 to return undefined (`WCSPROGRAMS_VegetationClassID_Other: undefined`) and the job should proceed with processing. 

If that's not possible, is there a quick check we can implement before executing the findValue step? 
e.g., `WCSPROGRAMS_VegetationClassID_Other: state => plotClass ? findValue(...) : undefined`

The issue (see run: https://openfn.org/projects/p5x4g4/runs/rwazbbn7) currently looks like the function is searching using a string `'undefined'`, and when no result is found... it throws an error, stopping the entire job.

**Comment by aleksa-krolls** [comment]
@lakhassane almost there... got through most of the errors but now encountering this on the upsertManys `TypeError: Cannot convert undefined or null to object` https://openfn.org/projects/p5x4g4/runs/r3xekjbr

**Comment by aleksa-krolls** [comment]
@lakhassane Even with the adaptor fix, I'm still running into `TypeError: Cannot convert undefined or null to object`
https://openfn.org/projects/p5x4g4/runs/ryamrnjw

**Comment by aleksa-krolls** [comment]
@lakhassane in addition to resolving the above mentioned `TypeError`, the client has configured missing DB columns. Please see [the red rows](https://docs.google.com/spreadsheets/d/1eGw8qxvDm34ZH6OM-6yJluMuyNwHwrax0yw-Wb2JBlw/edit#gid=0) for additional mappings to add.

**Comment by aleksa-krolls** [comment]
@lakhassane Still getting `TypeError: Cannot convert undefined or null to object`
https://openfn.org/projects/p5x4g4/runs/rg5ydpga

Is it because of queries like these passing `undefined`? 
```
Preparing to execute sql statement
Executing query: select WCSPROGRAMS_VegetationClassID from WCSPROGRAMS_VegetationClass where WCSPROGRAMS_VegetationClassName = 'undefined'
```
**Please test on prod to confirm this works... see above `state` section for 3 Message links to use.**

**Comment by lakhassane** [comment]
@aleksa-krolls that error has been solve but it's still failing because of `Generated_ID`column in the DB https://openfn.org/projects/p5x4g4/runs/rd75n7ka

**Comment by aleksa-krolls** [comment]
@lakhassane I need your help again. We need to filter the `dataArrays` by unique values before executing `upsertMany` statements, otherwise we encounter this error: https://openfn.org/projects/p5x4g4/runs/r9wemzp4
```
The MERGE statement attempted to UPDATE or DELETE the same row more than once. This happens when a target row matches more than one source row. A MERGE statement cannot UPDATE/DELETE the same row of the target table multiple times. Refine the ON clause to ensure a target row matches at most one source row, or use the GROUP BY clause to group the source rows.
```

See state (https://openfn.org/projects/p5x4g4/messages/mrbnqnpd) where we are trying to insert multiple `BigTrees` with the same `btspecies` name. We need to filter this repeat group array by unique `btspecies` before we try to `upsertMany(WCSPROGRAMS_VegetationBigTrees)`
```
"tree_10cm": [
      {
        "tree_10cm/bdbh": "34.5",
        "tree_10cm/bheight": "12.0",
        "tree_10cm/btspecies": "Ficus_vallis-choudae"
      },
      {
        "tree_10cm/bdbh": "48.3",
        "tree_10cm/bheight": "15.0",
        "tree_10cm/btspecies": "Ficus_vallis-choudae"
      },
      {
        "tree_10cm/bdbh": "55.7",
        "tree_10cm/bheight": "23.2",
        "tree_10cm/btspecies": "Newtonia_buchananii"
      },
      {
        "tree_10cm/bdbh": "24.0",
        "tree_10cm/bheight": "18.5",
        "tree_10cm/btspecies": "Ficus_vallis-choudae"
      },
      {
        "tree_10cm/bdbh": "23.0",
        "tree_10cm/bheight": "24.5",
        "tree_10cm/btspecies": "Ficus_vallis-choudae"
      }
    ],
```
See relevant part of job: https://github.com/OpenFn/ConSoSci/blob/master/vegetation/VegetationClassficationAndTreeMeasurementForm.js#L573-L578

**Comment by lakhassane** [comment]
@aleksa-krolls some the BigTrees have same `btsspecies`but the other parameters are different. How should we proceed then? Which one should be taken among all?

**Comment by lakhassane** [comment]
I can make the change but then only the 1st matching `Btspecies` of each will be inserted

**Comment by aleksa-krolls** [comment]
@lakhassane hm... looking at the DB. Can we do 2 things...
1. Create a custom uuid that maps to `WCSPROGRAMS_VegetationBigTreesExtCode`: `${btspecies}${height}${bdh}` and use this to upsert `WCSPrograms_VegetationBigTrees`
2. And then... only take the first array item that matches that. Even if we build this custom uuid, I worry there will be duplicates... so let's please still only take the 1st matching.

**Comment by aleksa-krolls** [comment]
@lakhassane Now it hates your `handleValue` function... I think this is thrown whenever a value is `undefined`. 
Check out these example run failures with the error `TypeError [Error]: value.replace is not a function`. 
https://openfn.org/projects/p5x4g4/runs/r7xdzp7x
https://openfn.org/projects/p5x4g4/runs/rrk49yng
https://openfn.org/projects/p5x4g4/runs/rrk49ykg
