### ISSUE TITLE
Updates to automation jobs to handle undefined repeat groups

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/ConSoSci#97]
## Background
[See docs](https://openfn.github.io/ConSoSci/kobo-automation/) on the Automation solution and prior issues. 

## Request
When the automation solution runs to auto-write sql scripts and jobs, we need to make small adjustments to the output...

We should expect that sometimes repeat groups will not be answer. Therefore auto-generate jobs need to handle that the object of `upsertMany(...)` operations might be undefined. This will come up repeatedly, so I think we need to make changes to the job `2b` that auto-writes Open jobs. 
See example run failure here: https://www.openfn.org/projects/p5x4g4/runs/rmkrj4zp
See related slack thread: https://openfn.slack.com/archives/G2LJCFFDW/p1617887226025400

**Note: we are training on this solution Monday, so if changes are not 100% complete, please push to a separate branch for us to merge after the training.**

## To Reproduce
This job was auto-generated via the job 02b - e.g., https://www.openfn.org/projects/p5x4g4/runs/ren7m767
Job 02b is triggered by job 00 for Kobo - e.g.,  form id `apZrpKcK78xzrPcAfRrfac` https://www.openfn.org/projects/p5x4g4/runs/rwazbzr7

## expression.js
Related to jobs 2b

## state.json
Kobo: `openfn_kobo`
DB: `WCS ConSoSci`

**Comment by lakhassane** [comment]
@aleksa-krolls this is the correction I made yesterday about `language-postgresql`. We are still seeing in on the linked run because it is using `v2.4.3` instead of `v.3.1.1`(which holds the latest changes).
See last run using `v3.1.1` https://www.openfn.org/projects/p5x4g4/runs/rg5ym89e
