### ISSUE TITLE
Automation jobs: change CamelCase format in DB output

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/ConSoSci#98]
## Background
[See docs](https://openfn.github.io/ConSoSci/kobo-automation/) on the Automation solution and prior issues. 

## Request
When the automation solution runs to auto-write sql scripts and jobs, we need to make small adjustments to the output...
Job `2a` currently outputs a sql script with database configuration changes that need to be made. Currently the database columns mirror the Kobo questions exactly (e.g., if the Kobo question is `landing_site`, the DB column name is also `landing_site`). 
E.g., `landing_site: dataValue('landing_site'),` - see job: https://www.openfn.org/projects/p5x4g4/jobs/jvbbkm

WCS wants to apply the CamelCase convention across all DB configuration, including column names. Therefore when determining the DB column names to configure, please clean the Kobo question names to remove `_` and capitalize the first letter in each separate string. This way `landing_site` ==> `LandingSite`, and the mapping in the job should look like: 
`LandingSite: dataValue('landing_site'),`

## To Reproduce
These jobs are auto-generated via the job 02a: https://www.openfn.org/projects/p5x4g4/runs/renkbmrz
Job 02b is triggered by job 00 - e.g., Kobo form id `ayd6iLVGgvEiXnT6bRxWvH` https://www.openfn.org/projects/p5x4g4/jobs/jyd8gg

## expression.js
Related to jobs 2a

## state.json
Kobo: `openfn_kobo`
DB: `WCS ConSoSci`

## Expected behavior
Column headers should look like...
`landing_site` ==> `LandingSite: dataValue('landing_site')`
`new.question` ==> `NewQuestion`
`surveyor__name` ==> `SurveyorName`

**Comment by lakhassane** [comment]
@aleksa-krolls I made the changes for all columns. What about `table names`? Are they included?
```js
upsertMany(
  "wcs_sharks_and_rays_SharksAndRays_Boat",
  "GeneratedUuid",
  (state) => {
    const dataArray = state.data["boat"] || [];
    return dataArray.map((x) => ({
      BoatInfo: x["boat/boat_info"],
      BoatType: x["boat/boat_type"],
...
```

**Comment by aleksa-krolls** [comment]
@lakhassane Table names should also be CamelCase... but with the convention `prefix1_prefix2_TableName_RepeatGroup` ...so each component `p1`, p2`, `TableName` should have CamelCase applied, if not already... but keep the `_` between.

**Comment by aleksa-krolls** [comment]
@lakhassane This CamelCase is causing uniquess issues... this form  `aF83yMqfW5AikzRkvca8Bx` has 2 fields: `_version_`,  `__version__`.  

When we apply CamelCase, job `02a` fails with the error `error: column "version" specified more than once`. See run:
https://www.openfn.org/projects/p5w6xn/runs/rwazwr9j

What do you think is the easiest way to handle this? Maybe if only 1 underscore `_`, we remove... but otherwise keep `_` if there are double or more? So output would be... 
`_version_` --> `Version`
`__version__` --> `_Version_`

Open to suggestions!

**Comment by lakhassane** [comment]
I left it as is @aleksa-krolls so should not be a problem to insert now.
`_version_` --> `_Version__`
`__version__` --> `__Version__`

**Comment by lakhassane** [comment]
@aleksa-krolls you misplaced the comment in a closed issue. However, I made the change for the camel case of `generated_uuid`

**Comment by aleksa-krolls** [comment]
@lakhassane thank you!! will check it out

**Comment by aleksa-krolls** [comment]
@lakhassane `generateduuid` is fixed, but the same change also needs to be made on the `parentuuid` column on child tables created for repeat groups.

Right now I'm seeing in the auto-generated job, there is a `_` in these parentuuid column names - e.g., `boat_uuid` on L157
https://www.openfn.org/projects/p5w6xn/jobs/jvebeg

But the SQL script is correctly outputting `BoatUuid`
https://www.openfn.org/projects/p5w6xn/runs/ryae595x
