### ISSUE TITLE
Automation job 01-processForm.js failed with TypeError

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/ConSoSci#99]
## Describe the bug
This happened while @ritazagoni was running the automation solution during training. See run failure with error: `TypeError [Error]: Cannot read property 'path' of undefined at questionToType `
https://www.openfn.org/projects/p5w6xn/runs/raakb8pn

## To Reproduce
Here is the run that triggered this whole flow: https://www.openfn.org/projects/p5w6xn/runs/ren7d9yk
Let @aleksa-krolls or @ritazagoni know if you need help replicating. 

### expression.js
https://github.com/OpenFn/ConSoSci/blob/master/automation/01-processForm.js

### state.json
DB: `WCS ConSoSOc DB (For automation testing)`
Re-run job `A1`: https://www.openfn.org/projects/p5w6xn/jobs/jyjxzd

## Expected behavior
This should trigger jobs 2a (aka `A3`) and 2b (aka `A4`) to write to Postgres and create OpenFn jobs. Looks like there maybe is a question type the job is not setup to handle?

**Comment by lakhassane** [comment]
Hey @aleksa-krolls this is what I found when I try to display the content of that `survey`. Looks like `content`is empty
<img width="510" alt="Screen Shot 2021-04-13 at 12 35 07" src="https://user-images.githubusercontent.com/8411231/114552987-af781300-9c54-11eb-86d0-f60c32926755.png">

Checking in `kobotoolbox`I see the form has not been deployed yet.

**Comment by aleksa-krolls** [comment]
@lakhassane Interesting, thanks for finding... so @ritazagoni we can add as a step to ask users to make sure their Kobo forms are deployed and not archived before trying to run through the automation solution.

**Comment by aleksa-krolls** [comment]
@lakhassane how much level of effort would it be to add a step to handle this error and log a message like `Kobo form not deployed or not defined. Please check the Kobo form status.` If <30 min, can you please implement?
